### ISSUE TITLE
Не работает алгоритм PHi

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#10]
я так понял не загружается майнер от него, я его сам загрузил, но он всё равно не запускается

**Comment by Quake4** [comment]
блокируется антивирусом?

**Comment by danik-guitar** [comment]
не. просто не отображает этот алгоритм в списке и не загружает сам майнер.

**Comment by Quake4** [comment]
каталог в bin с майнером "ccminer-phi-10" есть?

**Comment by danik-guitar** [comment]
Каталог есть, я посмотрел путь и сам загрузил, но это не помогло

**Comment by Quake4** [comment]
после загрузки, MM просит подтверждение на выполнение бенчмарка.

**Comment by Quake4** [comment]
надо нажать Y

**Comment by danik-guitar** [comment]
В том то и дело. ничего не просит сразу начинает майнить. я только на zpool включал. Вот скрин алгоритмов на zpool .
![qip shot - screen 03 03 18 22-55-31](https://user-images.githubusercontent.com/30734827/36938663-fc75906e-1f35-11e8-8ac4-3182120b97eb.png)

**Comment by Quake4** [comment]
содержимое файла ccminer-phi-10.txt из stat

**Comment by danik-guitar** [comment]
активировал другой пул и появилось предложение пройти бенчмарк и этот алгоритм

**Comment by Quake4** [comment]
да, phi сейчас на zpool отключен: https://www.zpool.ca/api/currencies

**Comment by Quake4** [comment]
Написал в поддержку вернули.
