### ISSUE TITLE
Add ccminerdumax

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#100]
https://github.com/DumaxFr/ccminer/releases/download/dumax-0.9.3/ccminer-dumax-0.9.3-win64.zip

**Comment by Quake4** [comment]
What is the speed of the algorithms on 1070?

**Comment by platinum4** [comment]
benchmark and try, its fast on phi2

**Comment by platinum4** [comment]
Miner        Algorithm(s)         Profit Accuracy    Speed(s) Pool          Info
                                 USD/Day                      [Region]
-----        ------------ -------------- --------    -------- ------------- ----
CcminerDumax Phi2               2.451685      99%   6.72 MH/s Blaze [US]    ProfitFactor: 0.990 (Fee: 1.0%) [Workers: 28 / Coins: 1]
CcminerDumax PHI                1.043517      97%  39.12 MH/s BM [US]       ProfitFactor: 0.998 (Fee: 0.3%) [Workers: 1 / Coins: 2]
CcminerDumax X16R               0.954663      99%  19.13 MH/s ZergP [US]    ProfitFactor: 0.995 (Fee: 0.5%) [Workers: 531 / Coins: 4]
CcminerDumax Tribus             0.965838      94% 109.69 MH/s ZergP [US]    ProfitFactor: 0.995 (Fee: 0.5%) [Workers: 10 / Coins: 3]
CcminerDumax X17                0.812608      98%  19.90 MH/s ZP [US]       ProfitFactor: 0.983 (Fee: 1.8%) [Workers: 496 / Coins: 4]
CcminerDumax X16S               0.590801      86%  21.76 MH/s BM [US]       ProfitFactor: 0.998 (Fee: 0.3%) [Workers: 2 / Coins: 1]
CcminerDumax C11                0.102809      94%  28.30 MH/s BM [US]       ProfitFactor: 0.998 (Fee: 0.3%) [Workers: 134 / Coins: 5]
CcminerDumax Timetravel        -0.600408      95%  51.60 MH/s Blaze [US]    ProfitFactor: 0.990 (Fee: 1.0%) [Workers: 9 / Coins: 1]

2x 1070s 112% PL +440mem
