### ISSUE TITLE
Zergpool LTC balance doesn't show up, Blockmasters does

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#102]
Check and see on the display/request for this info, doesn't show LTC balances.

**Comment by Quake4** [comment]
possible is zero?

**Comment by platinum4** [comment]
ill check in a bit

**Comment by platinum4** [comment]
It doesn't seem to work but i think zergpool is only mining balloon so i dont know if that goes to LTC

**Comment by Quake4** [comment]
is working?

**Comment by platinum4** [comment]
yes ty
