### ISSUE TITLE
Disable Keccak on Yiimp pools, leave for Nicehash only

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#103]
too many rejects

**Comment by Quake4** [comment]
I know, but fine tuning is user territory. MindMiner is instrument.

Config manual:
https://github.com/Quake4/MindMiner/blob/master/Config.md
Zpool/Zergpool.config.txt
    "DisabledAlgorithms": [ "Keccak" ],

And i write this in forum.

**Comment by platinum4** [comment]
Need do https://github.com/Quake4/MindMiner/issues/115
