### ISSUE TITLE
MindMiner 2.54 not bench passed

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#104]
У меня возникает ошибка при бенчмарке, так как ферма из разных видюх, в частности ошибка в том, что при запуске бенчей, одновременно запускается несколько майнеров и несколько разных алго, в последствии это приводит к BSOD///.,,,, 
Так же скажите плиз, как отключить майнинг и бенчи для видюхи АМД 240, я не хочу задействовать её в майнинге, к ней просто подключен  монитор....

**Comment by Quake4** [comment]
ММ не останавливает запущенный майнер?

#71 Прописать так же как "-di 1" в настройках sgminer

**Comment by BARUCHER777** [comment]
Нет не останавливает, но параметр "-di 1" я думал прописывают только для майнеров от Клеймора, в других майнерах что-то другое вроде....
Да и не могли бы вы сделать опционально, при первом запуске майнера, что-бы было можно выбрать какие видюхи задействовать для майнинга, а какие не задействовать ?.... Было бы очень удобно и все же проще, чем постоянно копаться в конфигах для каждой из видюх по отдельности....

**Comment by Quake4** [comment]
Не останавливается конкретный майнер или все?
`-di` условно, в каждом майнере по своему.
Подумаю.

**Comment by BARUCHER777** [comment]
Вы не могли бы сделать хоть так, что-бы бенчи запускались, последовательно, допустим сначала, проход бенчей для амд карт, а потом для нв, ну или наоборот, у меня на пяти последних ваших версиях, при бенчах постоянно вылетает BSOD....

**Comment by Quake4** [comment]
Проверьте питание и разгон. Добавлены новые майнеры для nvidia. Они более требовательны к разгону и питанию карт. Если не проходит бенч, значит есть проблемы с ригом. Попробуйте сбросить разгон до заводских установок.

**Comment by BARUCHER777** [comment]
Разгон при запуске вашего софта вообще не использую, все майнеры запускаются на стоковых параметрах!

**Comment by Quake4** [comment]
В большинстве случаев параметры майнинга стандартные, только для каких-нибудь c11 или lyra2z есть дополнительные параметры.
Попробуйте использовать CoolDown переменную секунды в 3-5.
Попробуйте все карты установить в PL = 90%. Скорее всего проблема с питанием на риге.
Обратите внимание на столбец ExtraArgs он как раз указывает дополнительные параметры запуска.

**Comment by Quake4** [comment]
Можно вот еще что попробовать:
https://support.allegorithmic.com/documentation/plugins/servlet/mobile?contentId=128745489#content/view/128745489

**Comment by BARUCHER777** [comment]
ок, спасибо за инфу, попробую.

**Comment by platinum4** [comment]
Need English cannot help

**Comment by Quake4** [comment]
Заработало? 
Тут выяснилось что в файле hosts был кривой мапинг не на 127.0.01 и MM не работал.
Попробуйте последнюю версию. Может у вас то же самое?

**Comment by BARUCHER777** [comment]
У вы не работает, не новая весрия, не обновленная старая, в новой пишет после внесения конфига 
"NO POOLS" а в старом варианте тесты бенчей вообще теперь перестали запускаться....

**Comment by Quake4** [comment]
Так BTC адрес не указан

**Comment by Quake4** [comment]
А для MPH не указан логин.
Это такая шутка? Что ничего не работает?

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/42682346-04b566a4-8693-11e8-82c1-be359657ba14.png)
Нет адресов:
![image](https://user-images.githubusercontent.com/29517243/42682365-10f9e5e8-8693-11e8-9bf6-dacacfa974e0.png)

**Comment by BARUCHER777** [comment]
Сделал перезапуск, теперь все это есть, но бенчи как-бы перезапускаются постоянно...
