### ISSUE TITLE
Miner adjustments

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#109]
Remove Keccak and Pascal, because Keccak is full of FPGA miners, and Pascal is ASIC territory now.

Extend XMRig AMD benchmark interval to 120 sec, because of slow kernel compiling.

Sgminer-kl and sgminer-djm always failing benchmarks also. I have RX 580 and RX 560 in compute mode in same rig, latest 18.5.1 driver.

**Comment by platinum4** [comment]
All can be done with miners config.txt file in \Miners

**Comment by jestercore** [comment]
Yes, but we all need this, i think.

**Comment by Quake4** [comment]
if you run manually Sgminer-kl and sgminer-djm. please show output error.

**Comment by Quake4** [comment]
while "eth + keccak" more profitable than "eth" only.

**Comment by jestercore** [comment]
So, i've run Sgminer-kl batch files, now i have binary files and it's still not working. Mindminer still fails it. Miner starts and closing immediately, no specified error. Maybe Mindminer giving wrong config to it.

Sgminer-djm don't have any batch files, writing it would take so much time. Ain;t benchmarking too.

> while "eth + keccak" more profitable than "eth" only.

No rejects at this time? We still don't Pascal, tho.

**Comment by platinum4** [comment]
Put this:

{
    "Algorithms":  [
                       {
                           "ExtraArgs":  "-dcri 70",
                           "DualAlgorithm":  "blake2s",
                           "Algorithm":  "ethash",
                           "Enabled":  true
                       },					   
                       {
                           "ExtraArgs":  "-dcri 10",
                           "DualAlgorithm":  "keccak",
                           "Algorithm":  "ethash",
                           "Enabled":  true
                       }
                   ],
    "BenchmarkSeconds":  120,
    "Enabled":  true
}

**Comment by platinum4** [comment]
need disable keccak and blake2s on all pools except nh

**Comment by Quake4** [comment]
try set: GPU_FORCE_64BIT_PTR=0

**Comment by Quake4** [comment]
> need disable keccak and blake2s on all pools except nh

i dont disable any algos on pools. its user settings

**Comment by Quake4** [comment]
> No rejects at this time? 

NH - yes. I switch to keccak at zergpool.

**Comment by platinum4** [comment]
Hi I talk to the guy have the problem Hi

**Comment by Quake4** [comment]
> Put this:

I have other optimal values. This values look like from 1080Ti.
I can create all values with step 10 from 10 to 100 ;)

**Comment by platinum4** [comment]
Don't do that it creates too many cross-contaminated profit earnings Hi

**Comment by Quake4** [comment]
right now one rx 584 no bios mod
```
   Type: AMD

Miner                 Algorithm            Speed, H/s
-----                 ---------            ----------
%sgminer-kl-105f      X16r                     7,01 M
+sgminer-kl-105f      Aergo                    3,45 M
claymore-neoscrypt-12 NeoScrypt              785,85 K
sgminer-kl-105f       X17                      7,80 M
claymore-dual-118     Ethash+Blake2s   12,98 M+1,30 G
claymore-dual-118     Ethash+Keccak     8,87+263,27 M
claymore-zcash-126    Equihash                 274,15
castxmr-130           Cryptonightheavy         448,96
claymore-eth-118      Ethash                  14,08 M
```

**Comment by Quake4** [comment]
where is blake2s & keccak no profit?

**Comment by platinum4** [comment]
it's like barely 5 cents more to add keccak its not worth the power he's saying

oh wait no power consumption read yet issue #54 Hi

**Comment by Quake4** [comment]
not everyone pays for electricity.
you can manual configure MM to any needed configuration. diable dual, enable only lyra2z.
But then why do we need MM?

**Comment by platinum4** [comment]
cuz then id miss the wave of profitable lyra2re2 on nicehash like yesterday morning.  try and be open to suggestions we want to help you make a great miner

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/42473379-2a1b116e-83cd-11e8-85a5-5913913c4e68.png)

MM dont miss it.

**Comment by Quake4** [comment]
I am trying to make a miner that works consistently and provide a basic configuration suitable for most cases, but fine tuning is given to advanced users like you.

**Comment by jestercore** [comment]
> this miners is 32bit, try to set: GPU_FORCE_64BIT_PTR=0
This solved issue, thank you! Add note about it in FAQ, please.

> right now one rx 584 no bios mod
No compute mode? 580 even in stock should hash something like 20-25mh

Mindminer is awesome software, we don't need to delete uncommon algos. But some of are for Baikal Giant-B only, like Pascal. Never seen it more than profitable other dual or eth only.

**Comment by platinum4** [comment]
Fix keccak drop
https://github.com/Quake4/MindMiner/issues/115

**Comment by Quake4** [comment]
I'll remove keccak & pascal after dual profit drops than single ethash.

**Comment by JayGaming** [comment]
**HELP ME WITH THIS SIR QUAKE4? PROGRAM EXITS**
```
[[Timeout Loop/Check/No Hash: 60 sec/5 sec/10 min
Hash Speed Average/Current: 1 day/180 sec
      Switching Resistance: True as 5% or 12 min
             Active Miners: CPU, Intel <= Allowed: CPU, nVidia, AMD, Intel
                API Server: Disabled
                    Region: Europe

CPU x 1: Intel Core i3-5005U @ 2.00GHz, 1995 Mhz, 2/4 Core/Thread, MMX SSE SSE2 SSE42 AES AVX AVX2

   Type: CPU

Miner             Algorithm Speed, H/s BTC/Day USD/Day BTC/GH/Day Pool         ExtraArgs
-----             --------- ---------- ------- ------- ---------- ----         ---------
cpuminer-opt-3881 Bitcore   Need bench 30 sec  30 sec  0.00214825 ZergPool-BTX
cpuminer-opt-3881 X16r      Need bench 30 sec  30 sec  0.00438969 NiceHash-EU
cpuminer-opt-3881 X17       Need bench 30 sec  30 sec  0.00423075 BlockMasters

+ Running, - No Hash, ! Failed, % Switching Resistance, * Specified Coin, ** Solo|Party, _ Low Profit


Pool      Confirmed, BTC Unconfirmed, BTC Balance, BTC Balance, USD
----      -------------- ---------------- ------------ ------------
BlazePool     0.00000000       0.00000000   0.00000000         0.00
NiceHash      0.00000000       0.00000000   0.00000000         0.00
Total:        0.00000000       0.00000000   0.00000000         0.00

Information:
 Loop/Used RAM:        1/70.3 Mb
  Run/Fee Time: 00:05:38/00:00:00 (0.0 %)
Boot/Rate Time: 01:21:17/00:54:25]([url](url))](url)
```
