### ISSUE TITLE
ccminer source code?

### ISSUE THREAD

**Issue by nemosminer** [Quake4/MindMiner#11]
Original 2x Issue was closed by MindMiner no explanation (apart from providing source code : https://github.com/sp-hash/ccminer) this source code has not had a update in over a year and has no bitcore support)

#5 https://github.com/Quake4/MindMiner/issues/8

ccminer source code? for ccminer spmod-bitcoin2

GNU General Public License v3.0
Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

**Comment by nemosminer** [comment]
you are not allowd to have a binary avalible for download with a complete source code...

you need to change bitcore algo to a different ccminer or provide a full soucre code. for ccminerbitcorespmod2..

**Comment by Quake4** [comment]
Нou demand that I delete this: https://github.com/Quake4/MindMinerPrerequisites/tree/master/nVidia/ccminer-bitcore ?

**Comment by nemosminer** [comment]
yes 
you can change it to a different ccminer.. this is what i use for bitcore..
https://github.com/nemosminer/tpruvot-ccminer/releases/download/v2.2-tpruvot/ccminer-x86-2.2.7z

im trying to help you...

**Comment by Quake4** [comment]
I is remove it. Thanks.
