### ISSUE TITLE
[Miner update] coolminer 1.5

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#111]
https://bitcointalk.org/index.php?topic=4412370.msg41755754#msg41755754

**Comment by Quake4** [comment]
can you test?

**Comment by Quake4** [comment]
miner:
https://github.com/Quake4/MindMiner/raw/master/Miners/ccminer-cool-15.ps1

**Comment by mo35** [comment]
for 1.15

*Fixed "--benchmark" mode, now you can benchmark lyra2z algo.
*Fixed memory leaks in lyra2z.c
*Should be more stable then v1.4, also will exit miner if no connection to pool.
*Time between fee mining increased by 20%(every hour+, less pool switching per 24H).
*Added "Blks.found:" to display the number of Block Found.

performance is same as 1.14 , but i personally prefer coolminer over cryptodredge for lyra2z , due power consumption , temps , and that cryptodredge implemented devfee using awful method

p.s. 1.15 download in your PS points to 404 ;)

**Comment by Quake4** [comment]
2.60
