### ISSUE TITLE
[Miner update] z-enemy 1.12a public

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#112]
zealot/enemy-1.12a (z-enemy)  From: Dk & Enemy

- Improved phi2 performance: +4-5% (up to 5 Mh/s for 1070ti, up to 7.5 Mh/s for 1080ti)
- Minor performance improvements for other algos

https://bitcointalk.org/index.php?topic=3378390.0

p.s. no rest for wicked ;P

**Comment by Quake4** [comment]
Added, just not released  yet.
