### ISSUE TITLE
srbminer

### ISSUE THREAD

**Issue by Quake4** [Quake4/MindMiner#113]
http://www.srbminer.com/
https://bitcointalk.org/index.php?topic=3167363

**Comment by platinum4** [comment]
Yes is good and important for AMD upcoming V8 fork

**Comment by platinum4** [comment]
It would be nice if you figure out how to do the command lines for v1.6.8 since this is a better cnv8 miner than xmrig or xmr-stak for AMD

**Comment by platinum4** [comment]
Need add or close this; JCE is fine for AMD now

**Comment by Quake4** [comment]
i add it but later

**Comment by platinum4** [comment]
still looking to add this; forager has this just fine

https://github.com/yuzi-co/Forager/blob/master/Miners/A-SRBMiner-1.7.9.json

**Comment by platinum4** [comment]
Need add for V1.8.0

**Comment by Quake4** [comment]
https://github.com/doktor83/SRBMiner-Multi/releases

**Comment by platinum4** [comment]
Hi,

I think you are able to close this, you already have srb-20
