### ISSUE TITLE
M7M profit

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#114]
These seems wrong.

1 CPU 4790K making more than 3 GPUs a day mining ETH...

**Comment by platinum4** [comment]
https://i.imgur.com/JU6NBLD.png

**Comment by platinum4** [comment]
Makin' dat money

**Comment by Quake4** [comment]
API send wrong data?

**Comment by Quake4** [comment]
What's the matter?

**Comment by platinum4** [comment]
Nothing it's fine
