### ISSUE TITLE
Editing "DisabledAlgorithms" for pools

### ISSUE THREAD

**Issue by rinkal26783** [Quake4/MindMiner#117]
I was trying to disable hmq1725 algo from zpool and zergpool. but after updating poo.config files. Mindminer asked for benchmark.
After pressing Y button. It displayed messages 
Do you want to mind zpool (Yes/No) No
Do you want to mind zergpool (Yes/No) No
It disabled those pools. there values in pool.config file changed as.
    "Enabled":  false,
    "AverageProfit":  "1 hour 30 min",
    "SpecifiedCoins":  null,
    "EnabledAlgorithms":  null,
    "DisabledAlgorithms":  null

**Comment by Quake4** [comment]
you write wrong json format. config not parsed. created default.
