### ISSUE TITLE
Messages in bluebar 

### ISSUE THREAD

**Issue by rinkal26783** [Quake4/MindMiner#119]
These messages keep running with mindminer

 Reading web response
    Reading response stream... (Number of bytes read: 15918)
 Reading web response
    Reading response stream... (Number of bytes read: 15918)

**Comment by Quake4** [comment]
run IE and continue configuration steps

**Comment by Quake4** [comment]
if ie runs normally, then fine configured
![image](https://user-images.githubusercontent.com/29517243/43899153-b39f8fb2-9be9-11e8-81f1-a07f1a1967f4.png)
try set latest updates to net framework

**Comment by AcharyaOne** [comment]
I closed this window by mistake, is there anyway to run this wizard again?

**Comment by Quake4** [comment]
just rerun ie. if no window, possible its normal configured.
