### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Imaminer** [Quake4/MindMiner#12]
AMD rig...Latest MindMiner..All prerequisites installed...
Please see pics.. Miner does not find pool and will not run for me.
Thanks

![mindminer1](https://user-images.githubusercontent.com/30805282/37163217-3127dfbe-22c5-11e8-91b8-57ff245395a8.JPG)

![mindminer2](https://user-images.githubusercontent.com/30805282/37163248-46969a52-22c5-11e8-9697-6c5538e0cde7.JPG)

![inkedmindminer3_li](https://user-images.githubusercontent.com/30805282/37163359-93d0d116-22c5-11e8-9f0d-a41d23c65d47.jpg)

![mindminer4](https://user-images.githubusercontent.com/30805282/37163275-5251b80e-22c5-11e8-9764-bc036be26f20.JPG)

**Comment by Imaminer** [comment]
Just adding that I have full permissions to the folder and all the latest .net is installed. I have tried multiple config files. Same errors no matter what I try. Thanks

**Comment by Quake4** [comment]
All works after Net install or permissions to folder?

**Comment by Imaminer** [comment]
No nothing works.

**Comment by Quake4** [comment]
Windows 7 or 10 (32bit or 64bit)?

**Comment by Imaminer** [comment]
Win10 64 bit creator

**Comment by Imaminer** [comment]
Latest AMD drivers with compute on for cards

**Comment by Quake4** [comment]
please, manual run from cmd :
MindMiner\Bin\AMDOpenCLDeviceDetection.exe
MindMiner\Bin\FeatureDetector.exe

**Comment by Imaminer** [comment]
I dont know how to get all the info on the screen. Had to make a .bat file to get this far 
![opencl](https://user-images.githubusercontent.com/30805282/37242374-5201a982-2436-11e8-8177-4ec26bdc3b3d.JPG)

![feature](https://user-images.githubusercontent.com/30805282/37242394-98b2c2bc-2436-11e8-94ad-d45892e0ba6e.JPG)

**Comment by Quake4** [comment]
thanks, strange, all fine with its.
place bat file int MindMiner-1.16 folder with content:
"run.bat > log.txt"

Run this file. Wait 3-5 minutes. Close window. And send to me file log.txt.

**Comment by Imaminer** [comment]
[log.txt](https://github.com/Quake4/MindMiner/files/1799831/log.txt)

**Comment by Quake4** [comment]
please, try to reinstall net framework: http://go.microsoft.com/fwlink/?LinkId=852107

**Comment by Imaminer** [comment]
![net](https://user-images.githubusercontent.com/30805282/37247801-3369b5c4-248f-11e8-9362-565712668da4.JPG)

**Comment by Quake4** [comment]
thanks. very strange.
please, remove "Bin" folder and run "run.bat"

**Comment by Quake4** [comment]
Please run powershell console: right mouse click on start button - "powershell"
type this and press enter:
$PSVersionTable

**Comment by Quake4** [comment]
Dear, Imaminer.

I wait for your replay if you want to run MM.
I would be interested to deal with this problem because it isn't trivial.
