### ISSUE TITLE
Add zFastminer-v2.3.4

### ISSUE THREAD

**Issue by rinkal26783** [Quake4/MindMiner#120]
Hello Oleg,
Can you please add zFastminer-v2.3.4 for miningpoolhub lyra2z
it is 30% more faster compare to other miners.

**Comment by Quake4** [comment]
Not yet. MM does not support miners without API yet.

**Comment by Quake4** [comment]
https://bitcointalk.org/index.php?topic=3259259.msg40652971#msg40652971

you try? look pool side speed?

**Comment by rinkal26783** [comment]
I tried it. It gave me 9500 mh on my gtx 1060 rig.

**Comment by rinkal26783** [comment]
but other are saying there is already another miner (t-rex) having same speed
https://bitcointalk.org/index.php?topic=4432704.0
but t-rex use more voltages compare to zFastminer-v2.3.4

**Comment by Quake4** [comment]
Sorry t-rex & zfast, MM does not support miners without API yet.

**Comment by Quake4** [comment]
scam

**Comment by Quake4** [comment]
t-rex faster
