### ISSUE TITLE
MindMiner-2.65  -  X17 Algo Not Started, Not worked this algo, in lastest versions!

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#124]

**Comment by BARUCHER777** [comment]
X17 algorithm does not work absolutely, no matter what settings and parameters of video cards!
I attach screenshot of the screen!

![x17_algo-ntsrt](https://user-images.githubusercontent.com/18327150/42704684-799fa786-86d9-11e8-80d0-477da65a1d44.jpg)

**Comment by Quake4** [comment]
Possible, blockmasres  x17 stratum isnt working.
Disable block, hash & blaze.

**Comment by BARUCHER777** [comment]
ccminer-alex-01
Very more ALL REJeCTed`s

![x17morerejects](https://user-images.githubusercontent.com/18327150/42711224-ba6e793e-86ef-11e8-9513-739dac62d7e6.jpg)

**Comment by Quake4** [comment]
Please, remove mindminer.

**Comment by Quake4** [comment]
I dont undersand what's wrong in you rig.

**Comment by Quake4** [comment]
Speed is unknown. Its very bad.

**Comment by BARUCHER777** [comment]
The rest of the algorithms work and the benchmarks pass!
