### ISSUE TITLE
[Miner Update] Cryptodredge 0.7.0

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#125]
https://github.com/technobyl/CryptoDredge/releases

improve defvee mechanism
Add --retries, --retry-pause, and --timeout options.
Check Readme for more information
Build first Linux version
Other minor fixes

**Comment by Quake4** [comment]
added, just not released

**Comment by Quake4** [comment]
https://github.com/Quake4/MindMiner/commit/e5d51357afa381748b3f87b7692da279b5763081

**Comment by Quake4** [comment]
2,66
