### ISSUE TITLE
[Miner update] T-Rex 0.5.1

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#128]
https://mega.nz/#!6Rk1xa5A!0Du8UIFg0Ue6dmmXwHKEZPwNVbaYDCOTse4Jk9cqsO8

**Comment by platinum4** [comment]
Need do

**Comment by Quake4** [comment]
Isnt changes with 0.5.0.
Only my issue about ccminer compatible api.

**Comment by platinum4** [comment]
What was that supposed to mean?

**Comment by platinum4** [comment]
Hi everyone, we just released a new version of our miner - 0.5.1

Changes:
Faster phi2, lyra2z, x17, c11.
Added new algo HSR.
Added API (HTTP JSON [preferable option, very flexible] and telnet ccminer compatible) - pending integration with monitoring software (ethmonitoring, awesome miner etc.)
Multiple bug fixes, new config options, failover pools.

**Comment by platinum4** [comment]
Multiple bug fixes

**Comment by platinum4** [comment]
Added new algo HSR.

**Comment by platinum4** [comment]
We are going to release a new version in a few hours, hopefully your problem is resolved in 0.5.1 (we fixed a lot of bugs in 0.5x)

**Comment by Quake4** [comment]
> Multiple bug fixes
In 0.5.0.
0.5.0 vs 0.5.1 only api fix.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/42923875-62e1e5c6-8b30-11e8-913f-e2dd60b68524.png)
