### ISSUE TITLE
Be transparent with your benchmarks, all benchmarks go to fee address and not the user

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#129]
Hi,

Watching programs that show the logged in user during "Benchmark needed" they all go to address that's not mine.

If you are going to take the benchmarks be sure to fairly include them in fee please.

**Comment by Quake4** [comment]
I transparent.
Read main page:
Fee: MindMiner has development fee 1% and all benchmarks.

**Comment by AcharyaOne** [comment]
Why do you take all benchmarks as fee?

**Comment by Quake4** [comment]
Why you work? I'm working on the MM too.
