### ISSUE TITLE
неправильно считает кессакс

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#13]
![image](https://user-images.githubusercontent.com/30734827/37244010-a7e9c836-2493-11e8-9df6-36c1f3787389.png)

**Comment by Quake4** [comment]
Если версия последняя 1.18, то либо удалить файлы статистки пулов и перезапустить, либо удалить алгоритм из файлов статистики пулов и перезапустить, либо подождать пока "пройдет",

**Comment by Quake4** [comment]
И Win 32bit?

**Comment by danik-guitar** [comment]
64 . До этого норм было. Скорость карт то правильно показывает

**Comment by danik-guitar** [comment]
Статистику пула удалял. Не помогло

**Comment by danik-guitar** [comment]
удалил статистику всех пулов вообще и стало норм
