### ISSUE TITLE
Hodl algoritm for nicehash

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#132]
Why CPU doesn't try to mine using HODL algoritm on nicehash servers?

**Comment by Quake4** [comment]
just enable in cpuminer-opt-[ver].config.txt hodl algo
its crashing, if your not disable windows error reporting, MM stoped, possible on fee time.

**Comment by g5-freemen** [comment]
![image](https://user-images.githubusercontent.com/36886126/43034242-ad668036-8ce1-11e8-8f78-d35c6bed070e.png)
enable, but MM doesn't try to benchmark it and doesn't see it

**Comment by Quake4** [comment]
show miner config: cpuminer-opt-[ver].config.txt from miners folder.
show miner stat:  cpuminer-opt-[ver].txt from stats folder.

**Comment by Quake4** [comment]
dont change ps1 files. change config files.
