### ISSUE TITLE
Pause button and pool payout threshold display?

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#134]
Press **P**ause to close running miner and wait for pressing **P** or **R**esume button again. This would be useful.
Is this time to type Mindminer hotkeys in 2 rows? 

What about display pools threshold in running Mindminer window?

**Comment by Quake4** [comment]
why one isn't  normal?
![image](https://user-images.githubusercontent.com/29517243/43065929-efd9d98c-8e6b-11e8-8965-a3233dd3f493.png)

**Comment by Quake4** [comment]
what is it pools threshold? min payout?

**Comment by Quake4** [comment]
why need is paused state? Alt+X & after double click on desktop (by shortcut)

**Comment by jestercore** [comment]
One row is ok, but if you gonna add more hotkeys... Maybe there wouldnt be enough space.

Yes, min payout i mean, sorry.

Pause is useful too, this is quicker than restarting. And, maybe it's better to run cycles to gather pool info, but don't run miners.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/43067876-6cca93b4-8e71-11e8-8ce2-f17a26d3559d.png)
window is wrap text.

On On/Off Pools min payout is showed.

On pause isnt pool requests.
