### ISSUE TITLE
Add ethminer. Is needed?

### ISSUE THREAD

**Issue by Quake4** [Quake4/MindMiner#139]
https://github.com/ethereum-mining/ethminer

**Comment by jjziets** [comment]
Good Idea. It has no dev fee. So not stopping. ALso the performance is as good as Clymore with CUDA and not boosted reported hashrate like PhoenixMiner.

**Comment by platinum4** [comment]
Need do

**Comment by AcharyaOne** [comment]
I think so

**Comment by nemosminer** [comment]
done

**Comment by nemosminer** [comment]
https://github.com/ethereum-mining/ethminer/releases

 v0.16.0rc1 is the Fastest Etherem Miner Available and has 0%fee

**Comment by Quake4** [comment]
Да нифига он не быстрейший.

**Comment by nemosminer** [comment]
Да нифига он не самый быстрый. нормально, если вы говорите, скажите .. мое тестирование показывает, что etherminer быстрее 1070-1080ti
Da nifiga on ne samyy bystryy. normal'no, yesli vy govorite, skazhite .. moye testirovaniye pokazyvayet, chto etherminer bystreye 1070-1080ti
