### ISSUE TITLE
these pools worth adding?

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#142]
https://www.starpool.biz/ and http://www.phi-phi-pool.com/

**Comment by Quake4** [comment]
Star: only 300 miners on rwo algo, other asic users.
Phi: can add, but small only 700 users and no support links.

**Comment by jestercore** [comment]
I don't think so. We don't need these pools at this moment.

**Comment by Quake4** [comment]
Prohashing.com have only two gpu algo - no.
starpool - only asics
phi - too small
