### ISSUE TITLE
Pool Request stalled because of no information

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#143]
On start up there is a never ending pool request because http://blockmasters.co/api/currencies isn't giving any information back. Is there a way to work around it?

**Comment by AcharyaOne** [comment]
Now I'm not sure what is the problem, I disabled the pool but it still takes a long time on pool request

**Comment by Quake4** [comment]
Polls info please. Press V to Full.

**Comment by AcharyaOne** [comment]
While is on pool request I can't press V, it eventually works but it takes like 5-10 minutes

**Comment by AcharyaOne** [comment]
Btw it seems you paid attention to the details on this software, so congratz!

**Comment by Quake4** [comment]
Stop mm. Close miners. Change in blockmasters.config.txt parameter enabled to false. Run mm.

**Comment by AcharyaOne** [comment]
Thanks, I read that blockmasters discord this: @everyone We are currently not supporting the Currencies API. It may become available again in the future but for now we will not be enabling it.

Is it possible to work only with default api instead? http://blockmasters.co/api/

**Comment by Quake4** [comment]
I change to only one request. No extended data.

**Comment by AcharyaOne** [comment]
I didn't understand what you mean

**Comment by Quake4** [comment]
I change blockmasters support to only one api support `state`

**Comment by AcharyaOne** [comment]
I'm not sure you noticed but http://blockmasters.co/api/currencies is working again, is it better to put back previous conifiguration for this?

**Comment by Quake4** [comment]
The announce channel in discord isn't message about enable api. Only disable message.
https://discordapp.com/channels/377678675895779349/456328618621009921

**Comment by AcharyaOne** [comment]
![image](https://user-images.githubusercontent.com/31579891/43905342-d01cf5e0-9be8-11e8-910c-536747d14105.png)
Maybe it will stay up for good

**Comment by Quake4** [comment]
May be. I waiting an announcement.
