### ISSUE TITLE
Ccminer Balloon 102 arguments issue

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#144]
It seems the arguments passed on this miner only affect first gpu:
![image](https://user-images.githubusercontent.com/31579891/43677156-4db97f2a-97f5-11e8-82e7-f58badfa6ca1.png)

**Comment by Quake4** [comment]
Read first and second line, please

**Comment by AcharyaOne** [comment]
Read 4th, 5th, 6th and 7th lines please.

Arguments = " -b $($Variables.NVIDIAMinerAPITCPPort) -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_) --cuda_devices 0,1,2,3,4,5,6,7,8,9,10,11 --cuda_threads 448,448,448,448,448,448,448,448,448,448,448,448 --cuda_blocks 48,48,48,48,48,48,48,48,48,48,48,48 --cuda_sync 0 -t 0"

these are the arguments passed on nemosminer, there are a bunch of values because the miner is implemented in a weird way where you must specify every value for each gpu

**Comment by AcharyaOne** [comment]
Of course I know every gpu is being used, the issue is the cuda threads argument is only being applied to first gpu...

**Comment by AcharyaOne** [comment]
Also I don't understand how to force MindMiner to benchmark again, I tried to delete stats but it doesn't ask to benchmark again.

**Comment by Quake4** [comment]
thanks. fixed cuda_threads arg. clear cuballoon config.
rereadstat: stop MM. remove stat. start MM.

**Comment by AcharyaOne** [comment]
Thanks but for some reason after deleting stats file from balloon it doesn't ask to benchmark again.

**Comment by Quake4** [comment]
check minimum miners ... on pool & config (default is 25)

**Comment by AcharyaOne** [comment]
Thanks! It wasn't easy to spot that
