### ISSUE TITLE
CryptoDredge v0.8.2

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#145]
https://github.com/technobyl/CryptoDredge/releases

Release 0.8.2 - (August 6, 2018)
Fix Phi2 bug related to smart contracts
Improve Tribus

Release 0.8.1 - (August 3, 2018)
Improve Allium, Lyra2z, and Phi2 for low-end and middle-end graphics cards
Fix P2Pool bug related to many rejected shares
Fix TCP and WebSocket connections used for API
Add power consumption monitoring

**Comment by platinum4** [comment]
NEED DO

NEED

DO

**Comment by platinum4** [comment]
Hi
right now

**Comment by mo35** [comment]
seems like api with 0.8.2 works wonky , looks like api often tries to bind to default port , not to one passed via commandline

https://bitcointalk.org/index.php?topic=4807821.20

can only bench manually , without api working correctly

**Comment by Quake4** [comment]
cmd line: -b 127.0.0.1:4068
connect: Port = 4068

**Comment by Quake4** [comment]
all fine. no errors

**Comment by Quake4** [comment]
> looks like api often tries to bind to default port

runned other miner with same port ...

**Comment by mo35** [comment]
https://github.com/Quake4/MindMiner/issues/146

same issue still persists , all Dredge 0.8.2 bechmarks fails , same errors as above in screenshot
