### ISSUE TITLE
CryptoDredge 0.8.2 API Get-Speed doesn't work after a few minutes, fails the miner

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#146]
NEED DO

https://i.imgur.com/9P1AQV5.png

**Comment by platinum4** [comment]
is fixed

**Comment by platinum4** [comment]
need use MIND

MindMiner fix, lose money lose fee lose Oleg

**Comment by Quake4** [comment]
need write to dev of dredge... i dont think is problem in MM

**Comment by platinum4** [comment]
is fix

**Comment by Quake4** [comment]
v0.8.3 released

* Fix TCP and WebSocket connections used for API
* Fix Lyra2z performance on 1070 Ti and P104-100 graphics cards

**Comment by platinum4** [comment]
NEED DO MINDMINER 2.87 Need

DO

**Comment by Quake4** [comment]
#148 duplicate
