### ISSUE TITLE
Zerg Wallet Balance URL

### ISSUE THREAD

**Issue by bonifacio123** [Quake4/MindMiner#147]
I'm seeing long delays with Pool Request(s) - I think the issue is with Zerg Pool wallet which according to the website should be:

http://api.zergpool.com:8080/api/wallet?address=WALLET_ADDRESS

Thank you

**Comment by bonifacio123** [comment]
Sorry - I'm confused - you have it set correctly

**Comment by Quake4** [comment]
Is how many copies of mm you run on your network?

**Comment by bonifacio123** [comment]
3

**Comment by bonifacio123** [comment]
Narrowed it down to Zerg/Status - sometimes it returns results and sometimes not. I also noticed it redirects from https to http - does Power Shell handle redirects?

**Comment by Quake4** [comment]
Disable `showbalance` on two.

**Comment by Quake4** [comment]
Yes, handle it.

**Comment by bonifacio123** [comment]
will do, thank you
