### ISSUE TITLE
CryptoDredge v0.8.3 (fixes API issues)

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#148]
https://github.com/technobyl/CryptoDredge/releases

Fix TCP and WebSocket connections used for API
Fix Lyra2z performance on 1070 Ti and P104-100 graphics cards

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/issues/146

NEED DO

24 HOURS LATE

**Comment by Quake4** [comment]
Too much miners updated in one week.

**Comment by platinum4** [comment]
yes!!!!
2.87!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Quake4** [comment]
;)
