### ISSUE TITLE
Доходность

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#15]
Я сравниваю с немосом. 
На немосе использую zergpoolplus . хотя фиг с цифрами, там выбор профитного алгоритма более правильно и отличается от тех что выбираются у тебя, как мне показалось. хотя я могу и ошибаться

**Comment by Quake4** [comment]
Вот как раз хотелось бы конкретного сравнения, в том что показывает, и что получается на балансе спустя сутки. Но для этого надо запустить на разные кошельки два майнера на одинковом железе. Я планировал это сделать, но пока нет возможности купить видюхи по нормальным ценам.

**Comment by Quake4** [comment]
Не знаю как сейчас в немосе, надо попробовать опять. Раньше цифры предпологаемого дохода вообще не соответсвовали реальному выходу.

**Comment by danik-guitar** [comment]
я сейчас заскринил график с зергпула по которому примерно видно доход за сутки 
теперь переключился на твой майнер и завтра вечером сравню
![qip shot - screen 12 03 18 18-57-17](https://user-images.githubusercontent.com/30734827/37295855-57fb26ec-262a-11e8-9d50-11f8b64172f9.png)

**Comment by Quake4** [comment]
Спасибо.

**Comment by danik-guitar** [comment]
предварительно могу сказать, что твой майнер практически 99 % времени майнит x16r алгоритм, немос майнер много майнил c11,x17,phi и другие и переключался довольно часто.

**Comment by Quake4** [comment]
да, конечно, x16r самый стабильный и доходный по моему мнению, а при условии что обмен занимает от 4 до в среднем 10 часов, то бегать туда сюда вообще смысла нет. Плюс переключение то же не бесплатное.

**Comment by Quake4** [comment]
осталось 4 часа, я правильно понимаю?

**Comment by danik-guitar** [comment]
Да после 19 часов пройдут сутки . Тогда графики наложу друг на друга и посмотрю разницу.

**Comment by Quake4** [comment]
Наверное, все таки лучше цифры сравнить, так как на графиках шкала Y разная будет.

**Comment by Quake4** [comment]
Из графика я вижу, за сутки немо сделал:
Balance: 30 K => 178 K
Unpaid: 100 K => 237 K
Вторые цифры из верхней таблицы ну и на графике они в принципе совпадают.

**Comment by Quake4** [comment]
MindMiner за ~20 часов:
Balance: 178 K => 334 K = 156 K
Unpaid: 237 K => 411 K = 174 K

**Comment by Quake4** [comment]
Собственно есть еще 4 часа, что все еще улучшить.

**Comment by Quake4** [comment]
Вот именно поэтому я и сел MM писать. Мне не понравился алгоритм работы. И я решил все переписать, вместо исправления чужого.
Тем более немо забивал память компа утечками уже за сутки.

**Comment by danik-guitar** [comment]
да и русскоговорящие люди почему то как то в сторонке ничего не пишут не придумывают. или затаились и в тихаря)

**Comment by Quake4** [comment]
Судя по 1% fee - только тесты проходят и сваливают,
Людей смущает, что другие показывает предполагаемого профита на 200 K, а MM только  150K. Но мои 150 это так сказать планируемый "гарантированный" доход.
А то что с тех показанных 200 по факту у них выходит 120, ну я не знаю меня такой расклад сразу не устроил.

**Comment by Quake4** [comment]
> да и русскоговорящие люди почему то как то в сторонке ничего не пишут не придумывают. или затаились и в тихаря)
Где то на форуме прочел, что мы всего лишь 1% от всех майнеров. Вот и не видно.

**Comment by Quake4** [comment]
Правильнее было бы одну ферму пустить на один кошелек под немо, а вторую на другой под Mind. Это бы более точно отразило разницу. Между сутками сравнивать не совсем верно, ибо условия разные.

**Comment by Quake4** [comment]
Сколько предполагаемую доходность пишет MM? Можно пару первых строк?

**Comment by danik-guitar** [comment]
![image](https://user-images.githubusercontent.com/30734827/37343018-5ba900f4-26d7-11e8-94ad-2d2e5e887f1c.png)

**Comment by danik-guitar** [comment]
я могу запустить на разных компах, но карты отличаются немного.
в одном компе 2 штуки 1080ti и в другом 1 штука 1080ti и 2 штуки 1080

**Comment by danik-guitar** [comment]
вот на втором 
![image](https://user-images.githubusercontent.com/30734827/37343124-a32b3d52-26d7-11e8-82f7-e66328a9b64e.png)

**Comment by Quake4** [comment]
Да, так сравнивать не получится.

**Comment by danik-guitar** [comment]
![image](https://user-images.githubusercontent.com/30734827/37353430-5fad9d9a-26f0-11e8-9c75-ea44bfa42e85.png)

**Comment by Quake4** [comment]
А вывод то какой?

**Comment by danik-guitar** [comment]
с небольшим отрывом побеждает немос по моему.

**Comment by Quake4** [comment]
Не понял, как так получилось, если все с точность да наоборот.
Баланс:
178-28=150 немос
359-178=181 майнд
Анпэйд:
237-100=137 немос
422-237=185 майнд

**Comment by danik-guitar** [comment]
по графику выходит 1,8 примерно и там и там, но у немоса чуть выше) это я по графику определял) померил отношения начала и конца на обоих графиках

**Comment by Quake4** [comment]
Может скрин завтра в 19 так же для сравнения?

**Comment by danik-guitar** [comment]
завтра я несмогу в это время. есть идея более точной оценки .
я дожидаюсь выплаты и начинаем отсчёт от выплаты до выплаты на обоих майнерах. тогда будет более точно . будут точные цыфры и даты со временем выплат

**Comment by Quake4** [comment]
Точная оценка возможно только в случае двух разных конельков и двух одинаковых ферм.

**Comment by danik-guitar** [comment]
может просто добавить статитику как у немоса, но только чтобы она не обнулялась при перезапусках и более адекватно считалась 
![image](https://user-images.githubusercontent.com/30734827/37464423-52634cdc-2869-11e8-9029-1507aa2f28fa.png)

**Comment by Quake4** [comment]
Ок, подумаю.

**Comment by nemosminer** [comment]
С наилучшими пожеланиями
Nemo

**Comment by Quake4** [comment]
> С наилучшими пожеланиями

Спасибо.

**Comment by danik-guitar** [comment]
ещё 2 раза сравнил доходы, примерно одинакого вышло, у тебя чуточку больше. =)

**Comment by Quake4** [comment]
А если в процентах, то на сколько?

**Comment by danik-guitar** [comment]
не знаю. примерно вышло так: немос намайнил до такой же суммы на 2-3 часа больше

**Comment by Quake4** [comment]
Ок
