### ISSUE TITLE
Excavator 1.4.4a for 1080ti

### ISSUE THREAD

**Issue by RetroShag** [Quake4/MindMiner#151]
Is it possible to add a config file for excavator 1.4.4a?  I don't have a problem manually downloading it or copying the config file into miner folder for it to automatically download.
 It is nearly 20% faster on 1080 ti compared to Klaust 8.22 and 10% faster than cryptodredge 0.83 without a fee.

**Comment by Quake4** [comment]
Please post screen with speed and oc.

**Comment by RetroShag** [comment]
![excavator neoscrypt](https://user-images.githubusercontent.com/39284708/44002773-3db17cf0-9e16-11e8-8c24-c222ecf04fec.PNG)

80% TDP, +75 core/+500 memory

**Comment by AcharyaOne** [comment]
Seems interesting

**Comment by RetroShag** [comment]
![image](https://user-images.githubusercontent.com/39284708/44059398-3ccbdaba-9f1f-11e8-953d-f13b3ac7c3f0.png)

**Comment by Quake4** [comment]
please, show config from excavator

**Comment by RetroShag** [comment]
It's from NPlusMiner, but here is the command line arguments.

![image](https://user-images.githubusercontent.com/39284708/44163081-4f3e0700-a090-11e8-8e2c-604c6d198919.png)

**Comment by Quake4** [comment]
configuration file for excavator for neoscrypt for 1.79Mhs

**Comment by RetroShag** [comment]
[
    {
        "time":  0,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "algorithm.add",
                             "params":  [
                                            "neoscrypt",
                                            "185.177.113.20:4233",
                                            "YWxdUn9TLfXGMjL3frBX5etQokBfg2ZQL9:ID=RG,c=YTN"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "0"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "1"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "2"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "3"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "4"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "5"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "6"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "7"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "8"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "9"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "10"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "11"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "12"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "13"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "14"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "15"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "16"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "17"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "18"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "19"
                                        ]
                         }
                     ]
    },
    {
        "time":  10,
        "loop":  10,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "algorithm.print.speeds",
                             "params":  [
                                            "0"
                                        ]
                         }
                     ]
    }
]

**Comment by Quake4** [comment]
thanks

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/44298976-f2dc2100-a2f5-11e8-8527-fef43ac453e9.png)
5 x 1080Ti = 1,82 Mh
