### ISSUE TITLE
BTC/USD info

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#153]
Maybe it possible to add info about BTC/USD course to Balance string?

**Comment by Quake4** [comment]
- [ ] show rates info
- [ ] add fast key
- [ ] config variable to en/dis/able

**Comment by g5-freemen** [comment]
Just show rates info

**Comment by g5-freemen** [comment]
It works, but maybe better to make it in the same string as balance
Maybe something like that
![image](https://user-images.githubusercontent.com/36886126/44076653-a51f2920-9fa9-11e8-986f-59f0d54c0252.png)

**Comment by Quake4** [comment]
no, it is not clear what belongs to what

**Comment by g5-freemen** [comment]
Ok, but maybe better make less free space between strings "Pool", "Coin", "Information"?
![image](https://user-images.githubusercontent.com/36886126/44137568-8efe8034-a079-11e8-8472-71480561ddad.png)

**Comment by Quake4** [comment]
yes. try master

**Comment by g5-freemen** [comment]
Only tomorrow I can test. Now gonna work
