### ISSUE TITLE
New location for Ltc wallet

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#154]
Sorry for opening an issue but just asking why the location of Ltc wallet config changed and if it is mandatory we change the config?

**Comment by Quake4** [comment]
No.location of the ltc wallet is same. you use two wallets. before ltc wallet was substituted by force. now it is necessary to explicitly specify which to use. perhaps the same pool you want btc, ltc on the other. to do what is written.

**Comment by Quake4** [comment]
I must fix warning on only two wallet is ltc and nicehash. It case no warning is needed.

**Comment by Quake4** [comment]
fixed. remove btc wallet if not used.
