### ISSUE TITLE
version 2.100 = version 2.1 is not Y2K compliant

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#157]
Hi

need v3 with power consumption thru nvsmi

professional programm from 2000 have 18 years to prepare for make power consumption read on mindminer v3.000-platinum4-build-ae549ec

**Comment by Quake4** [comment]
in version each value is int as maximum 2 147 483 648
```
public Version(
	int major,
	int minor
)
```
https://msdn.microsoft.com/ru-ru/library/03sheck6(v=vs.110).aspx

yes, i add this feature in future
