### ISSUE TITLE
Normal / Fast Switching details

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#159]
Could you please explain better the differences between normal and fast switching and advantages of using each one.

**Comment by Quake4** [comment]
Normal mode is use averaging profit by "AverageProfit" setting in pool config. Fast switching do not use averaging profit calculation.

**Comment by AcharyaOne** [comment]
In your experience can you benefit from fast switching?

**Comment by AcharyaOne** [comment]
Any insight on this? thanks in advance

**Comment by Quake4** [comment]
I test it on blaze 2 rigs side by side three days. one day fast is win, two other normal is win.
