### ISSUE TITLE
adding blazepool

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#16]
Is there option to add blazepool to your miner program?

**Comment by kingyem** [comment]
sorry to ask in a closed issue, but is there an option?

**Comment by Quake4** [comment]
Yes, I can add, but I isn't recommended this pool.
Add this pool to MindMiner?

**Comment by podlbo** [comment]
Add this pool to MindMiner? yes

**Comment by kingyem** [comment]
Would appreciate it, but may i know why blazepool is not recommended?

**Comment by Quake4** [comment]
I add Blaze pool.
Enable its in config Pools\BlazePool.config.txt

> why blazepool is not recommended?

Too small. Overall 1K miners. No info about support.
