### ISSUE TITLE
CryptoDredge v0.8.4-beta

### ISSUE THREAD

**Issue by KL0nLutiy** [Quake4/MindMiner#160]
Hi, @Quake4, could you please add  CryptoDredge v0.8.4-beta it is faster on 1080/1080 Ti for Lyra2Z and Neoscrypt.
https://github.com/CryptoDredge/beta/releases/tag/v0.8.4-beta

**Comment by Quake4** [comment]
i waiting release in this location: https://github.com/technobyl/CryptoDredge/releases

**Comment by jjziets** [comment]
something is fishy. why is it not listed on there website or bitcointalk page.

**Comment by jjziets** [comment]
Ok i could not resist. It is faster on lyra2z and Neo. But I need to add a -d 0,1,2,3,4,5 to get it to work on all gpu's

**Comment by Quake4** [comment]
Ok. Thanks all. I add it, but disabled by default.

**Comment by Quake4** [comment]
check link https://github.com/CryptoDredge/beta/releases/download/v0.8.4-beta/CryptoDredge_0.8.4-beta_cuda_9.2_windows.zip

**Comment by AcharyaOne** [comment]
Thanks, that was it!
I changed the ps1 file to enabled: true but forgot there was txt file also

**Comment by Quake4** [comment]
Ps1 isnt needed to edit. Only configs.
