### ISSUE TITLE
Pause button

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#162]
Can you add pause button to disable mining for some time?

**Comment by Quake4** [comment]
why do this?
Alt+X ..... double click on desktop link

**Comment by Quake4** [comment]
add to taskbar

**Comment by g5-freemen** [comment]
No, thanks.
I just want to say that some another miners (Nemosminer) have pause or stop button and it's more convenient than close and open again miner (shell)

**Comment by Quake4** [comment]
I do not understand why you need to suspend the miner.

**Comment by g5-freemen** [comment]
Because I use miner on my home pc and when I open browser and want to read news or view something on YouTube it works too slow.

**Comment by Quake4** [comment]
I don't see the need.
