### ISSUE TITLE
CryptoDredge v0.9.0 CNany isnt work on NiceHash

### ISSUE THREAD

**Issue by KL0nLutiy** [Quake4/MindMiner#166]
Hi, @Quake4 , please add CryptoDredge v0.9.0 https://github.com/technobyl/CryptoDredge/releases/tag/v0.9.0

**Comment by Quake4** [comment]
Please, test it

[ccminer-dredge-090.zip](https://github.com/Quake4/MindMiner/files/2343338/ccminer-dredge-090.zip)

**Comment by AcharyaOne** [comment]
![image](https://user-images.githubusercontent.com/31579891/44957600-91a67700-aecb-11e8-9e82-9dd8adb8a11c.png)

**Comment by AcharyaOne** [comment]
![image](https://user-images.githubusercontent.com/31579891/44957614-b1d63600-aecb-11e8-90a3-42a85be68672.png)

**Comment by Quake4** [comment]
Thanks.

**Comment by Quake4** [comment]
Can you test cnv7 on mph?

**Comment by Quake4** [comment]
Please, test on CD 9,1.
