### ISSUE TITLE
Переключиться на другой, если нет коннекта

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#17]
![image](https://user-images.githubusercontent.com/30734827/37427750-58e9ac10-27db-11e8-9d37-46acbc2fea43.png)
этот алгоритм не коннектится и можно как то таких моментов избежать, типо попробовал 10 раз и переключиться на следующий алгоритм

**Comment by danik-guitar** [comment]
а всё переключился на другой. значит уже так сделано, у немоса не переключается так и строчит по пол часа ретри афтер и так далее

**Comment by danik-guitar** [comment]
странная фигня на каждом алгоритме такое пишет, на втором компе работает

**Comment by danik-guitar** [comment]
заработало.

**Comment by Quake4** [comment]
stratum сервера по всей видимости перезапускали.
Должно переключаться, но по достижении трех минут, возможно не везде работает.

**Comment by Quake4** [comment]
> у немоса не переключается так и строчит по пол часа ретри афтер и так далее

Ага, это киллер фича MindMiner ;)
