### ISSUE TITLE
Lolminer "-device=" parameter

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#172]
Lolminer running 2 times and both windows using amd+nvidia, rig crashing. On nvidia only or AMD only rig everything is ok.
So, "-device=" parameter not working on lolMiner
![desktop bug](https://user-images.githubusercontent.com/33821148/45262033-822dad80-b438-11e8-81db-6884bfb80175.png)
![platform bug](https://user-images.githubusercontent.com/33821148/45262034-82c64400-b438-11e8-91b0-add3b81a6ecd.png)

**Comment by jestercore** [comment]
> “DEVICES” : “AMD” or “DEVICES” : “NVIDIA” : Mine will all GPUs from one of the vendors (**only
> works with official vendor drivers, with 3rd party and opensource drivers this may not work**)

That's because i'm using AMD/ATI Pixel Clock Patcher with 18.2.1 on AMD? I don't think so.

**Comment by Quake4** [comment]
Iam mistakes. Please, change lominer-043.ps1 -device to -devices, and try.

**Comment by jestercore** [comment]
Yes, everything is ok now, thank you.
