### ISSUE TITLE
ask pools in "No Pools" state

### ISSUE THREAD

**Issue by Quake4** [Quake4/MindMiner#176]

**Comment by petrovsky34** [comment]
не работает zergpool no pools

**Comment by petrovsky34** [comment]
Можешь добавить что бы в Zergpool другие монеты ставить на выплату кроме BTC и LTC

**Comment by Quake4** [comment]
Все сделано в config.md подробности
Параметр Wallet в zergpool.config.txt
NoPools - api не отвечает (http://api.zergpool.com:8080/api/status)
