### ISSUE TITLE
Zergpool BTC LTC и другие добавь Монеты В Выплаты пожалуйста

### ISSUE THREAD

**Issue by petrovsky34** [Quake4/MindMiner#181]

**Comment by petrovsky34** [comment]
ато я переделываю твой минд майнер а после обновы опять приходиться менять на другие монеты для выплаты какие мне нужны

**Comment by Quake4** [comment]
В какой монете майнится в той и выводится. Если мм майнит в ltc, то его и показывает. Не откуда там взяться другим монетам. Если другой риг майнит в дуги, то и покажет дуги.

**Comment by Quake4** [comment]
Не понимаю, что было переделано.
