### ISSUE TITLE
Сделай пожалуйста что бы 10603gb отдельно работали от 4gb 

### ISSUE THREAD

**Issue by petrovsky34** [Quake4/MindMiner#182]

**Comment by petrovsky34** [comment]
просто может быть у некоторых разные карты стоят
у меня например 11 какт на риге 1 rx5604gb. 8 1050ti  и 1060 3gb 2 штуки

**Comment by petrovsky34** [comment]
этого очень не хватает в mindminer

**Comment by Quake4** [comment]
Я в ближайшем будушем не собираюсь делить карты по параметру di. Проще сменить мм на что нить другое или продать карты.
