### ISSUE TITLE
Олег перестал работать Zergpool

### ISSUE THREAD

**Issue by petrovsky34** [Quake4/MindMiner#183]

**Comment by petrovsky34** [comment]
просто Олег убрал LTC оставил только BTC
а мне если в битке будет плата то оч долго ждать выплату
в LTC минималка была 200 руб а у битка 1000 для меня разница большая
и еще в zergpoole можно любую ставить монету для выплаты тотже равенкоин или доге

**Comment by petrovsky34** [comment]
g5-freemen у тебя в битке стоит у меня в лайткоине вот и у меня не работает!!! уже проверил

**Comment by Quake4** [comment]
Читаем документацию. Zergpool.config.txt > Wallet > LTC.
У блокмастера вчера апи не отвечало.

**Comment by Quake4** [comment]
Если пул пропал, проверяйте его апи сначла. 100% что оно не отвечает
