### ISSUE TITLE
Trex 0.64 zpool hmq1725 no hash

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#185]
Miner is working and displaying hashrate but for some reason mindminer exits trex saying it has no hash

**Comment by AcharyaOne** [comment]
![image](https://user-images.githubusercontent.com/31579891/45501822-37829d00-b77a-11e8-9367-63389dc65740.png)

**Comment by Quake4** [comment]
Does this happen on all algorithms? Can the MM window?

**Comment by AcharyaOne** [comment]
I only saw it happen with hmq1725, but didn't test them all, it is working with x16r on nicehash at the moment

**Comment by Quake4** [comment]
Reopen if its showed again.
