### ISSUE TITLE
Zergpool.config.txt > Wallet > LTC

### ISSUE THREAD

**Issue by petrovsky34** [Quake4/MindMiner#187]

**Comment by petrovsky34** [comment]
там нет ни кокого примера как это сделать

**Comment by petrovsky34** [comment]
![xcxz](https://user-images.githubusercontent.com/39003568/45551074-7295d680-b835-11e8-8583-955a86f9f3a7.PNG)

**Comment by petrovsky34** [comment]
пример напиши

**Comment by petrovsky34** [comment]
Спасибо большое

**Comment by Quake4** [comment]
Specific for ZergPool, ZPool & BlockMasters
Wallet [string] - coin short name (example "LTC") to use on the pool (as c=XXX in password). Wallet address must be specified in main settings file.

**Comment by petrovsky34** [comment]
там не понятно был бы пример норм было бы!
как на других

**Comment by Quake4** [comment]
Добавлю
