### ISSUE TITLE
выбор монеты для алгоритма у зерга

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#19]
{
    "AverageProfit":  "1 hour 30 min",
    "Enabled":  true,
    "SpecifiedCoins": { "C11": "SPD", "NeoScrypt": [ "SPK", "GBX"], "Phi": "LUX" }
}

не работает выбор люкса, майнит фолм
![qip shot - screen 18 03 18 12-44-14](https://user-images.githubusercontent.com/30734827/37564625-c3602f5c-2aaa-11e8-954f-8ff17393d185.png)

**Comment by danik-guitar** [comment]
странно, но через некоторое время переключился всё таки на люкс

**Comment by danik-guitar** [comment]
хотя если верить статистике пула 
![image](https://user-images.githubusercontent.com/30734827/37564715-a32ff756-2aac-11e8-8fdb-3340a09b664b.png)

**Comment by Quake4** [comment]
Все правильно, если звездочки нет, то майним как обычно алгоритм PHI и показываем, что на текущем круге более профитное. А вот если статистика говорит, что LUX более прибыльный в течении "AverageProfit" и/или сильно больше дельта между ним и просто алгоритмом, то переключаемся на него с указанием монеты.

**Comment by Quake4** [comment]
Может сделать признак, что выбирать только из SpecifiedCoins?

**Comment by Quake4** [comment]
Сейчас фактически выбор делается либо указанная монета, либо алгоритм.

**Comment by Quake4** [comment]
Да, надо сделать. Завтра сделаю.
