### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#190]
Может можно сделать сохранение настроек в файл config.txt например, в частности Fast/Normal Switching, Exchange Rate show on/off ?

**Comment by Quake4** [comment]
Не понял вопроса. Они там есть.

**Comment by g5-freemen** [comment]
После перезапуска при обновлении или просто при закрытии и старте MM стоит по умолчанию Normal Switching, Exchange Rate show off. Почему нельзя сделать, чтобы если я изменил что-то при работе - это изменение сохранилось.

**Comment by Quake4** [comment]
Я не правлю конфиг, за исключением начальной инициализации. Во избежании, проблем.
Эти настройки меняются на текущую работу приложения, а значения по умолчанию для этих параметров впишите в конфиг какие надо, например Fast и показывать курс обмена.

**Comment by Quake4** [comment]
Вы шутите? Причем здесь описание процесса конфигурирования?
Надо править config.txt

**Comment by g5-freemen** [comment]
ok, понял. Извиняюсь за беспокойство.
