### ISSUE TITLE
Trex 0.6.9

### ISSUE THREAD

**Issue by petrovsky34** [Quake4/MindMiner#194]

**Comment by platinum4** [comment]
I think he means t-rex 0.6.6 https://mega.nz/#!TEsUSIiC!4zpoxI58Qc90bcKsFHM0RhAvA7ERsNBB5HlNYsUa9xI

**Comment by platinum4** [comment]
0.6.9 Windows (x64)
CUDA 9.1/9.2:
https://mega.nz/#!zQ1TxBTT!8XtJ8KTMsiNDNkYYJog6sm04cBSMu7aJSWzBOX99xJs

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/45928853-aae29680-bf52-11e8-8066-0b07472bb987.png)
its not release

**Comment by Quake4** [comment]
latest release is 0.6.6

**Comment by platinum4** [comment]
https://i.imgur.com/zLinURw.png

**Comment by platinum4** [comment]
https://i.imgur.com/FjZoEqd.png
