### ISSUE TITLE
[Add Miner] cpuminer-opt-3810-bf has Argon2DYN/yespower/yescrypt

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#196]
Hi,

Include this optional cpu miner https://github.com/bellflower2015/cpuminer-opt/releases/download/v3.8.10-bf/cpuminer-opt-v3.8.10-bf-win64.zip

**Comment by platinum4** [comment]
https://i.imgur.com/cQUoqbN.png

**Comment by g5-freemen** [comment]
+1
[cpuminer-opt-bf.zip](https://github.com/Quake4/MindMiner/files/2451755/cpuminer-opt-bf.zip)
