### ISSUE TITLE
AMD rig error

### ISSUE THREAD

**Issue by Imaminer** [Quake4/MindMiner#20]
Getting this while mining. Stops for a while and then goes again.

Get-Speed error: Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4028"
Get-Speed error: Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4028"
Get-Speed error: Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4028"

**Comment by Imaminer** [comment]
This seems to of stopped. So closing for now

**Comment by Quake4** [comment]
Yes. If miner fail show 2-3 error and go to next miner.

So how did you get started? Why didn't work MindMiner?

**Comment by Imaminer** [comment]
I just tried the latest version and except for above error it seems to be working.

**Comment by Quake4** [comment]
Ok. Thanks.
