### ISSUE TITLE
[Miner update] T-Rex 0.6.10

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#200]
From Trex discord:

The change log below is based on 0.6.6 as previous version.

Speed improvements: x16r/s, x17, c11, bitcore, bcd, sonoa - 1-2%
Add functionality for setting failover pools in cmd line by specifying -o, -u and -p arguments multiple times.
New cmd line arguments:
    --gpu-report-interval: controls how often GPU report stats are displayed (by default every 5th share).
    --no-color: disable coloured output
    --time-limit: maximum time [s] to mine before exiting the program.
    --quiet: disable GPU stats output
Add ability to change averaging hashrate window and GPU report interval via API or web browser on the fly (without stopping the miner) - see the help file.

Bug fixes:
Hung/freeze issues
Invalid shares on x16r
Long log path issue on Linux
"extranonce subscribe timed out" on suprnova pools

Cosmetic changes:
Showing configured pools upon start up
Displaying colour representation of hashorders for x16r/s
Miner uptime is displayed as part of GPU stats report

Windows (x64)
CUDA 9.1/9.2:
https://mega.nz/#!XUUSgCDI!jThvXxy5Sbec6RvG_8Jq96yZgxxziXDcCWQtZMHxGDY

**Comment by platinum4** [comment]
NEED DO professional programme from 2000

**Comment by mo35** [comment]
thx
