### ISSUE TITLE
NLPool not showing on main screen

### ISSUE THREAD

**Issue by bonifacio123** [Quake4/MindMiner#202]
I have NLPool enabled along with Zerg, I see it pulls stats for NLPool pool in NLPool.txt but MindMiner doesn't seem to include that pool on the main screen. This section:

Miner              Algorithm   Speed, H/s    BTC/Day USD/Day     BTC/GH/Day Pool               ExtraArgs
-----              ---------   ----------    ------- -------     ---------- ----               ---------
+ccminer-trex-065  X17            40.39 M 0.00022579    1.47     0.00559018 ZergPool-XVG
ccminer-ze-x32-121 X17            40.28 M 0.00022519    1.46     0.00559018 ZergPool-XVG

**Comment by Quake4** [comment]
Nlpool has only 9 algo. And profit is lower than zergpool. Disable zerg and see nlpool. MM show for each algo only profitable pool.
