### ISSUE TITLE
t-rex exits with no apparent error

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#207]
i have this miner fail in mindminer with no error in the t-rex windows
 why does mindminer report t-rex as failed miner if there is no error?

**Comment by Quake4** [comment]
Api has no answer or error result in answer

**Comment by AcharyaOne** [comment]
Does it happen to someone else or is it just me?

**Comment by Quake4** [comment]
its happen only with trex

**Comment by Quake4** [comment]
0.7.0 is work correctly
