### ISSUE TITLE
Removing a miner 

### ISSUE THREAD

**Issue by Imaminer** [Quake4/MindMiner#21]
2 of my AMD rigs are crashing with Gateless Neo.
How do I remove Neo from Gateless and NOT have it come back when program does upgrade?

**Comment by Imaminer** [comment]
I figured it out :)

**Comment by Quake4** [comment]
Change config "gatelessgate-0136.config.txt".
You can disable any algo in each algo setting in the "Algorithms" or disable whole miner by change Enabled in the root.
You can also change intensity to lower value.

**Comment by Quake4** [comment]
I disable neo in gg. Claymore's NeoScrypt is faster.

**Comment by Quake4** [comment]
Can you past screen with top algo from your farm?
