### ISSUE TITLE
cpuminer-argon2

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#210]
https://github.com/BeastPool/cpuminer-argon2d/releases
предлагаю добавить майнер

cpuminer-opt-3881 почему то не работает с argon2-dyn на zergpool

**Comment by platinum4** [comment]
you need to use cpuminer-3810-bf

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/issues/196

**Comment by g5-freemen** [comment]
don't know how to add this with right command line in MM

**Comment by Quake4** [comment]
что не работает в argon2-dyn? стратум или что?

**Comment by Quake4** [comment]
попробуйте удалить конфиг `cpuminer-opt-3881.config.txt`

**Comment by Quake4** [comment]
this miner is slower
![image](https://user-images.githubusercontent.com/29517243/46805278-58d0ac00-cd6d-11e8-9fde-82d56f9755e8.png)
then original cpuminer-opt
![image](https://user-images.githubusercontent.com/29517243/46805422-ad742700-cd6d-11e8-904a-04687cecc181.png)
