### ISSUE TITLE
[minerupdate] T-Rex 0.7.0

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#215]
from their discord

Speed improvements: there's ~1% improvement in x16 family of algorithms on some configurations.
Add support for Volta (Titan V) and Turing (20xx) cards - not optimised yet. Download CUDA 10 version to run on 20xx cards.
New arguments:
    --temperature-limit: When a GPU reaches the temperature limit (in Celsius) the miner stops using it and keeps mining with the rest of GPUs
    --exit-on-fail-shares: Forces miner to immediately exit on N successively rejected shares (default: 10)
Command line arguments now take precedence over config files. If an argument is set in both places, the value from cmd line overrides the config one.
New HTTP API handler that allows you to control the miner via a web browser on the fly. By default is accessible at http://localhost:4067/trex. Functionality is limited but will be extended in future releases if there's demand. We're looking forward to getting your feedback.

Bug fixes:
Stability fixes, especially on x16r/s and bitcore
CUDA version reported by the miner is now the version that the miner has been built against rather than the one installed on user's machine
Redirection of console output to stdout on Windows with no buffering in place.

Cosmetic changes:
Add miner efficiency (Hashes per Watt) to console output and API
Print "Submitting found block!" message when a block is found and return this info in API

Windows (x64)
CUDA 9.1 (former 9.1/9.2 one):
https://mega.nz/#!GQVxQA7L!SppCdxuy8ShbHclv0oiXuAxA1mHYllo2Okx2q8-aFIs

CUDA 9.2 (experimental):
https://mega.nz/#!OYNXEAhQ!abLofQ0_GZRl-HF8XjzoBH5kj664OI9beSl2nbdbFhA

CUDA 10.0 (experimental):
https://mega.nz/#!qVVFGaLR!B9lHI4M2zLiKLGVZ7pu1Bb_cwCjyJ-73ttE6BjCr2Kw

**Comment by platinum4** [comment]
Type: nVidia

Miner              Algorithm   Speed, H/s    BTC/Day USD/Day BTC/GH/Day Pool         ExtraArgs
-----              ---------   ----------    ------- ------- ---------- ----         ---------
ccminer-ze-x32-122 X17            29.56 M 0.00020963    1.38 0.00709193 BlockMasters -i 22
ccminer-ze-x64-122 X16r           29.49 M 0.00017880    1.17 0.00606308 BlockMasters -i 22
ccminer-dredge-092 Lyra2z          7.36 M 0.00017019    1.12 0.02312893 NLPool
+ccminer-trex-070  Hmq1725   Benchmarking     90 sec  90 sec 0.00722987 ZPool-PLUS   -i 22
ccminer-trex-070   Phi       Benchmarking     90 sec  90 sec 0.00153822 BlockMasters -i 24
ccminer-trex-070   Polytimos Benchmarking     90 sec  90 sec 0.00163993 ZPool-POLY   -i 24
ccminer-trex-070   Skunk     Benchmarking     90 sec  90 sec 0.00071965 NiceHash-Usa -i 25
ccminer-trex-070   X16r      Benchmarking    120 sec 120 sec 0.00606308 BlockMasters -i 22
ccminer-trex-070   X16s      Benchmarking    120 sec 120 sec 0.00501896 BlockMasters -i 22
ccminer-trex-070   X17       Benchmarking    120 sec 120 sec 0.00709193 BlockMasters -i 22

**Comment by Quake4** [comment]
in next version
