### ISSUE TITLE
Request : Excavator

### ISSUE THREAD

**Issue by kingyem** [Quake4/MindMiner#22]
Hello,

Can i request to add excavator into the miner?I understand that its it illegal to distribute but is legal if the user downloads it him/herself, can you provide that option?

Thank you.

**Comment by Quake4** [comment]
Yes. I add it.

**Comment by Quake4** [comment]
> From version 1.5.0a further excavator supports only NiceHash stratum servers. Stratum servers are available at: nhmp.LOCATION.nicehash.com (LOCATION: eu, usa, hk, jp, in, br).

Is it needed?

**Comment by kingyem** [comment]
i just saw the update, 
though 1.5.0a doesn't support other stratums, the previous iteration (1.4.4a) was far faster than the nearest miner

saying that, i understand if the prospect to add nicehash is low for better future proofing

to answer the initial question, the 1.5.0a is not needed :)
