### ISSUE TITLE
hsr zergpool опять не пашет на пуле

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#23]
этот алгоритм нифига не пашет. и в итоге он пробует , потом запускает другой алгоритм и через несколко минут опять пробует этот нерабочий и получается многоо времени уходит на попытки приконнектиться к этому алгоритму. надо как то этот момент учесть

**Comment by danik-guitar** [comment]
надо реализовать выбор алгоритмов, чтобы можно было просто не использовать ненужные на свой выбор. у других просто список алгоритмов, нужный вписываешь или убираешь

**Comment by danik-guitar** [comment]
и зергпул пишут будут модернизировать . сервера менять на викенде. надеюсь лучше работать будет)

**Comment by Quake4** [comment]
1) Это учтено, первый раз дизаблим майнер на "NoHashTimeout" минут, второй раз на 2xNoHashTimeout и далее 3xNoHashTimeout и ...
Сейчас они по всей видимости переехали. Стратумы не работали 20 минут. У меня был дополнительный пул, поэтому ММ переключился на него.

2) Ок. По пулам или общий или Пулы+Общий что бы было конкретнее?

**Comment by danik-guitar** [comment]
2.лично меня устраивает общая настройка выбора алгоритмов.

**Comment by Quake4** [comment]
создал issue отдельную.
