### ISSUE TITLE
Cryptonightv8 fails on CryptoDredge v0.9.3

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#232]
State: Failed

Type   Pool         Algorithm     Speed, H/s Run Time Run  Command
----   ----         ---------     ---------- -------- ---  -------
nVidia NiceHash-Usa Cryptonightv8    Unknown 00:00:06 Once ccminer-dredge-093\cryptodredge.exe -a cryptonightv8 -o stratum+tcp://cryptonightv8.usa.nicehash.com:3367 -u [redacted].Z97EX4 -p x -R 5 -b
 127.0.0.1:4068 --api-type ccminer-tcp --no-watchdog -N 3

**Comment by platinum4** [comment]
-a cryptonightv8 does not work

**Comment by Quake4** [comment]
use original `ccminer-dredge-093.ps1` and delete `ccminer-dredge-093.config.txt`
