### ISSUE TITLE
JCE GPU Miner (jce-cn-xxxx) takes Nvidia

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#239]
On mixed AMD+Nvidia rig jce-cn-033b starts mining on all GPU's, not only on AMD.

We need some commandline?

**Comment by jestercore** [comment]
https://github.com/jceminer/cn_gpu_miner/issues/22

**Comment by Quake4** [comment]
Now, only -g can fix it in mixed rigs. Waiting fix from author.
Add -g to main exrtaargs with ids gpu.

**Comment by Quake4** [comment]
i update jce gpu miner to 0.33b2. 
is it fix this issue?

**Comment by jestercore** [comment]
Still catching Nvidia's, that's bad @jceminer

**Comment by platinum4** [comment]
Thanks, this got my 290X back to mining something better than eth/neo

**Comment by Quake4** [comment]
@jestercore this version must fix it problem

**Comment by jestercore** [comment]
Yes, thank you so much.
