### ISSUE TITLE
adding pool hashrefinery

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#24]
im rally happy that you add blazepol on MindMiner. Im hopping you can add another pool -> http://pool.hashrefinery.com

**Comment by Quake4** [comment]
this?
![image](https://user-images.githubusercontent.com/29517243/37698801-905e15ae-2cf5-11e8-96da-cd6d277a4782.png)

**Comment by podlbo** [comment]
no this -> http://pool.hashrefinery.com/

**Comment by Quake4** [comment]
ok, soon.

**Comment by Quake4** [comment]
I did it. Version 1.30.
