### ISSUE TITLE
[Add Miner] zjazz

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#245]
For Яeal my friend is good is miner for the zjazz 

https://cryptomining-blog.com/10360-new-zjazz-1-2-amd-and-nvidia-miner-with-support-for-merit-bitcash-and-suqa/

is make Oleg turn the R to the front again so Hi

**Comment by Quake4** [comment]
https://github.com/zjazz/zjazz_cuda_miner/releases
