### ISSUE TITLE
Local thousand separator DOT is came to the speed conversion error

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#25]
I think conversion is wrong for G h/s from M h/s 
https://bitcoin.stackexchange.com/questions/42078/gigahash-vs-megahash

![slika](https://user-images.githubusercontent.com/33230718/37699189-a08564b4-2ce6-11e8-81ed-592d34d98f9c.png)

**Comment by Quake4** [comment]
please, grab total ccminer string

**Comment by podlbo** [comment]
that was total...
![slika](https://user-images.githubusercontent.com/33230718/37699744-1ab2a9b6-2ce9-11e8-9b2a-670e96f24b94.png)

**Comment by Quake4** [comment]
sorry

**Comment by Quake4** [comment]
please, send settings window from windows control panel "Language and regional standarts" tab "Fromats"

**Comment by Quake4** [comment]
win 10: Settings/Time& lang/Region & lang/Additional lang and time/Regional standarts/change/additional params

**Comment by podlbo** [comment]
i hope this looks correct?
![slika](https://user-images.githubusercontent.com/33230718/37700602-7b3c072a-2cec-11e8-94ef-618db5f7b9dd.png)

**Comment by Quake4** [comment]
yes

**Comment by Quake4** [comment]
quick fix: change thousand separator from . to Empty
i try add normal fix later.

**Comment by podlbo** [comment]
YES this works... it is impossible to leave empty -> but i did add 1 spacebar ;) This works 
![slika](https://user-images.githubusercontent.com/33230718/37701442-5aeee16a-2cef-11e8-8b2b-742e14670f49.png)

**Comment by Quake4** [comment]
Is your national currency setting really have dot in thousan separator?

**Comment by podlbo** [comment]
yes im affraid so...

**Comment by Quake4** [comment]
fix it in 1.30. update its. revert locale settings and check this.

**Comment by podlbo** [comment]
Works PERFECT

**Comment by Quake4** [comment]
thanks
