### ISSUE TITLE
[Add Feature] Mining Profitability Lower Floor

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#257]
Hi,

Can you add a feature where if rig is making a certain amount of money to stay mining on it please.

For instance below, this is 6x 1070s.

Can you add in config.txt a "MineAboveDailyProfitTarget" or something similar so we can input a value "4" and then if you see below, only x16r and Skunk would be mined.  If both fall below $4/day then rig sits idle doing nothing.

```
   Type: nVidia

Miner               Algorithm Speed, H/s    BTC/Day USD/Day BTC/GH/Day Pool         ExtraArgs
-----               --------- ----------    ------- ------- ---------- ----         ---------
%ccminer-ze-x64-122 X16r         94.92 M 0.00067174    4.23 0.00707696 BlockMasters -i 22
+ccminer-dredge-094 Skunk       223.48 M 0.00065479    4.13 0.00293000 NiceHash-Usa
ccminer-trex-072    Bitcore     155.83 M 0.00053896    3.40 0.00345857 BlazePool    -i 22
```

**Comment by Quake4** [comment]
i can add in btc lower floor. is it normal?

**Comment by platinum4** [comment]
BTC/day is fine but can easily convert to USD if already doing that

**Comment by Quake4** [comment]
What if I don't get the exchange rates?

**Comment by Quake4** [comment]
profit in btc/day be always

**Comment by platinum4** [comment]
ok do it

**Comment by AcharyaOne** [comment]
but you can get the value for btc so you could convert easily to usd or euro

**Comment by Quake4** [comment]
Yes, i can, but what do if I don't get the exchange rates?

**Comment by platinum4** [comment]
Hi,

Every loop gets exchange rates anyway; but just make BTC floor please.  Can you break down for each device type like AMD, CPU, NVIDIA; maybe as JSON array

**Comment by Quake4** [comment]
every hour. `rates loop`

**Comment by Quake4** [comment]
yes, i add in the next three days

**Comment by Quake4** [comment]
since 3.07
