### ISSUE TITLE
уменьшить количество строчек в отображении

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#26]
Было бы хорошо убрать отображение всех строк. оставить только самые профитные в каждом алгоритме, а полное отображение сделать только в фул режиме.
![qip shot - screen 21 03 18 11-06-40](https://user-images.githubusercontent.com/30734827/37699319-162c21ba-2cf8-11e8-88ca-08f8251bfeb9.png)

**Comment by Quake4** [comment]
Задизабли непрофитные майнеры

**Comment by Quake4** [comment]
И там не все показываются, а только которые 0,65 от максимального, а в минимуме только 0,8.

**Comment by Quake4** [comment]
В принципе согласен в нормале и минимале можно по одной строке на алгоритм показывать.

**Comment by Quake4** [comment]
Сделано в 1.34.
