### ISSUE TITLE
Nicehash no hash

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#261]
![image](https://user-images.githubusercontent.com/36886126/47951938-13bd2580-df79-11e8-95b5-14b7230f55e5.png)

Проблемы с nicehash серверами - x16r, skunk и другие не работают

**Comment by Quake4** [comment]
А собственно, в чем баг то?
MM отработал правильно, определил, что нет хэша и выбрал следующий по списку майнер.
Далее через `NoHashTimeout` будет сбрасывать nohash и снова пробовать.

**Comment by Quake4** [comment]
попробуйте usa или europe регион

**Comment by g5-freemen** [comment]
Европа и так выбрана

**Comment by Quake4** [comment]
Попробуйте usa. Возможно найс забанил вас.
В зависимости от времени benchmark timeout * 2.
