### ISSUE TITLE
[ request ] disable auto download of (new) miners

### ISSUE THREAD

**Issue by TobBla** [Quake4/MindMiner#267]
Hello :)
First things first: Appreciate your work very much! It´s a pleasure to use Mindminer!
No useless features, no useless gui (if you like doing your config in txt anyways), transparent on when it does what and why ;)
So thumps up for that!

Just a small request (or maybe i am silly and it is an option i am totally not seeing?):
I am not using most of the miners anyways, and if the miner is connected through mobile hotspot, it drains unneccessary data volume when downloading every new update of every ccminer out there :/
Aside from the data volume: it kind of bothers me that, even though mindminer does not launch them without the Y key, exe files are being downloaded without being asked (and most of them being useless to me).

Best, Tobi

**Comment by Quake4** [comment]
Thanks, Tobi.

For example, is witch miner you not use?

Miner will not be downloaded if all its algorithms are disabled.
See: https://github.com/Quake4/MindMiner/blob/master/Config.md#algorithms

**Comment by Quake4** [comment]
since 3.01
* ***ConfirmMiner*** [bool] (true|**false**) - need user confirm for miner without configuration file (false - auto download new miners).

**Comment by TobBla** [comment]
Much appreciated, thanks! 💯
