### ISSUE TITLE
x22i cryptodredge 9.6 all rejects on zpool

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#268]
what subject says , all rejects with wrong extranounce error

**Comment by Quake4** [comment]
Now, disable the x22i algo in miner config.

**Comment by Quake4** [comment]
![screenshot_20181107-075515](https://user-images.githubusercontent.com/29517243/48111437-802e7200-e262-11e8-9586-486c34710713.jpg)
Is your local problem with dredge?

**Comment by mo35** [comment]
hmm , re-enabled again , now its working out of the box .... guess it was temporary zpool issue , i just happened to do benchmark at that time

**Comment by Quake4** [comment]
fine
