### ISSUE TITLE
Team Red cn v8 RX560+RX580 crash

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#269]
Team Red 0.3.6 showing 0 hashrate and crashing system after closing it. Bug appears **only** on CryptonightV8 algo.

**Comment by jestercore** [comment]
@teamredminer Look

**Comment by todxx** [comment]
Thanks for the ping.  These are both known bugs that we plan to address in the next release.  We're hoping to get this release out in the next day or two, but we have a long list of bugs/requests we're trying to fit in.

**Comment by Quake4** [comment]
thanks. waitings...

**Comment by jestercore** [comment]
What about temporary disabling cn v8 in this miner?

**Comment by jestercore** [comment]
still bugged for me
