### ISSUE TITLE
Add sgminer fork

### ISSUE THREAD

**Issue by KL0nLutiy** [Quake4/MindMiner#275]
https://github.com/fancyIX/sgminer-phi2-branch
Support phi2, lyra2Z, allium, x22i, lyra2REv2, lyra2h algos

**Comment by Quake4** [comment]
ok. thanks. is when next release of sgminer-kl?

**Comment by KL0nLutiy** [comment]
Maybe on this week, I found some faster kernels.

**Comment by platinum4** [comment]
@KL0nLutiy do you have any Hawaii settings or bins to share?  Most those settings with -X 256 are awful and I was person who helped test very first sgminer5 back in 2014 on x11/x13/x15, etc.  I can't find anything that doesn't crash-- even at stock clocks.

**Comment by KL0nLutiy** [comment]
@Quake4, new version of my fork: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.7
@platinum4, please try last version from my fork.

**Comment by KL0nLutiy** [comment]
@Quake4, use -w 256 for polytimos algo

**Comment by platinum4** [comment]
@KL0nLutiy I can't get 1.0.7 to generate any BINs on a Hawaii, I'm on Adrenalin 18.11.1, same as before.  This software doesn't work for older AMD

**Comment by Quake4** [comment]
on rx580 is miner down
![image](https://user-images.githubusercontent.com/29517243/48311784-0d046300-e5b6-11e8-9d2b-1fd83f03a0b4.png)

**Comment by Quake4** [comment]
please try it
https://github.com/Quake4/MindMiner/raw/master/Miners/sgminer-fancy-5f.ps1

**Comment by Quake4** [comment]
I have to move it to the archive later.

**Comment by KL0nLutiy** [comment]
@platinum4, create an issue in my repository: https://github.com/KL0nLutiy/sgminer-kl/issues
Describe which cards do you have, your os, driver version etc.

**Comment by Quake4** [comment]
@KL0nLutiy can you show MM window?

**Comment by KL0nLutiy** [comment]
@Quake4, what the MM miner section?

**Comment by Quake4** [comment]
Скрин, который сверху постил
