### ISSUE TITLE
Optimized CCMiner (CUDA miner) fork for x16r

### ISSUE THREAD

**Issue by nemosminer** [Quake4/MindMiner#28]
https://github.com/nemosminer/Ccminernevermore/releases

Optimized CCMiner (CUDA miner) fork for x16r

Forked from https://github.com/tpruvot/ccminer
Alexis78 x16r support added by "brian112358" : https://github.com/brian112358/nevermore-miner
disabled fee and recompiled: https://github.com/nemosminer/Ccminernevermore

Initial release. Windows 32-bit

11-hour side-by-side comparison on 1080 Ti show 20% increased hashrate over ccminer-2.2.5

compiled with vs2013 cuda 9 32bit

Best Regards
Nemo

**Comment by Quake4** [comment]
Thanks.

**Comment by nemosminer** [comment]
Your Welcome

**Comment by nemosminer** [comment]
note: i just compiled a x64 Release it performs even better 

https://github.com/nemosminer/ccminernevermore/releases

https://github.com/nemosminer/ccminernevermore/releases/download/0.1-nevermore/ccminernevermore0.1x64.zip

Best Regards Nemo
