### ISSUE TITLE
sgminer-fancy-5f crashing RX560+RX580 rig

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#286]
at least on allium algo

**Comment by jestercore** [comment]
lyra2z crash too

**Comment by Quake4** [comment]
please disable all algo in config file without allium.

**Comment by jestercore** [comment]
miner crashing on all algos

**Comment by Quake4** [comment]
strangely
just is disable it

**Comment by jestercore** [comment]
issue still persist

**Comment by jestercore** [comment]
It's bugged for RX 560.

**Comment by fancyIX** [comment]
Fixed 580 and Vega. Tested two hours without crash. Updated the archive in release page. Please download again.
