### ISSUE TITLE
[miner update] Z-ENEMY 1.24 ver.3 

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#291]
on discord

- Major optimizations for skunk, polytimos and phi
- Minor optimizations for hex and x16r/s, tribus.
- Massive performance boost for RTX 2080/2080ti/2070 in many algorithms.

Other: 
- Highlighted hardware stats reporting, colored GPU temperatures (green/yellow/red)
- Added Volta architecture support
- Important update(1.24 ver.2): Fixed multi-gpu crash bug (skunk and polytimos)
- Important update(1.24 ver.3): Fixed reduced poolside hashrate ( XDNA : hex algo)

**Comment by Quake4** [comment]
only this: `Important update(1.24 ver.3): Fixed reduced poolside hashrate ( XDNA : hex algo)`
