### ISSUE TITLE
Reading web response

### ISSUE THREAD

**Issue by bonifacio123** [Quake4/MindMiner#293]
Since the 3.11 update I see the following message on both rigs and they don't seem to go away. Restarted the rigs and the messages reappear:
```
 Reading web response
    Reading response stream... (Number of bytes read: 11680)
```
Active pools: NLPool and Blockmasters, Blazepool

**Comment by bonifacio123** [comment]
OK, had an idea to select different pools and then select these three again, restart, and now the message does not appear.

**Comment by bonifacio123** [comment]
Oh well, the message box is back and stuck again:


MindMiner 3.11   http://MindMiner.Online   (C) 2017-2018 by Oleg Samsonov aka Quake4


 Reading web response
    Reading response stream... (Number of bytes read: 4380)

                Wallet BTC: 15nV26qRSiNf42fjUwHtaFR7cT4umqWSQi
 Profitability Lower Floor: "CPU": 0.00001, "nVidia": {"USD": 1.20}
Timeout Loop/Check/No Hash: 60 sec/5 sec/10 min
Hash Speed Average/Current: 1 day/180 sec
      Switching Resistance: True as 4% or 15 min
             Active Miners: nVidia <= Allowed: nVidia
                API Server: Disabled
                    Region: Usa

   Type: nVidia

Miner                Algorithm Speed, H/s    BTC/Day USD/Day BTC/GH/Day Pool         ExtraArgs
-----                --------- ----------    ------- ------- ---------- ----         ---------

**Comment by Quake4** [comment]
this inscription appears when the connection to the network is unstable. How to make it disappear I do not know
