### ISSUE TITLE
dredge reading problem

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#297]
Hi, see this picture here:

https://i.imgur.com/6bqBGOR.png

Also you misspell "unknown" here:  https://i.imgur.com/PesaeOS.png

"Uknown" should be spelled "Unknown"

**Comment by AcharyaOne** [comment]
Same here

**Comment by mo35** [comment]
for quick dirty fix you can use following (im too lazy to dig where api type "dredge" is coming into play)

open Get-Speed.ps1 (code dir.)
find line 127 (use notepad++ or sumthin like that)
change this line to following :

{ $_ -eq "ccminer" -or $_ -eq "ccminer_woe" -or $_ -eq "dredge"} {

**Comment by Quake4** [comment]
Change api in old dredge ps1 file to ccminer.
Sorry.

**Comment by Quake4** [comment]
Fixed in 3.16. Press Ctrl+R to update.
