### ISSUE TITLE
Errors on Initial Run

### ISSUE THREAD

**Issue by DonavonPage** [Quake4/MindMiner#3]
On initial setup, I fill in the info for the config.txt file, the file is created, and I get this error on startup:

![capture0](https://user-images.githubusercontent.com/35850976/35459087-a841b31a-0293-11e8-92c0-267939f5eb89.PNG)

All these errors once the miners are loaded:

![capture](https://user-images.githubusercontent.com/35850976/35459007-6de63ab0-0293-11e8-8bff-ceff34d29e78.PNG)

Did I miss a step?

Here is a copy of the config.txt file that it created: (Should Currencies be null?)

{
    "Region":  "Europe",
    "SSL":  true,
    "Wallet":  {
                   "BTC":  "redacted"
               },
    "WorkerName":  "MindMiner",
    "Login":  "redacted",
    "Password":  "x",
    "CheckTimeout":  5,
    "LoopTimeout":  60,
    "NoHashTimeout":  10,
    "AverageCurrentHashSpeed":  180,
    "AverageHashSpeed":  "1 day",
    "AllowedTypes":  [
                         "nVidia",
                         "AMD",
                         "Intel"
                     ],
    "Verbose":  "Normal",
    "Currencies":  null
}

**Comment by Quake4** [comment]
thanks. fix in next version

**Comment by Quake4** [comment]
please start from simple config:
{
    "Wallet": { "BTC":  "Your BTC wallet" },
    "WorkerName": "Rig/Computer Name",
    "Login": "Login for Pool with registration",
    "AllowedTypes": [ "CPU", "nVidia", "AMD", "Intel" ],
    "Currencies": { "BTC": 8, "USD": 2 }
}

**Comment by Quake4** [comment]
Hi Donavon!
Working?

**Comment by DonavonPage** [comment]
Going to grab the .45 update and see...

There is an issue apparently with the BinFolder parameter not looking in the right place so it is not finding the detectors. After I put the full path in Get-Config.ps1:

                                [Config]::CPUFeatures = Get-CPUFeatures ("C:\BitcoinMining\MindMiner-master\bin")
                                [Config]::AMDPlatformId = Get-AMDPlatformId ("C:\BitcoinMining\MindMiner-master\bin")

that issue is fixed. It is passing null to Get-CPUFeatures([Parameter(Mandatory)][string] $bin) otherwise so apparently BinLocation is not getting set before the call?

It is running benchmarking now (on the .45 update) so definitely further than it was getting.

Thanks!
Donavon

**Comment by DonavonPage** [comment]
When the script starts a miner, I get this message:

[cid:image001.png@01D39756.48156660]


When I copy the Command from the window and make it so I can run it manually, it starts fine.

[cid:image002.png@01D39756.48156660]

**Comment by DonavonPage** [comment]
Currencies still not processing correctly. Keeps ending up being null so doesn’t show BTC or USD columns.

I have to enter them manually into the config file:             "Currencies": { "BTC": 8, "USD": 2 }

**Comment by Quake4** [comment]
BinLocation transmit normally, else not working nothing.
Please, attach images frome above.
If you use drive "c:", please add rights your windows user to folder ""C:\BitcoinMining\MindMiner-master" or try move MindMiner to My Documents.

**Comment by Quake4** [comment]
Currencies fixed. Thanks for report error.

**Comment by Quake4** [comment]
> BinFolder parameter not looking in the right place
Where programm looking?

**Comment by Quake4** [comment]
Donavon, you run programm from run.bat?

**Comment by DonavonPage** [comment]
Was not running run.bat because it errors out.
[cid:image001.png@01D39781.58494AD0]

**Comment by Quake4** [comment]
Plesase attach screen on github site. Its dont showing.

**Comment by DonavonPage** [comment]
The bat doesn't work because my default directory for powershell is one directory up. If I fix that issue, then it will start, but then it cannot find the '.\Code\Out-Data.ps1' pathing. I don't really want it automatically updating the files anyway because when it does, all the ps1 files get marked as untrusted and I have to fix that before anything else will work. Running just the MindMiner.ps1 is working after hard-coding the default BinLocation and entering currencies in config.txt manually.

**Comment by DonavonPage** [comment]
Got everything working! Your code is much better than what I had been using (Nemos_Miner)! Well done!

A couple of thoughts, suggestions:


  1.  Make update optional.
     *   I don’t know if everyone has this issue, but after an update, nothing will work until I touch all the ps1 files to tell my computer to “Unblock” the files. I don’t always have time to do this to get things running again! 😊
                                                               i.      If you convert your startup .bat to a .ps1, maybe you can include this line to unblock the files automatically:

           *   Get-ChildItem .\ -file *.ps1 -recurse | Unblock-File
  1.  Make “WorkerName” default to the name of the computer.
     *   In Config.ps1
                                                               i.      [string] $WorkerName = $env:computername

     *   Then I just delete WorkerName from config.txt file and then I can copy the MindMiner folder to other computers and not have to re-configure them in any way
  1.  I converted the startup .bat to a .ps1 and this works to resolve my issue with my default powershell folder not being the root install location of MindMiner. It also fixes my issue with the “Bin” location setting. (I was still having to hard-code the Bin location in Config.ps1.)
     *   cd .\MindMiner-master\
     *   .\MindMiner.ps1

Donavon Page

**Comment by Quake4** [comment]
Hi, Donavon.

> Your code is much better than what I had been using

Thanks.

>  maybe you can include this line to unblock the files automatically
> Make “WorkerName” default to the name of the computer.

Yes. Included in 0.50.

>  I converted the startup .bat to a .ps1 and this works to resolve my issue with my default powershell folder not being the root install location of MindMiner. 

How I can set default powershell folder to test this use case?

**Comment by DonavonPage** [comment]
How I can set default powershell folder to test this use case?
To set powershell default startup location:


1.                   In “Documents” create a folder called “WindowsPowerShell”

2.                   Create a file in that folder called “Profile.ps1”

3.                   In that file, add a change directory line

     *   Cd c:\altcoinmining\

[cid:image003.png@01D3999E.9D2F1F70]

After doing this, whenever the user opens powershell, it will start in the indicated directory

Donavon

**Comment by Quake4** [comment]
Hi, Donavon Page.

Please, download new version 0.51. Run.bat has fix to powershell user profile.
