### ISSUE TITLE
no workername on blazepool

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#30]
There is no visible workername on blazepool.

**Comment by Quake4** [comment]
please, look "State: Running" and it command line after c=BTC. Its has workername?

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/38271724-e623665c-378f-11e8-8526-dc47d3967d25.png)

**Comment by Quake4** [comment]
Fix it. Wait next version, please.
