### ISSUE TITLE
User deiined intensity

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#300]
Would it be possible to define a default intensity for each miner, (T-Rex, enemy, etc)

**Comment by Quake4** [comment]
write to extraargs parameter any miner parameters

**Comment by Quake4** [comment]
```json
{
    "Algorithms":  [
                       {
                           "ExtraArgs": "-i 23",
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "x16r"
                       },
   ....
```

**Comment by AcharyaOne** [comment]
Yes, but you have to define that on every updated miner, wouldn't it be more efficient to have some user defined parameters so we don't have to change them every time?

**Comment by AcharyaOne** [comment]
The user defined parameter would create the same intensity for every algo of that miner

**Comment by Quake4** [comment]
copy config for new miner

**Comment by AcharyaOne** [comment]
I don't know how most do it but I control the miner many times from my cellphone and it's not so easy to do it there. And on top of that I have miner working at night because of the cost of electricity and I check the phone at night and press y to benchmark, it would make my life easier if I had the intensity I want for each miner defined already
