### ISSUE TITLE
Pool_Variety config.txt Pools

### ISSUE THREAD

**Issue by petrovsky34** [Quake4/MindMiner#305]
{
    "AverageProfit": "1 hour",
    "Enabled": true,
    "Wallet": "LTC"
    "Pool_Variety = 0.85
}
 что то типа токого можешь добавить пожалуйста??? что бы я сам выбирал число какое поставить.

**Comment by Quake4** [comment]
Да. А сколько и кому хочешь поменять?

**Comment by AcharyaOne** [comment]
I think he means having the pool variety in the pool user defined config.

**Comment by AcharyaOne** [comment]
Could I ask you to update hashrefinery pool file for people that still use it?

**Comment by Quake4** [comment]
the hashrefpool file is uptodated in archive

**Comment by Quake4** [comment]
колько и кому хочешь поменять?

**Comment by Quake4** [comment]
"Variety": 0.9
Только посчитай реальный выход через 24 часа

**Comment by Quake4** [comment]
Ибо найс это здесь и сейчас, а пулы это через 6-12 часов
