### ISSUE TITLE
PLUS logic integrate

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#31]
I will like to ask if there is possible to incorporate somhow PLUs logic theat uses NemosMiner ->  plus - uses advanced calculations to maximize profit.

At this point i dont know if MindMiner already uses simmilar solution?

**Comment by Quake4** [comment]
MindMiner profit calculation use 24 hour actual, current estiamted value and 24 hour estimated value.
I can say that MindMiner has its own unique algorithm.
