### ISSUE TITLE
Add Gminer

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#310]
Better performance than ewbf despite the 2% fee. Worth it.

**Comment by Quake4** [comment]
link?

**Comment by AcharyaOne** [comment]
https://bitcointalk.org/index.php?topic=5034735.0

**Comment by Quake4** [comment]
can you try master?

**Comment by AcharyaOne** [comment]
It's working fine, why didn't you enable the other algos as ewbf?

**Comment by Quake4** [comment]
No pools with it algos and for test it.

**Comment by Quake4** [comment]
Ewbf was tested.
