### ISSUE TITLE
Seeing this a lot

### ISSUE THREAD

**Issue by bonifacio123** [Quake4/MindMiner#311]
I'm not mining HashRefinery but see this with 3.27

Pool(s) request ...
ReadOrCreateConfig : The term 'ReadOrCreateConfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At E:\coin\MindMiner\Pools\HashRefinery.ps1:13 char:8
+ $Cfg = ReadOrCreateConfig "Do you want to mine on $($PoolInfo.Name) ( ...
+        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ReadOrCreateConfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Quake4** [comment]
extract pool file from archive
