### ISSUE TITLE
Add switching resistance between pools on same algo

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#314]
Hi, I notice when I watch x22i as most profitable it bounces around 2-3 pools like ZPOOL and BLAZEPOOL back and forth every few minutes.  I already have custom diff values set but still I think switching resistance needs to account for if I am already mining x22i on BLAZEPOOL and it's within "20%" of ZPOOL don't make it switch back and forth.

Loop 1 Blazepool $2 Zpool $2.20 - mine on Zpool
Loop 2 Blazepool $2.20 Zpool $2.00 - I want this to stay on Zpool, no need if switch to Blazepool since
Loop 3 Blazepool $1.80 Zpool $2.40 - this why I stay on Zpool if lose one minute to switch and reload miner then I am losing almost all 3 minutes of mining with reloads and job serves.

**Comment by platinum4** [comment]
Any luck on this?  Happens often with Argon2-dyn on my 290X

**Comment by platinum4** [comment]
I feel like this is already resolved by leaving Switching on "Normal" instead of "Fast"

**Comment by Quake4** [comment]
no. but for now, the solution requires increasing the memory used by N times. I haven't found a better solution yet

**Comment by Quake4** [comment]
added, did not require much overhead

**Comment by Quake4** [comment]
add a new bug :(

**Comment by Quake4** [comment]
done
