### ISSUE TITLE
Setpower error

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#321]
![image](https://user-images.githubusercontent.com/31579891/49462233-73635680-f7ed-11e8-868e-49d3102a3a48.png)

**Comment by AcharyaOne** [comment]
nevermind, client wasn't updated correctly

**Comment by Quake4** [comment]
Don't get master. Get only releases.

**Comment by Quake4** [comment]
Or i write special for quick fix or test it.
