### ISSUE TITLE
Update sgminer-kl to 1.0.9

### ISSUE THREAD

**Issue by Quake4** [Quake4/MindMiner#323]
https://github.com/KL0nLutiy/sgminer-kl/releases

**Comment by sgeneralov13** [comment]
@Quake4 sgminer-kl not send hashrate
![2019-01-21_15-04-34](https://user-images.githubusercontent.com/35292309/51473879-a9a16900-1d8e-11e9-9ad9-6279af10458f.png)
![2019-01-21_15-04-52](https://user-images.githubusercontent.com/35292309/51473953-d9507100-1d8e-11e9-8e1c-03e1e1ccdbe9.png)

Benchmark not passed too. Time to bench -- 10 minutes.
