### ISSUE TITLE
question regarding electricity calcs

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#324]
i configured ElectricityPrice , set DevicesStatus and ElectricityConsumption true , but im not getting anything on Electricity column 

p.s. what you mean by working `nvidia-smi` , its by default installed on Win with driver installation and working just fine from command prompt

any tips how to get electricity part working ?

**Comment by Quake4** [comment]
1. Is showed in MM window your devices?
example for cpu, for you need nvidia gpu
```
                    Region: Europe

CPU x 1: Intel Core i3-6100 @ 3.70GHz, 3696 Mhz, 2/4 Core/Thread, MMX SSE SSE2 SSE42 AES AVX AVX2

   Type: CPU
```

**Comment by Quake4** [comment]
3. Is can see in MM window messege like `Can't run nvidia-smi.exe: xxx`

**Comment by mo35** [comment]
no errors whatsoever , and i see on test box line "nvidia x 1: GTX1080ti , etc ... " thats prolly smi output , but nothing in electricity calculations

**Comment by Quake4** [comment]
please copy past ElectricityPrice parameter string from config to next message

**Comment by mo35** [comment]
wattage shows fine on smi line

last 3 config lines , related to electicity calcs

"DevicesStatus": true,
"ElectricityPrice": { "USD": 0.10 },
"ElectricityConsumption": true

**Comment by Quake4** [comment]
its right config.
`but im not getting anything on Electricity column`
if current value of electricity is zero, electricity cost inserted after benchmark timout for current miner, but switching resistant will not allow to switch to the next benchmark quickly
set full verbose by V and see to bottom of nvidia miners list

**Comment by Quake4** [comment]
or clear all stat and rebenchmark all

**Comment by mo35** [comment]
ok , ill rerun benchmarks and let you know 

p.s. gona take some while

**Comment by Quake4** [comment]
is it working?

**Comment by mo35** [comment]
on benchmarks i see wattage summary , will post back how it looks later on on calculation tab , benches gona take some time because i run each bench 240 secs by default

**Comment by Quake4** [comment]
its too much. 150-180 is normal.

**Comment by Quake4** [comment]
wattage sets after 240 sec

**Comment by AcharyaOne** [comment]
I also had some problems with certain miners not showing the electricity cost so I disabled Electricity Consumption for now. Not sure the problem was due to a crash in gpu drivers which affected the electricity cost even after restarting mindminer (didn't restart rig)

**Comment by Quake4** [comment]
electricity cost(power consumption) inserted/saved to miner stats only after benchmark or run this miner longer than benchmarking timeout configured for it.
remove all stat and rebench all.
