### ISSUE TITLE
How to LTC on zerg

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#33]
my question is how to add 2 differend wallets if i mine on zerg + other pool?. So where can i configure BTC wallet i already know --> at this point i dont know how to set up LTC wallet only for zerg and leave BTC wallet for other pools?

**Comment by Quake4** [comment]
fix it, try 1.48:
if has both LTC & BTC wallet use on zergpool LTC wallet

change confit & specify both wallets:
`
	"Wallet": { "BTC": "xxx", "LTC": "yyy" },
`

**Comment by Quake4** [comment]
Its working?

**Comment by podlbo** [comment]
working 100% great :) exactly what i need ;) THANKS

**Comment by Quake4** [comment]
ltc balance not supported eat => #35
