### ISSUE TITLE
[Enhancement] MTP ccminer (kernlx) & MTP Pool

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#347]
Zcoin switched to asic proof algo MTP , CryptoDredge 0.15.1 isnt very stable yet. Kernlx relesed ccminer (on par with CryptoDredge performance wise (no fee and stable) compiled by Djm34.
https://github.com/zcoinofficial/ccminer/releases

from poolwise seems like https://mintpond.com/ is best.

**Comment by platinum4** [comment]
I think is OK to add for benchmark now that MTP is on yiimp

**Comment by Quake4** [comment]
https://github.com/Quake4/MindMiner/blob/master/Miners/ccminer-mtp-113.ps1
just isnt released

**Comment by Quake4** [comment]
and try https://github.com/Quake4/MindMiner/blob/master/Miners/tt-217.ps1

**Comment by platinum4** [comment]
Both of these work OK just not the most profitable so far so have not tested long term; I think we can close this

**Comment by daimaah** [comment]
It seems that the hashrate value is misread or something else happens, but after benchmarking 
ccminer-mtp-113 on my GTX 960, it's reported to have 1.05 GH/s speed with approximate profits of over 200 dollars a day.

**Comment by Quake4** [comment]
Remove file `ccminer-mtp-113.txt` from stats folder
Extend benchmark time to 180-240 in `ccminer-mtp-113.config.txt`
and try again

**Comment by platinum4** [comment]
This is probably good to close and add.

**Comment by mo35** [comment]
https://github.com/zcoinofficial/ccminer/releases
bumped to 1.1.4

stability improvement
small hashrate bump
