### ISSUE TITLE
x16r fastest ccminer test results

### ISSUE THREAD

**Issue by nemosminer** [Quake4/MindMiner#36]
thankyou @Tesla74 & @buxstore

Normalized Average Results

#1 - 108.51 RVN RavenCoin
#2 - 106.98 RVN Suprminer
#3 - 104.17 RVN PoolParty

Raw Average Results

#1 - 108.63 RVN RavenCoin
#2 - 107.21 RVN Suprminer
#3 - 104.16 RVN PoolParty

Full Article here:

https://ravenforum.org/topic/30/suprminer-1-6-vs-ravencoin-miner-v2-5-vs-poolparty-1-3-test-results

https://github.com/Ravencoin-Miner/Ravencoin/releases FTW

**Comment by Quake4** [comment]
спасибо.
