### ISSUE TITLE
cpuminer-bf-3810 --cpu-priority 0

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#364]
--cpu-priority should have value 1, because 0 didn't work at all. It's not possible to set low priority, only lower.

@bellflower2015 bug?

**Comment by Quake4** [comment]
```--cpu-priority    set process priority (default: 0 idle, 2 normal to 5 highest)```

**Comment by jestercore** [comment]
Yes, but with "0" task manager shows priority "normal". Try it.

**Comment by Quake4** [comment]
yes. its normal priority

**Comment by jestercore** [comment]
Isn't this commandline designed to set lowest priority to cpu mining? What about configuring all miners like this, for stability and quicker system response?

**Comment by Quake4** [comment]
ok

**Comment by Quake4** [comment]
All cpu miners i configure to lowest cpu usage as idle priority.

**Comment by jestercore** [comment]
Idle means - lowest? Awesome!

**Comment by Quake4** [comment]
https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-setthreadpriority
