### ISSUE TITLE
zergpool now has MTP algo

### ISSUE THREAD

**Issue by nemosminer** [Quake4/MindMiner#374]
Happy Mining

Tested on 1070 and above 

is cuda 10.0 so requires modern drivers..

Best Regards
Nemo

**Comment by nemosminer** [comment]
Your Program is Awesome by the way.. if you could remove from your README.md would be much appreciated #This is not another fork based on MultiPoolMiner (NemosMiner)

**Comment by nemosminer** [comment]
we have no claim... and nothering to post..

**Comment by Quake4** [comment]
https://github.com/nemosminer/NemosMiner/blob/73d12efc70e02e03ec6274e6ae77f6ce1ed61b07/Include.ps1
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/0293a9010dcc1411602a0245460b689c03e15472/Include.ps1

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/0293a9010dcc1411602a0245460b689c03e15472/MultiPoolMiner.ps1
https://github.com/nemosminer/NemosMiner/blob/73d12efc70e02e03ec6274e6ae77f6ce1ed61b07/NemosMiner-v2.0.ps1

it are equals
I won't remove.
