### ISSUE TITLE
добавить варинт "базовый" и "приоритет"

### ISSUE THREAD

**Issue by kirja23** [Quake4/MindMiner#38]
После долгожданного добавления внутреннего кошелька найсхеш, предлагаю добавить вариант для майнинга "базовый", допустим...
вариант 1 - не можем достучаться до приоритетного пула - майним то что указано в строке "базы"...
вариант 2 - профит упал ниже желемого значения - майним то что указано в стоке "базы"...
в строке базы предлагаю через конфиг вручную прописывать адрес нужного пула, порта, кошелька(юзера) и пароль...
На мой взгляд эта функция позволит в безрыбные времена майнить желаемую монету, допустим на пуле супрнова, или в любом другом месте.
Как развитие данной функции предлагаю так же вариант "приоритет": когда профит упал ниже задаваемого значения майним на таком то пуле, допустим если профит рига ниже 1мбтс, майним на пул найсхеш, если профит выше 1мбтс - майним там где выше. Эта фишка поможет опять же в безрыбные времена домайнивать на нужном пуле до очередной выплаты...эх еще бы привязать этот "приоритет" к времени ожидаемой выплаты - цены бы не было!

**Comment by Quake4** [comment]
В общем, идея понятна. Не совсем только понятно зачем это надо. Если профита нет, то можно просто майнер руками запустить на супрнову.
Программа и так все считает, сейчас найс иногда выстреливает с нормальным профитом на несколько часов или дней. Просто непонятно зачем такая логика в прграмме сделаной для другого, если разрешив найс и ахаш, получим например то же самое. А если надо премайн монеты сделать, то ручками.

**Comment by kirja23** [comment]
ну как вариант для чего нужно - профит упал в значения сопоставимые со стоимостью электричества - смысл майнить с таким профитом эквихеш нет, но если например включить криптонайт или этихеш (эфир) - расход электричества ниже, итоговая прибыль за "нерыбный" период - повышается. т.е. как пример - переключение на более экономный алгоритм.

**Comment by Quake4** [comment]
С электричеством все понятно. Неплохо бы сделать его учет, а для начала отображение потребления.
