### ISSUE TITLE
[Miner update] CryptoDredge v0.16.2

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#389]
https://github.com/technobyl/CryptoDredge/releases/tag/v0.16.2

Support GINcoin on X16RT algorithm
Fix P2Pool for Lyra2REv3
Add CNFastv2 (Masari and Stellite) algorithm
Add CNSuperFast algorithm
Other minor fixes

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/pull/391

**Comment by Quake4** [comment]
merged.
thanks to platinum4
