### ISSUE TITLE
Litecoin (LTC) as a payout currency on  hashrefinery

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#39]
Now also hashrefinery (http://pool.hashrefinery.com) supports Litecoin (LTC) as a payout currency :) Can you also add this option?

"Litecoin (LTC) is now available as a payout currency"

**Comment by Quake4** [comment]
Ок.

**Comment by Quake4** [comment]
See version 1.57.

**Comment by podlbo** [comment]
Now with update Hashrefinery pool does not read my current BTC ballance...
![slika](https://user-images.githubusercontent.com/33230718/38977364-7b869e64-43b4-11e8-8484-fd88df7fe048.png)

**Comment by Quake4** [comment]
balance in ltc not supported eat => #35
