### ISSUE TITLE
bminer-141 all shares rejected on beam on NH

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#396]
Invalid nonce (is miner compatible with nicehash?) warning. 0 accepted shares when you observe

**Comment by Quake4** [comment]
fixed. https://github.com/Quake4/MindMiner/commit/8591dc62ea1cec1cfce11a072616281ea427a4a3

**Comment by platinum4** [comment]
Not closed at all:
https://i.imgur.com/Jo5d40J.png
Used new .ps1

**Comment by platinum4** [comment]
Fresh run too
https://i.imgur.com/kHhVbKI.png
