### ISSUE TITLE
CPU mining on/off hotkey

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#399]
Please? Or even Nvidia and AMD switches too.

**Comment by platinum4** [comment]
Yeah I hate editing the config and also lower_floor never stops the miner once it falls below the floor

**Comment by Quake4** [comment]
@jestercore What for?
@platinum4 I checked lower floor - its works.
please, publish your config.txt without addresses

**Comment by jestercore** [comment]
> @jestercore What for?

I'm mining on my primary pc, and cpu mining makes whole system lag a lot. But when i'm afk or just watching YT its ok. At the current state i should restart and edit config to do so.

**Comment by platinum4** [comment]
I don't like that wattage isn't read on CPU mining but mining is generally inefficient for CPU for me so I stopped

**Comment by jestercore** [comment]
It's ok to run two mindminer instances? Gonna try to use one for gpu, and another for cpu

**Comment by Quake4** [comment]
yes, you can, from two different folders
and select devs by
```"AllowedTypes": [ "CPU", "nVidia", "AMD" ]```

**Comment by Quake4** [comment]
in next release

**Comment by jestercore** [comment]
Thank you sooo much! But... i can't find hotkey

**Comment by Quake4** [comment]
T

**Comment by Quake4** [comment]
this feature is active only if you have more of one "AllowedTypes" in config.txt

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/52692243-73619e80-2f74-11e9-8789-3a82e5154515.png)

**Comment by platinum4** [comment]
Can you have in config a place to allow CPU but disable by default?  If I add CPU it will add as Active by default

**Comment by Quake4** [comment]
By default, you say to MM who may work: ```"AllowedTypes": [ "CPU", "nVidia", "AMD" ]```
in online you can disable any, minimum one must be enabled

**Comment by Quake4** [comment]
its need if reboot happens without your presence.
