### ISSUE TITLE
Where is algorithms from the pool?

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#40]
Is it possible to add algos SKUNK, PHI and SKEIN?
On blazepool Skunk seems to be profitable + PHI and SKEIN are ok for Hashrefinery per instance ;)

**Comment by podlbo** [comment]
Thanks for hellp ;) I don not know from the start what is VERBOSE level ;) If i get it rigt it meens how much algos is considered for mining ;)

**Comment by Quake4** [comment]
No, `Verbose level` its how much show info about work of MindeMiner.
Full - fully detailed all clculations.
Normal - only one algo per miner program and only 0,65 higher profit from top in group.
Min - my favorite, show minimal info about miners only 0.8 from higher miner + total balance.

**Comment by podlbo** [comment]
OK - sorry .... Ok will check benchmark stat if it is look normal ;)
