### ISSUE TITLE
[Miner Add] NBMiner v21.4

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#421]
p.s. not tested latest performances myself

https://github.com/NebuTech/NBMiner/releases
https://bitcointalk.org/index.php?topic=5099379.0

Add support for Grin31
Add support for mining Grin on NiceHash
Add new option to tune CPU usage when mining Grin.
Improve BTM+ETH performance on RTX cards.
Fix bug of lower hashrate when mining BTM on rigs with mixed 10 series and 20 series cards.
Do not add a default worker name if no worker name specified by user.

**Comment by mo35** [comment]
p.s. on mixed nvidia rig for cucaroo29 performance is same as latest bminer , not sure about fidelity yet , need to see performance results pool side over time

**Comment by mo35** [comment]
good thing about this one is , that it supports 1060 6gbs under win10 for cucaroo29 , bminer also does it (unfortunately bminer seems bit messy , lot of rejects , lots of stales) , gminer doesnt support 1060 6gbs under win10 at all

**Comment by mo35** [comment]
NBMiner v21.0
https://github.com/NebuTech/NBMiner/releases

Add support for AE (Aeternity)
Improve performance on Grin29 & Grin31
Improve miner stability.

**Comment by mo35** [comment]
v21.0 for mixed nvidia setup 1060 6gb , 1070 , 1070 ti is fastest on grin29

**Comment by mo35** [comment]
any chance to have this added , its performing best on mixed nvidia rigs with cucaroo29  , bminer supports 1060 6gbs , but that miner behaves weirdly , gminer dosnt support 1060 6gbs on win10 at all

**Comment by platinum4** [comment]
Hi, can we please add this now?

**Comment by mo35** [comment]
https://github.com/NebuTech/NBMiner/releases

Improve Grin29 performance
Add support for mining Grin & AE on Turing cards.
Add detection for GPU hung.
Increase chance of accept share when mining Grin on NiceHash.
Fix ETH mining on NiceHash.
Fix "accecpt share checking" bug when using backup mining pools.

**Comment by mo35** [comment]
https://github.com/NebuTech/NBMiner/releases

Fix bug: "GPU hung detected" happens under some normal conditions.

**Comment by mo35** [comment]
https://github.com/NebuTech/NBMiner/releases

Fix bug: Occasionlly lower local hashrate than previously version.
Do not run GPU if mining pool not connected when mining Grin & AE.

**Comment by mo35** [comment]
https://github.com/NebuTech/NBMiner/releases

Improve Grin31 performance.
Improve performance of Grin29 & AE on RTX cards.
Fix Grin31 compatibility on Win7 with 8G cards.
New option to reduce the range of power consumption by multi-gpu rig.
Add miner Up Time print in cmd outputs.

**Comment by Quake4** [comment]
added
