### ISSUE TITLE
[Miner Update] gminer 1.34

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#422]
https://github.com/develsoftware/GMinerRelease/releases

support Swap coin (cuckaroo29s algorithm)
support Beam mining on AMD cards under linux
fixed bug with "clean jobs" for grin leading to loss of actual solutions and inconsistency of miner hashrate and pool hashrate
improved fidelity up to 5% for grin29 and aeternity, it will increase your hashrate on pool side
added command to enable/disable cuda/opencl platform (--cuda 0/--opencl 0)

**Comment by Quake4** [comment]
in same time was commit
