### ISSUE TITLE
Setting benchmark time for all algos/pools in config.txt?

### ISSUE THREAD

**Issue by Myran1** [Quake4/MindMiner#43]
Would it be possible to determine the benchmark time for all algos and pools in the config.txt?

60-120secs are sometimes just waaaay to short time peroid to get nearly good results.

**Comment by Quake4** [comment]
Yes, I can. But I try to lower bechmark time. Let's increase the time on a particular algorithm and miner.

**Comment by Quake4** [comment]
Where is extend benchmark time?

**Comment by Quake4** [comment]
In version 1.66 i add changes to benchmark accuracy in the results. Please, write feedback if it has wrong values.
