### ISSUE TITLE
loops randomly stops

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#44]
im testing on x3 6 card rigs , loops on all of them randomly stops after a while , no errors nothing , mindminer just stops looping , launched miner keeps running. If im pressing V to change verbose mode , "pools request" message apears and loop runs again.

**Comment by Quake4** [comment]
Time on this machines changed to back. I can resolve this issue i next version. Please wait.

**Comment by Quake4** [comment]
Please recheck your configuration, someone sets the time forward and backward again.

**Comment by Quake4** [comment]
Try version 1.64. Its fix this issue, but not fix issue with profit calculation due to time change.

**Comment by Quake4** [comment]
Its working?

**Comment by mo35** [comment]
one of rigs still got stuck after 3 loops with 1.64 , time on rig was correct. same as before , hitting verbose mode change continued loop.

**Comment by Quake4** [comment]
Maybe you click to window and window going to selection mode?
Left angle - properties - options - edit options - quick edit mode - uncheck box.

**Comment by mo35** [comment]
i dont thing so , but just in case i unchecked quick edit option , also im running timechanger on all 3 rigs , if loop stops and i manage to catch error , i will report back

**Comment by Quake4** [comment]
ok, waiting for report ...

**Comment by Quake4** [comment]
?

**Comment by mo35** [comment]
over 300 miner loops and almost 5000 timechange loops , so far not observed any gliches anymore

**Comment by Quake4** [comment]
Ok, its was selection. thanks.
