### ISSUE TITLE
3.82 problem

### ISSUE THREAD

**Issue by smarcello** [Quake4/MindMiner#451]
after short time, MindMiner 3.82 is stucked:

online | name | tempe­rature, C | pool | miner | algo­rithm | speed, H/s | btc/day | run/up or down time
-- | -- | -- | -- | -- | -- | -- | -- | --
  | multipoolminer / CPU |   | ZergPool-YTN | cpuminer-opt-3881 | Yescryptr16 | 68.79 | 0.00000682 | 00:08:41
  | multipoolminer / AMD | 74 | NiceHash-Europe | claymore-eth-120 | Ethash | Unknown | 0.00004615 | 00:08:41

also all letter commands on the bottom do not react at all!

**Comment by Quake4** [comment]
Disable quick edit mode in MM window:
https://www.isunshare.com/windows-8/quick-edit-mode-in-command-prompt-how-to-open-it.html

**Comment by smarcello** [comment]
Thanks
