### ISSUE TITLE
[miner update] bminer 15.2.0

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#452]
https://www.bminer.me/releases/

Improve performance of Cuckaroo29 / Cuckatoo31.
Reduce reject rate of Cuckaroo29 / Cuckatoo31.
Experimental support Cuckaroo29 on AMD cards (ROCM only)
Improve compatibility on Windows.
Fix the regression on UI dashboard.

**Comment by platinum4** [comment]
please also add else if for 1% grin fee not just else 2

**Comment by mo35** [comment]
https://www.bminer.me/releases/

15.2.0 (Current)
Improve performance and stability of Cuckatoo31.
Support RTX 2080 for Cuckatoo31.

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/commit/bbb0b85f2a7e87d553b0814f00d8bdc3f271199f
