### ISSUE TITLE
hashrefinery earnings

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#46]
When mining on http://pool.hashrefinery.com using BTC wallet somehow mining earnings does not register on pool... Seems there is something wrong with settings? After mining for 8 hr only ONE earning was detected...   | Verge (x17) | 0.134209 XVG | 0.009% | 0.00092 | 8h ago |  

![slika](https://user-images.githubusercontent.com/33230718/39203445-149365e4-47f5-11e8-94e9-ce421b542a5a.png)

I notice one problem with selected port numbers -> for phi on pool is phi | 8333 |  -> but when mine i get
![slika](https://user-images.githubusercontent.com/33230718/39203730-f33d2bd6-47f5-11e8-8bd8-084ad3ac262e.png)

Maby problem is also with other ports?

**Comment by Quake4** [comment]
No its normal, pool has 2 orphans. 8 hours has one block. See pool statistic by x17 algo

**Comment by Quake4** [comment]
![screenshot_20180425-073617](https://user-images.githubusercontent.com/29517243/39226685-aae295a8-485c-11e8-9885-46521130a24f.png)

**Comment by Quake4** [comment]
Dont use small pools. My recomendation. Use zerg, ahash, zpool, nice & mph.

**Comment by podlbo** [comment]
OK ;) thanks so it is what it is ;)
But for PHI algo is still strange - > on pool it says port 8333, but when mining MM select PHI algo with port 8383.

**Comment by Quake4** [comment]
> But for PHI algo is still strange - > on pool it says port 8333, but when mining MM select PHI algo with port 8383.

MM is use ports from http://pool.hashrefinery.com/api/status

**Comment by podlbo** [comment]
Thanks ;) i notice pool change port today.
