### ISSUE TITLE
[Miner add] Bminer 15.3.1

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#472]
https://www.bminer.me/releases/

Slightly improve performance of Cuckaroo29 / Cuckatoo31.
Reduce CPU usages of Cuckatoo31.
Fix the regressions of Cuckaroo29 on RTX cards.
Fix the incorrect reportings of Ethash speed to the mining pools.

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/pull/471/commits/e0f76bd55dbcb156235b53a3f93e440fadf559a2

**Comment by Quake4** [comment]
Merged
