### ISSUE TITLE
xmrstak crashing rig

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#474]
i have pc with RX560 only, and xmrstak crashing windows when benchmarking. Without xmrstak - everything is ok. Remove it, please? Is superseeded by the way

**Comment by platinum4** [comment]
You can set this to false in the config file and not use it, or delete it yourself

**Comment by Quake4** [comment]
disable miner xmrstak on new version in it config `xmrstack-xxx.config.txt` before press y,
