### ISSUE TITLE
[miner upgrade] tt 2.1.17

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#475]
https://bitcointalk.org/index.php?topic=5025783.0
https://TradeProject.de/download/Miner/TT-Miner.zip

Version 2.1.17 release

   - changed some functions of the miner so that the number of rejected shares will be reduced again - also for NiceHash pool.
         You might still see rejections under certain conditions - for example:
              - if a new job comes in while the miner send a solution for the old job
              - the connection to the pool was reestablished just before the solution was sent
   - set default intensity for MTP to 20.

To get the most out of your system you should always try other values (+- 1 of the current values the miner shows you on start) for intensity and for finetuning you should use grid-size value directly.

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/commit/266ad40dbdb67556c71b4f88eb7b23edb11957ad
