### ISSUE TITLE
Программа для увелечения хешрейтa eth майнинга на gddr5x (1080, 1080ti, titan)

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#48]
https://mining-help.ru/articles/121-programma-dlja-uvelechenija-heshreita-eth-maininga-na-gddr5x-1080-1080ti-titan-ot-nvidia.html

Программа для увелечения хешрейтa eth майнинга на gddr5x (1080, 1080ti, titan)

изучай. может дельное что то . у меня 1080 и 1080ti стоят

**Comment by Quake4** [comment]
Ссылка только куда то не туда. https://github.com/OhGodACompany
