### ISSUE TITLE
[miner update] tt-miner 2.1.19

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#480]
New version 2.1.18 ready for download.

Release notes:
  - New option: -log creates a logfile that contains the screen output and
         additional information that could be helpful to find bugs.
  - New option: -luck shows a second statistic line - additional to the rig
         speed. It shows the time it may take to find a new solution(share)
         at the current difficulty. It also calculates a 'luck' value that
         show the luck in percent for the next share.
  - New option: --api-type does nothing so far, TT-Miner support TCP connections only
  - Remove the three stars in the 'Accepted share' message.
  - The meaning of the -A parameter changed slightly. If you define an algo without
  - cuda version, TT-Miner will load the algo that fits best to your installed
  - driver version - it will no longer load the algo for the last cuda version!

**Comment by mo35** [comment]
New version 2.1.19 ready for download.

Release notes:
 - Headline-color changed from blue to yellow.
 - Reduced memory-requirements for MTP (host-side only - not GPU)

**Comment by Quake4** [comment]
added
