### ISSUE TITLE
OverdriveN

### ISSUE THREAD

**Issue by Imaminer** [Quake4/MindMiner#491]
How do I use it?
I see it in the /bin folder but I get error messages "empty" something.
I'm on a all AMD rig.

**Comment by Quake4** [comment]
can you run from cmd `OverdriveN.exe` and post output?

**Comment by Imaminer** [comment]
It wont execute. I'll download a version straight from Guru3d and try that.

**Comment by Imaminer** [comment]
Issue resolved by actually reading the readme file lol
Just had to add a few more visual C files.
![overdriveN](https://user-images.githubusercontent.com/30805282/55585831-8d5a6a80-56f5-11e9-8f93-4b39225a6807.JPG)

**Comment by Quake4** [comment]
Fine
