### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by ghostofiht** [Quake4/MindMiner#492]
Hello, I support open source projects with my logo designs. I can't wait to contribute to MindMiner. I have a great logo idea for MindMiner.  You want to see this?

**Comment by ghostofiht** [comment]
I know that MindMiner is a mining monitoring and management project. In the design, I designed the "miner helmet" and the "monitoring screen" in it's light.  Thus, I have clearly shown the function of MindMiner. I hope you like it. Don't hesitate to tell me if you want me to make any changes. 
I look forward to your comments.

Here's my design ; 

![mindminer](https://user-images.githubusercontent.com/42060713/55828962-35b56800-5b16-11e9-988c-f1ab99872b22.jpg)

It will look like this on the website ;

![minminner](https://user-images.githubusercontent.com/42060713/55828982-44038400-5b16-11e9-8607-34f5a103b3ad.jpg)

**Comment by Quake4** [comment]
To be honest, I don't really like it.

**Comment by ghostofiht** [comment]
@Quake4 You may not like it. This is not a problem. I can design a new logo if you want. But I'm gonna need your opinion on this. Or you can close this issue if you want. Thanks .
