### ISSUE TITLE
Accepted shares accounting is too sensitive

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#493]
How can i turn it off, or let my very slow cpu still mine?

**Comment by Quake4** [comment]
extend benchmarktimeout for needed algo 
(now, need one share in time interval benchmarktimeout * 5)

**Comment by jestercore** [comment]
Set is to * 6, please, temporary at least

**Comment by platinum4** [comment]
@Quake4 I don't think this is necessary to keep open any more.

**Comment by jestercore** [comment]
irrelevant
