### ISSUE TITLE
Error key_id

### ISSUE THREAD

**Issue by Imaminer** [Quake4/MindMiner#499]
![mm error](https://user-images.githubusercontent.com/30805282/57784227-916aa680-76fd-11e9-9639-ba9e28e3646f.JPG)

**Comment by Quake4** [comment]
Check your apikeyid on site and in config.txt

**Comment by Imaminer** [comment]
Thanks. I generated a new key and put in config. Error seems gone now.

**Comment by Quake4** [comment]
If you dont use MM 7 day, key is erased.
