### ISSUE TITLE
GMiner is only using 1 GPU

### ISSUE THREAD

**Issue by Imaminer** [Quake4/MindMiner#509]
Tested on all AMD rigs. Gminer not recognizing all GPU's.
Only 1 GPU
This rig has 4 GPU's

![gminer_LI](https://user-images.githubusercontent.com/30805282/61298758-cc945f00-a7ac-11e9-8367-f8bdba1892c3.jpg)

**Comment by Quake4** [comment]
run gminer manually and add log writing
create issue here https://github.com/develsoftware/GMinerRelease/issues/new
with screen and log and window of device manager with expand group video cards from it rig

**Comment by Imaminer** [comment]
This looks like a miner issue not a MM issue. Thanks
