### ISSUE TITLE
Miningpoolhub

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#52]
I have problem conecting to Miningpoolhub using correct user name... with all algos i get... (Bminer, grestl...)
"autorisation error..."

**Comment by Quake4** [comment]
Check login.

**Comment by Quake4** [comment]
Write to me your login. I test its.

**Comment by Quake4** [comment]
**podlbo**, please write answer.

**Comment by Quake4** [comment]
Ok. I test its later.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/39533764-92b73420-4e38-11e8-9864-2ac1d1770aa9.png)
All fine.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/39547416-346beb5e-4e60-11e8-822b-f5efb8845c2c.png)

**Comment by podlbo** [comment]
it now works also for me... I did test today, now seems to be working without problems. Thanks for all the hellp.

**Comment by Quake4** [comment]
Is Claymore still not working?

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/39690408-a9aab21c-51e2-11e8-8afa-5cf76066b5cf.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/39690454-d7dd0c5c-51e2-11e8-8d42-9d177f7f0b26.png)

**Comment by podlbo** [comment]
no speed?

**Comment by Quake4** [comment]
yes, all works fine.

**Comment by podlbo** [comment]
hmm... i dont know where is the problem. Maby antivirus or firewall blocks something.... for some reson only MPH dont work normal for me, with other pools i dont get problems (i did test and use all other options). 

I was using MPH before with nemos and Multipoolminer without problems... So for now i did disable MPH and use other pools ;)
