### ISSUE TITLE
a1min3r miner

### ISSUE THREAD

**Issue by podlbo** [Quake4/MindMiner#53]
maby interesting miner to add?
"https://github.com/a1i3nj03/a1min3r/releases/download/1.5-alpha2/ccminer-Win64.7z"

**Comment by Quake4** [comment]
Interesting does anyone else?

**Comment by Quake4** [comment]
Interesting does anyone else?

**Comment by Quake4** [comment]
https://bitcointalk.org/index.php?topic=3385643.0;all
Enemy 1.08 faster
