### ISSUE TITLE
ethminer fails to get speed

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#540]
Hi, I made a pull request to fix stratum for MPH but there is an issue that I don't know how to fix.

![image](https://user-images.githubusercontent.com/31579891/66666448-8a15dd80-ec48-11e9-8793-0408d0c36ff7.png)

**Comment by Quake4** [comment]
ethminer dont run api for access
and isnt compatible with mph
![image](https://user-images.githubusercontent.com/29517243/66703520-2fe64c80-ed1c-11e9-9042-9d2d8c11f725.png)

**Comment by AcharyaOne** [comment]
The change I tried to submit controlling what type of stratum is used gets shares accepted but maybe that isn't enough because of no api

**Comment by Quake4** [comment]
try it ethminer-180.ps1 with fixed stratum

**Comment by Quake4** [comment]
Can you check it in latest version?

**Comment by AcharyaOne** [comment]
Still haven't tried on MPH but it gets all shares rejected on nicehash, so it seems not usable which it's a shame because it is open source miner.

**Comment by AcharyaOne** [comment]
nicehash works again with ethminer, maybe it was temporary problem on nicehash side
