### ISSUE TITLE
miniz missing equihash125 to mine zelcash

### ISSUE THREAD

**Issue by AcharyaOne** [Quake4/MindMiner#543]
missing something like 

[AlgoInfoEx]@{ Enabled = $true; Algorithm = "equihash125" }

and

"equihash125" { $alg = "--par=125,4" }

but since you simplified things for gminer maybe you have a better idea of what to change

**Comment by Quake4** [comment]
Remove you gminerxxx.config.txt with error algo names.
Now full names with _5 _7 etc

**Comment by Quake4** [comment]
thanks. fixed
