### ISSUE TITLE
[Bug] CPU power includes GPU power

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#544]
Hi,

When mining with CPU and NVIDIA enabled the power stats for CPU are actually CPU+GPU can you look to resolve this so we can have more accurate profitability readings for CPU?

Thanks.

**Comment by Quake4** [comment]
Screen, pls

**Comment by platinum4** [comment]
<img width="668" alt="before_running_CPU_power" src="https://user-images.githubusercontent.com/6779241/67821221-3d286880-fa8a-11e9-9e30-982c77e0c558.PNG">
<img width="793" alt="combined_power_CPU_GPU" src="https://user-images.githubusercontent.com/6779241/67821222-3d286880-fa8a-11e9-9b0f-08071229f3cc.PNG">

**Comment by platinum4** [comment]
271.7 - 123.9 = 147W which is more like what my CPU was using (I opened HWmonitor late)

**Comment by Quake4** [comment]
No. IA Cores. Error in adding to package power. Ok, today i fix it.
