### ISSUE TITLE
[Bug] API call freezes gminer and ccminer-yescrypt

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#547]
Looks like something causes these two miners to freeze up output or stop hashing when rounds of profitability or power usage are calculated; these miners work individually without MindMiner OK

**Comment by Quake4** [comment]
in this case, MM works and miners closes with the cause of NoHash?

**Comment by platinum4** [comment]
Sometimes but not on a multi-card rig like 6x 1070, the miner box just scrolls down into blackness for gminer and yescrypt miner (all klaust forks); the miner stays open and does not close and then if i can close it manually then MM will continue running afterward, but you have to watch it all the time now to see if it is hanging

**Comment by Quake4** [comment]
is MM window freeze or working normal?

**Comment by platinum4** [comment]
MM Window freezes until miner is closed then MM runs loop like normal; it is during API call to miner that it freezes the miner and does not hash

**Comment by Quake4** [comment]
ol. thanks. il look into it.

**Comment by platinum4** [comment]
Here is best I can provide

![image](https://user-images.githubusercontent.com/6779241/68978872-9f3ed880-07c1-11ea-8061-090f9bfd9ada.png)

**Comment by platinum4** [comment]
The problem is Get-Speed function is unable to connect to remote server and it hangs

**Comment by Quake4** [comment]
Pls, check 24pin+4pin atx power connector from power supply.

**Comment by Quake4** [comment]
enable logging in miner
"ExtraArgs": "-l log.txt",

**Comment by Quake4** [comment]
more like freezes at hardware problems with video cards

**Comment by platinum4** [comment]
Nah I appreciate the concern there but this only happens on grind29 and yescryptr32 all other miners and algos work fine for days without checking

I even ran those two miners at stock values for GPUs and the same issues occur so it's not hardware or OC in my opinion.  Review the "Get-Speed" function please.

**Comment by platinum4** [comment]
[log.txt](https://github.com/Quake4/MindMiner/files/3855327/log.txt)

**Comment by platinum4** [comment]
I can't identify any problem except for stratum interrupts but this behavior happened while mining beam so it's still isolated to gminer right now not any algo

These work fine in miniz/nbminer for hours/days

**Comment by platinum4** [comment]
I got D7 POST code 2x after a reboot so I flattened down the 1x riser part in the main PCIe_x16 slot and am testing now with yescryptr32 in MM

**Comment by platinum4** [comment]
Same happens on Get-Speed it freezes the miner

**Comment by Quake4** [comment]
get-speed freeze is a consequence of the miner's freeze (possible a windows socket/api freeze).
the getspeed request a powershell command with timeout of operation:
``` Invoke-WebRequest $Url -UseBasicParsing -TimeoutSec ($MinerProcess.Config.CheckTimeout)```
CheckTimeout is 5 sec
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Invoke-WebRequest?view=powershell-6

You have a system function hanging, what do you want me to look at? You clearly have a hardware problem, check the risers and the supply power.

**Comment by platinum4** [comment]
<img width="540" alt="2" src="https://user-images.githubusercontent.com/6779241/69031544-f00c2800-099f-11ea-9705-d6bfcdd148e9.PNG">

**Comment by platinum4** [comment]
algo and miners and associated wattages and times ran successfully are above; PSU is AX1500i risers are 2x Molex 4x PCIe I appreciate your concern on the hardware

**Comment by Quake4** [comment]
This only says that the load (confluence of some circumstances) of these programs leads to the occurrence of this error. Yes, the simplest way is not to use them.

**Comment by platinum4** [comment]
Maybe but it's not the PSU nor hardware, so is it a cpu-priority issue for MM or miner itself?  can it be placed as lower or higher to test for ccminer-yescrypt and/or gminer?  yescryptr32 was profitable last week

**Comment by platinum4** [comment]
All yescrypt miners failed due to being the same kind of klausT fork btw; they worked for days uninterrupted without MM doing rounds/nvml calls

**Comment by Quake4** [comment]
add to extraargs in gminer-175.config.txt `--nvml 0` parameter to exclude nvml calls and test it case.

**Comment by Quake4** [comment]
I think it will still freezes.

**Comment by platinum4** [comment]
k i will try it on a day when i can monitor it more instead of have it hang since it hangs at same power draw until closed

**Comment by Quake4** [comment]
fine

**Comment by platinum4** [comment]
looks like grind29 is profitable I will try it now

**Comment by platinum4** [comment]
I had even upgraded the CPU from a 2c/2t to 4c/8t i7 35W chip to see if it was overhead with grin like older miners had when it first released lol

**Comment by platinum4** [comment]
Same stuff just disabled miners; only happens when MM is running though

**Comment by Quake4** [comment]
how about new yescrypt miner?

**Comment by platinum4** [comment]
So fundamentally the problem was the same but I have been experimenting with -lockVoltagePoints in nvidiainspector and I seem to be able to hold stability across this and gminer in grind29 so far; let me experiment a bit but i think it happens on algos with such low gpu heaviness that the core goes to max on the boost clock table even at lowest power limit; causes a spike it doesn't seem to recover from which doesn't show up on -r or -s algos like rvn/pgn

**Comment by platinum4** [comment]
In gminer I enabled power calc and nvml and was able to watch miner it appears cannot use same ethash memory OC freq I backed all cards memclock down and can get some stability going to leave it tonight but I guess cuckarood and yescrypt32 have intensity issues memory-wise; I left gminer at 100 intensity

**Comment by platinum4** [comment]
I ended up moving all risers to other PCIe slots and reseating the risers on the GPUs and now MM functions as normal for over 24 hours; not sure why only certain algos had problems.

**Comment by Quake4** [comment]
ok. fine.
