### ISSUE TITLE
ccminer-klaust-821r9.ps1

### ISSUE THREAD

**Issue by Minerx117** [Quake4/MindMiner#553]
update from v1 to v3 

 +0.02-2% hashrate on 10 series
 +12-22% hashrate on rtx cards  

recommend -i 12.5 for best results 
recommend a high memory OC also +500-750mhz seems to yield best results

https://github.com/Minerx117/ccminer8.21r9-lyra2z330/releases

**Comment by platinum4** [comment]
This was rejected previously.

https://github.com/Quake4/MindMiner/pull/551

@Minerx117 can you rebuild this and yescrypt miner with CUDA 10.2?

**Comment by platinum4** [comment]
-i 13 and -i 13.5 work on 8GB GPUs 1070/2070

**Comment by Minerx117** [comment]
there is no benefit compiling with cuda 10.1/10.2 all that does is limit driver support i have already compiled and tested with cuda10.1 and 10.2 no improvements..
