### ISSUE TITLE
[Bug] NH rejecting all RandomX shares

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#555]
![image](https://user-images.githubusercontent.com/6779241/69910601-a5dd6a80-13d3-11ea-90ce-2eef039675c7.png)

**Comment by platinum4** [comment]
https://old.reddit.com/r/NiceHash/comments/e48hs9/randomxmonero_all_shares_rejected_cpu/f99t2hc/

**Comment by Quake4** [comment]
ok
