### ISSUE TITLE
[Question] On Pools, can we get specified coins paid out to different wallets?

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#557]
Hi,

Do I add wallets to config.txt then in pools config how do I specify when it mines PGN only or x21s to pay me in PGN, and x16rv2 to pay me in RVN, but then all other algos, to pay in LTC?

(Zergpool I guess)

Would it be like this?

{
    "Enabled":  true,
    "AverageProfit":  "45 min",
    "Wallet":  [ "LTC", "x16rv2": "RVN", "x21s": "PGN" ],
    "SpecifiedCoins":  null,
    "EnabledAlgorithms":  null,
    "DisabledAlgorithms":  null
}

**Comment by platinum4** [comment]
Hi

**Comment by Quake4** [comment]
Im think, i set added wallet and specified coin mining running.

**Comment by platinum4** [comment]
OK so we currently cannot do this now but it's something you can add sometime, right?  Since I wouldn't want to autoconvert other algos

**Comment by platinum4** [comment]
Can you show me a working pool config to do what I am asking?

**Comment by Quake4** [comment]
```"SpecifiedCoins": { "X21s": "PGN" }```
Main config
```"Wallet": { "BTC": "xxx", "PGN": "xxx"},```

**Comment by platinum4** [comment]
Hi, I tried this like you typed but it does not work.

SpecifiedCoins is not the same as SpecifiedAlgos

I think you mean to type { "PGN" } or {"PGN": "PGN}

**Comment by Quake4** [comment]
yes its isnt working. im propose this for example.

**Comment by platinum4** [comment]
OK thanks

**Comment by platinum4** [comment]
This might be pointless now that MRR is main source of profitability.

**Comment by Quake4** [comment]
ok
