### ISSUE TITLE
ccminer-alexis-01 problems

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#56]
I have a problem with ccminer-alexis-01 after run
https://user-images.githubusercontent.com/36886126/39400964-13aee846-4b43-11e8-80ff-ff40d426fb21.png
i remove N and R switches, add -d 0 (i have only one GPU)  and everything works fine
Geforce GTX 980

**Comment by Quake4** [comment]
You can try and write what kind of switch leads to this error.

**Comment by g5-freemen** [comment]
Ok, tomorrow

**Comment by slovke** [comment]
Alexis dont work with same oc settings as rest of miners reduce oc its not minde miner switch problem its your oc reduce it and you will see it happens on alexis miner even otside of mind miner tested few times lot of miners that way

**Comment by g5-freemen** [comment]
looks like it need -d switch to correct work at least at my situation. N and R switch have no influence.

**Comment by Quake4** [comment]
Change alexis config add -d switch to common extraargs:
```json
{
    "Algorithms": [ ...
                   ],
    "ExtraArgs": *"-d 0"*,
    "BenchmarkSeconds": 60,
    "Enabled": true
}
```
