### ISSUE TITLE
[Bug] ccminer-verus-3611 does not go to pool

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#561]
Hi, a few of your ccminers have been broken I think since they were copied and pasted but forgot an ending bracket or something

Current ps1 for ccminer-verus does not enumerate site name to connect to, just port; i had to go back and copy and paste an alexis ccminer ps1 and then manually edit it to verus to work

**Comment by Quake4** [comment]
Thanks. Fixed
