### ISSUE TITLE
getting mad with nicehash and nicehashNEW

### ISSUE THREAD

**Issue by smarcello** [Quake4/MindMiner#563]
changed to nicehash wallet with the new wallet and keep getting:

Cannot create object of type "PoolAlgorithmInfo". The Host property was not found for the PoolAlgorithmInfo object. The available property is: [Name <System.String>] , [Info <System.String>] , [InfoAsKey <System.Boolean>] ,
[Algorithm <System.String>] , [Profit <System.Decimal>] , [Protocol <System.String>] , [Hosts <System.String[]>] , [Port <System.Int32>] , [PortUnsecure <System.Int32>] , [User <System.String>] , [Password <System.String>] ,
[Priority <Priority>]
At C:\EFFE\MindMiner\Pools\NiceHashNew.ps1:118 char:85
+ ... ullOrWhiteSpace($Pool_Diff)) { $Pool_Diff } else { $Config.Password }
+                                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ObjectCreationError

Please clarify- old nicehash and new nicehash or what ??

**Comment by Quake4** [comment]
Remove nicehash new

**Comment by Quake4** [comment]
Check actual pools https://github.com/Quake4/MindMiner/tree/master/Pools

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Even with 5.15 I get red lines that NiceHash New is missing....  :(                                                                                                                                             Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 20 dicembre 2019 06:28A: MindMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [Quake4/MindMiner] getting mad with nicehash and nicehashNEW (#563)  Check actual pools https://github.com/Quake4/MindMiner/tree/master/Pools

**Comment by Quake4** [comment]
Delete the nicehashnew.ps1 file in pools folder of mindminer
