### ISSUE TITLE
[Bug] Attempted divide by zero when calc MRR profit on rig

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#565]
Hi, for each rig would we need to have separate API keys?  I don't think so, but I find that after running with MRR enabled it fails to calc profit

![image](https://user-images.githubusercontent.com/6779241/71501208-a6302080-282e-11ea-835f-a1635b2649ea.png)

**Comment by Quake4** [comment]
Thanks. But, strange 0h/s rigs.
Update to 6.2 and remove zero hasrate rigs.

**Comment by Quake4** [comment]
I have 3 rigs running under one apikey and fine

**Comment by platinum4** [comment]
I don't know what the problem is but it's like MM created the rigs and filled all advertised hashrates with zeroes, then it can't read my stats right to pass to MM so they are all zeroes; i tried with 1 key (yes/yes/yes) and 3 keys (yes/yes/yes) and they can create rigs but then they are all zeroes except like maybe 1, yescryptr32 which may be the last alphabetically

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71527528-78d08a80-28a1-11ea-8b1c-fe2d6f451cc6.png)

Do you know if there is problem with us-central?

Can you show me one working please?

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71527723-41aea900-28a2-11ea-8c63-6df70fbdcc98.png)
Is this a problem with the renter's pool?

**Comment by platinum4** [comment]
Why are all these zeroes all the time?

![image](https://user-images.githubusercontent.com/6779241/71539185-aa2b7380-28fe-11ea-9e45-99920c3d8cf4.png)

**Comment by Quake4** [comment]
remove from mrr all rigs with zero hasrate.

**Comment by Quake4** [comment]
Where mm write ¡~= 0.00 h/s

**Comment by platinum4** [comment]
Oh shoot, so I should try and recreate rigs on 6.2?

**Comment by platinum4** [comment]
OK I deleted all my rigs and now this kind of only wants to create one at a time...

**Comment by platinum4** [comment]
OK these rigs seem to create multiples if I disable electricity consumption temporarily

**Comment by Quake4** [comment]
thanks. all fixed in 6.3

**Comment by Quake4** [comment]
Please, post screen with `mrr: online xxx`

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71561152-62a90280-2a38-11ea-85c5-4422c1a00aef.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71561845-ba983700-2a41-11ea-8078-7030f17a541d.png)

You also have a very wide range in pricing, and not updating pricing frequently enough
See your other 2 MindMiner rigs here and the difference in pricing

**Comment by platinum4** [comment]
You have one priced at .00006000 and the other priced at .12843600 with no real adjustments happening when I am watching these other rigs; this is also causing mine to not get rented since you are setting the price too high

**Comment by Quake4** [comment]
Yes. Its bug. I think wrong khash to mhash conversion's.
