### ISSUE TITLE
Mrr: Wrong pricing conversions

### ISSUE THREAD

**Issue by Quake4** [Quake4/MindMiner#567]
![image](https://user-images.githubusercontent.com/6779241/71561845-ba983700-2a41-11ea-8078-7030f17a541d.png)

You also have a very wide range in pricing, and not updating pricing frequently enough
See your other 2 MindMiner rigs here and the difference in pricing

_Originally posted by @platinum4 in https://github.com/Quake4/MindMiner/issues/565#issuecomment-569536142_

**Comment by platinum4** [comment]
idk whats wrong because MTP was working for me for a few days I already caught 5 rentals earlier and have a current rental now

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71583349-aa309c80-2ad3-11ea-85e3-edd73ff4f61e.png)

Nobody will rent rigs at this price and they keep increasing the price...

**Comment by platinum4** [comment]
single GPU asking for $10/day...

**Comment by Quake4** [comment]
Please, send same screen again.

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71594255-d3195780-2afc-11ea-8d83-3049f658f6a3.png)

**Comment by platinum4** [comment]
It is mining Neoscrypt for $0.03/day and asking for $10/day for other algos on MRR...

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/71595627-0ca09180-2b02-11ea-97b4-c14fa9e035dc.png)

**Comment by Quake4** [comment]
Blake2b your rig is created as 700mh. Target profit 80к. You is create rig with wrong hashrate. You mast change hashrate and price of your rig.
![20191230_215829](https://user-images.githubusercontent.com/29517243/71596375-5748fa80-2b50-11ea-96ba-948961de19c5.jpg)

**Comment by Quake4** [comment]
first you need to pass all the speed tests, then turn on the mrr and create rigs.

**Comment by platinum4** [comment]
Check now, most are fixed, but how often will prices update?

![image](https://user-images.githubusercontent.com/6779241/71597540-3ad59f80-2b09-11ea-9036-6d069739565c.png)

**Comment by platinum4** [comment]
Will this update hashrates as they are run I don't get it, and why are 6 card rigs asking for 18 dollars per day

**Comment by Quake4** [comment]
The price update is executed every hour to decrease percent parameter if algorithm isn't rented.
If you change speed from low to high, you must change price from high to low to you target rig profit. 1% decrease profit every not rented hour, its very long time. lower to 50% its grater than 2 days.

**Comment by platinum4** [comment]
can we configure it to run at more update intervals than Rate Time equalling 1hr?

**Comment by Quake4** [comment]
No. You can change decrease percent.

**Comment by Quake4** [comment]
https://github.com/Quake4/MindMiner/blob/master/Config.md#miningrigrentals-mrr

**Comment by platinum4** [comment]
Is there a way to have it find the lowest price on MRR and set it to 95% of that price so it will always be on top on MRR to rent instead of down below others

**Comment by Quake4** [comment]
On rig create, mm get last10 price value.

**Comment by platinum4** [comment]
Yeah but what if it's already created I think that's the problem, these were created and are now a day or two old and the price keeps skyrockets, can it get FIRST10 not LAST10 since LAST10 is the most expensive?

**Comment by Quake4** [comment]
No in api data. https://www.miningrigrentals.com/api/v2/info/algos

**Comment by platinum4** [comment]
OK what is suggestion for all these badly priced rigs how do i fix them going from increasing?

**Comment by Quake4** [comment]
You must fix manually or wait while decrease percent do it.

**Comment by Quake4** [comment]
you did it yourself. created a rig with the wrong speed, then Isabeli speed, and the price to fix forgot.

**Comment by Quake4** [comment]
0.733 gh at 80k profit = 110k price
2.2gh at 80k profit = 35k price
Its two different prices

**Comment by platinum4** [comment]
You just took a picture of it saying 733M not G

**Comment by platinum4** [comment]
All these rigs were created via API I had deleted all the other rigs and let 6.2 re-make every one of them (93)

**Comment by platinum4** [comment]
I think I have this resolved it was just increasing way too fast based on default mrr pools config parameters; you are probably OK to close this

**Comment by Quake4** [comment]
In 6.5 fixed 2-3 errors. Possible, its fixed.

**Comment by Quake4** [comment]
add fix to 10x max profit
