### ISSUE TITLE
claymore-dual error

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#57]
![image](https://user-images.githubusercontent.com/36886126/39724530-b19eda9c-5251-11e8-9bfe-9816a5a579c7.png)
![image](https://user-images.githubusercontent.com/36886126/39724624-ee4215b8-5251-11e8-94a3-7faa38b47efd.png)
![image](https://user-images.githubusercontent.com/36886126/39724640-fd4b750e-5251-11e8-80fd-6500b72f85a7.png)

![image](https://user-images.githubusercontent.com/36886126/39724697-2cbbe5bc-5252-11e8-838a-a4af3e311a05.png)
![image](https://user-images.githubusercontent.com/36886126/39724703-301fdace-5252-11e8-87f8-b7a307be1862.png)

**Comment by Quake4** [comment]
Thanks, try:
Reset cards from overclock to default and retest.
Claymore reqirement:

TESTED NVIDIA DRIVERS (other versions are untested, they can be worse or better):
9xx cards in Windows 7 x64: just use latest/recent drivers from Nvidia website (for example, 368.81). Note that latest 372.54 is slower than 368.81.
9xx cards in Windows 10 x64: you have to use old drivers (for example, 352.xx) and miner built for cuda6.5

**Comment by Quake4** [comment]
Claymore miner suppot thread: https://bitcointalk.org/index.php?topic=1433925.23780
