### ISSUE TITLE
[Question] Can I specify Yescryptr32/x16rv2 to calc hashrates only every 5 or 10 minutes?

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#570]
Hi, for Yescryptr32 it takes awhile for 6 card rig to get to full speed, and because of this, it is always about 70% in stats file of total hashrate (2Kh/s hashrate, stats will read 1.45Kh/s)  This happens because it takes first few rounds of hashrates too often.  I tried changing setting in config to 300s but it did nothing really, plus, I only want to lengthen hashrate calc time for two algos, can this be done?

**Comment by Quake4** [comment]
Is you change `BenchmarkSeconds` to 300 for Yr32?

**Comment by platinum4** [comment]
Yes the benchmarking works fine at 300 seconds I mean when it's actually mining

**Comment by Quake4** [comment]
did you leave 300 seconds after the benchmark?

**Comment by platinum4** [comment]
Where?  What setting?  Can you show me in code and what file?

**Comment by Quake4** [comment]
Any miner have config...
You can change BenchmarkSeconds for all miner or each algo of miner.
```{
    "Algorithms":  [
                       {
                           "ExtraArgs":  null,
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "yespower"
                       },
                       {
                           "ExtraArgs":  null,
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "yespowerr8"
                       },
                       {
                           "ExtraArgs":  null,
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "yespowerr16"
                       },
                       {
                           "ExtraArgs":  null,
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "yespowerr24"
                       },
                       {
                           "ExtraArgs":  null,
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "yespowerr32"
                       }
                   ],
    "ExtraArgs":  null,
    "BenchmarkSeconds":  120,
    "Enabled":  true
}
```

**Comment by platinum4** [comment]
That is just for benchmarking I am talking about actual mining, yescryptr32 can take up to 5-10 minutes to get to full speed as it loads GPUs up

**Comment by Quake4** [comment]
the reading of the miner's speed occurs before the end of benchmarkseconds
