### ISSUE TITLE
[Enhancement] Try and pull MRR profitability from minerstats

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#571]
Hi, I see a few other algos like GRIMM and AION we could be mining but they are not on yiimp/yaamp pools so we never get an API call for profitability, can you poll a profitability site that lists mrr?

**Comment by platinum4** [comment]
You could also add option to create another rig for these two:

x16rt veil / x16rt gin
equihash 150,5 beam / equihash 150,5 grimm

Currently only veil and beam rigs get made, leaving behind gin and grimm

**Comment by Quake4** [comment]
veil fixed. no grimm pool -> no benchmark -> no mrr rig.
