### ISSUE TITLE
[Bug] MRR Failed to create Veil rig

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#573]
![image](https://user-images.githubusercontent.com/6779241/72210408-83ce1200-3480-11ea-9953-95baff2e5336.png)

**Comment by platinum4** [comment]
success is spelled with 2 c's btw

**Comment by Quake4** [comment]
Yes, sometimes requests are not executed. Its normal.

**Comment by platinum4** [comment]
lmao how would you mark this wontfix when it stops up creation of all other rigs

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/72210818-a6632980-3486-11ea-9f42-c5aac54cc49d.png)
Tried on 3 rigs now

**Comment by Quake4** [comment]
fixed

**Comment by platinum4** [comment]
Of course no worries at all, thanks again for your hard work.
