### ISSUE TITLE
[MRR] Veil rig still not creating

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#575]
![image](https://user-images.githubusercontent.com/6779241/72211130-8a15bb80-348b-11ea-8c43-294d7cece712.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/72211134-9ac63180-348b-11ea-91c1-32d167c1cd78.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/72211137-a9144d80-348b-11ea-8706-3d680855e6b3.png)

**Comment by platinum4** [comment]
I don't think this is resolved actually, when I check my MRR.config I have Veil disabled currently.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/72222535-df7ac700-3576-11ea-857a-4893def0219e.png)

**Comment by Quake4** [comment]
fixed. thanks
