### ISSUE TITLE
[MPH] Map "Ethereum" to "ETH" so no double balances in Full Verbose with ShowBalances true

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#576]

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/72214947-e7ccf680-34d1-11ea-9fc6-0d818e5a53be.png)

**Comment by platinum4** [comment]
Ethereum should not be displayed since ETH is already, or vice versa whichever, but can the double part be cleared?  I have "ETH": "" as wallet in Config so I could pull the rates and study them daily

**Comment by Quake4** [comment]
and where did etherium come from?

**Comment by platinum4** [comment]
"Ethereum" is being pulled from balance on MPH

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/72215952-1225b080-34e0-11ea-953c-ddc2714df533.png)

**Comment by Quake4** [comment]
ok
