### ISSUE TITLE
[MRR] Continue to calculate rig profitability during active rental contracts, and continue to update pricing during active rental contract, since people can buy extensions

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#579]
Hi, I noticed when a rental is active basically all calc activity of profitability stops during that time.  This will leave rig at same pricing but it could adjust upward if needed so when customer buys extension it is more representative of profit I want instead of cheap price for customer since it never moves while calc is frozen for 12 hours of renting

**Comment by platinum4** [comment]
Also when currently rented, the MRR.config does not update the min / max hours

**Comment by Quake4** [comment]
I can add code to disable extensions.

**Comment by Quake4** [comment]
I cant update price during rent time, only after. For it needed is save point.
I don't want to store rental data.

**Comment by Quake4** [comment]
?

**Comment by platinum4** [comment]
Yeah you're OK to close this.

**Comment by Quake4** [comment]
Are you satisfied with the current algorithm or what?

**Comment by platinum4** [comment]
Yes I like keeping extensions, do not change anything please.

**Comment by Quake4** [comment]
Ok
