### ISSUE TITLE
[Bug] [MRR] MaxHours is capped at 120, when entering 336, rigs are created at Max Hours 120

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#581]
OK I found the code in MRR.ps1 and removed it; you should set that limit to 672 though as a hard cap like when you set profit hardcap to 899

**Comment by Quake4** [comment]
I think that giving up for more than 5 days (120 hours) is unreasonable.  a lot can change.  and increasing the profit will not work. the total profit increase is 1000% or 10x. limitation from errors.

**Comment by platinum4** [comment]
This is fine for general use since I can always just delete the if statement if I want to go longer. Thanks.
