### ISSUE TITLE
[MRR] Disable Blake2b by default, ccminer does not mine Blake2b-SIA

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#582]

**Comment by Quake4** [comment]
where is blake2bsia pool?

**Comment by platinum4** [comment]
When people rent on MRR it is incompatible, MRR has Blake2b-SIA listed only

**Comment by Quake4** [comment]
so that's what needs to be fixed.
which miners mine sia?

**Comment by platinum4** [comment]
None do, but ccminer-tpruvot-231f mines Blake2b (non-SIA) on Zergpool, that is why we have an entry in /Stats folder under ccminer-tpruvot-231f.txt

Needs to be disabled by default in MRR.config

**Comment by platinum4** [comment]
ccminer-verushash-361 also does not work with MRR it connects endlessly and has an error message in the miner that it needs to support redirecting

**Comment by Quake4** [comment]
ccminer-verus-3611f.ps1?

**Comment by platinum4** [comment]
Yeah but that is a problem with the ccminer itself, I think monkins would need to rebuild it or nemosminer; I left as disabled in MRR.config

**Comment by platinum4** [comment]
this https://github.com/Quake4/MindMiner/commit/d834a7411f2637a0bf00dd561b2530eff591c802 does not fix the problem, running CCminer with -a sia is not Siacoin, it's another one.  Blake2b-SIA is the only Siacoin algo and no GPU miners we have do it

**Comment by platinum4** [comment]
Is best to just disable Blake2b in MRR.config I found no way to trick the rental I had into mining what it wanted.

**Comment by Quake4** [comment]
this do fix, sia is disabled algo

**Comment by Quake4** [comment]
```		$AllAlgos.Add("Disabled", @("beam", "bitcore", "sha256", "sha256t", "sha256asicboost", "sha256-ld", "scrypt", "scrypt-ld", "x11", "x11-ld", "x13", "x14", "x15", "quark", "qubit", "myrgr", "lbry", "decred", "sia", "blake", "nist5", "cryptonight", "cryptonightr", "cryptonightv7", "cryptonightv8", "cnheavy", "cnsaber", "x11gost", "groestl", "equihash", "lyra2re2", "lyra2z", "pascal", "keccak", "keccakc", "skein", "tribus", "c11", "phi", "timetravel", "skunk"))
```

**Comment by platinum4** [comment]
Oh in MindMiner.ps1 I got it ty

**Comment by platinum4** [comment]
OK I would close this and leave Verushash alone if that's another issue it will be separate

**Comment by Quake4** [comment]
```ccminer-verushash-361 also does not work with MRR it connects endlessly and has an error message in the miner that it needs to support redirecting```
Next time, please send a screenshot of miner and on MRR press button:
![image](https://user-images.githubusercontent.com/29517243/72424481-247d4400-3797-11ea-96c0-8423a4ea0ccb.png)
