### ISSUE TITLE
[MRR] Map Grin29 to Cuckaroo C29 (Not-Grin) | Map Grind29 to Cuckaroo C29D (Grin)

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#583]

**Comment by Quake4** [comment]
???
"equihash96" { $coin = "--coin MNX" }

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/72426245-fffd7980-374e-11ea-9379-aabb5ffd62aa.png)

**Comment by Quake4** [comment]
need peers value right  mine

**Comment by platinum4** [comment]
I don't understand what you said but I cannot find anything except a Marscoin from 2014 on scrypt back when there was only 2 algos to mine

**Comment by platinum4** [comment]
https://github.com/Quake4/MindMiner/issues/583

**Comment by Quake4** [comment]
is dead
https://www.investing.com/crypto/marscoin/mars-btc

**Comment by platinum4** [comment]
If I get bored I will ask merc82 what that is later.

**Comment by platinum4** [comment]
Why can't you just add this mindminer.ps1 I have to add this manually every update @Quake4

**Comment by platinum4** [comment]
Fix this, very simple.  Not sure why you do not want to.

**Comment by platinum4** [comment]
I asked MRR to disable algo
