### ISSUE TITLE
"Need bench"

### ISSUE THREAD

**Issue by sawyeregumbrell** [Quake4/MindMiner#585]
xmrigcpu and xmrignvidia has the message that need to bench
How to fix it?
https://prnt.sc/qmyew0

And i dont see RandomX algo. Where is it?

**Comment by Quake4** [comment]
Enable the pool with this algorithm. (zerg)

**Comment by sawyeregumbrell** [comment]
> Enable the pool with this algorithm. (zerg)

Thanks
Can you tell me how to do it, please?

**Comment by Quake4** [comment]
pls, read it
https://github.com/Quake4/MindMiner/blob/master/Config.md

Pools\ZergPool.config.txt => Enabled => true
```{
    "AverageProfit":  "3 hour",
    "SpecifiedCoins": null,
    "EnabledAlgorithms":  null,
    "PartyPassword":  "win",
    "DisabledAlgorithms":  null,
    "Enabled": true
}```

**Comment by Quake4** [comment]
did it work?
