### ISSUE TITLE
possible to give automaic reply?

### ISSUE THREAD

**Issue by smarcello** [Quake4/MindMiner#589]
hey,
is it possible to give ALL Yes reply to programs questions?

**Comment by Quake4** [comment]
`Do you want to mine all time to MM wallet?` Yes ;)
really is it needed?

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Right. When new rig is proposed, program stops till I press Y or N......                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 15 gennaio 2020 22:56A: MindMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [Quake4/MindMiner] possible to give automaic reply? (#589)  Do you want to mine all time to MM wallet? Yes ;)
really is it needed?

**Comment by Quake4** [comment]
while the speed is being determined on the new rig, it is better to disable the mrr. since the rig will not be created at full speed due to the fact that there are usually several miners per algorithm, and the creation goes according to the first, and not the fastest.

**Comment by Quake4** [comment]
need remove question before all isnt benchmarked

**Comment by Quake4** [comment]
fixed
