### ISSUE TITLE
цикличный апдейт

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#59]
ты что то накосячил, прога уходит в цикличный апдейт и всё без конца . на обоих компах

**Comment by Quake4** [comment]
сорри, пара минут

**Comment by Quake4** [comment]
Прошу прощения, не ушел один масенький коммит, не уследил.

**Comment by Quake4** [comment]
Как впечатления от программы в целом?

**Comment by danik-guitar** [comment]
всё чики пуки ))

**Comment by Quake4** [comment]
спасибо.
