### ISSUE TITLE
[Bug] unzip gminer to broken file

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#591]
Hi, I cannot run gminer because there is a problem in MinerProcess.ps1 can you fix it please

![image](https://user-images.githubusercontent.com/6779241/72660099-7fc55700-398e-11ea-8c4d-45cf01023218.png)

**Comment by platinum4** [comment]
I think it is a corrupt unzip maybe can you update 7zip version

**Comment by platinum4** [comment]
I can't get this to run on a rig with a single 1070, but it works on a rig with a single 2070

**Comment by Quake4** [comment]
need check errors after unzip

**Comment by Quake4** [comment]
possible, fixed
