### ISSUE TITLE
6.19 stucked !

### ISSUE THREAD

**Issue by smarcello** [Quake4/MindMiner#593]
6.19 stucks with:
Pool(s) request ...

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/72755913-b690ac80-3bdc-11ea-85c2-b36c4ba97554.png)
one of the pools is not responding. check the information about the pools in full verbose level (V).
zerg answer and process 10 seconds
zpool answer and process 14 seconds

**Comment by smarcello** [comment]
6.20 still stucked with pool request. Haven't changed nothing in my config !

**Comment by smarcello** [comment]
sure cannot check the full verbose level V in this condition...

**Comment by Quake4** [comment]
disable all pools. turn on one at a time (from nice/zerg/z)

**Comment by Quake4** [comment]
pools -> xxx.config.txt => enabled => false

**Comment by Quake4** [comment]
if pool isnt answer, pools request can take over 5-7 minutes to run. its normal
check api requests in browser

**Comment by Quake4** [comment]
you can lower pools request if `ShowBalance` switch to false.

**Comment by Quake4** [comment]
if you have more than 3 rigs, you must use master/slave scheme to prevent pool ddos and block your request to pools.

**Comment by Quake4** [comment]
clear your dns cache cmd from admin: `ipconfig /flushdns`

**Comment by Quake4** [comment]
figured it out?

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Not yet, at work now. Followed all instructions but got a red no pool's! Will take a look again in this afternoon. Thanks!                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 21 gennaio 2020 06:36A: MindMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [Quake4/MindMiner] 6.19 stucked ! (#593)  figured it out?

**Comment by Quake4** [comment]
after disable all pools. you need enable one by one pools to find it pool with freeze.

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Reinstalled from the beginning, seems to work now.                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 21 gennaio 2020 09:02A: MindMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [Quake4/MindMiner] 6.19 stucked ! (#593)  Closed #593.

**Comment by Quake4** [comment]
blockmasters had problems yesterday. Most likely, you have it turned on.
