### ISSUE TITLE
[MRR] Are you sure you fixed MRR pricing with ElectricityConsumption true?

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#596]
Why is the pricing or profit like 10x the current mining highest profitability?

![image](https://user-images.githubusercontent.com/6779241/72880825-3e51e600-3cc5-11ea-8884-b2eebb2768fa.png)

**Comment by platinum4** [comment]
RawProfit is like 200% over the current highest mining profitable algo

**Comment by Quake4** [comment]
How many Target you set? 100? Vds and grimmrigs you are created manually and set your price. Price is lower 10x. All fine.

**Comment by platinum4** [comment]
Target was 10, and then 5

**Comment by Quake4** [comment]
Decrease?

**Comment by platinum4** [comment]
"Target":  5,
    "MinHours":  3,
    "Enabled":  true,
    "Increase":  1,
    "MaxHours":  120,
    "DisabledAlgorithms":  [
                               "Verushash",
                               "Yescrypt",
                               "Blake2b"
                           ],
    "Decrease":  1,

**Comment by Quake4** [comment]
How many hours does it take for the rig's profit to drop by 20% at 1% per hour?

**Comment by platinum4** [comment]
Where do you see 20 in any setting?

**Comment by Quake4** [comment]
This is a question of your understanding of the situation.

**Comment by platinum4** [comment]
I don't think you've fully explained what is going on in the config.md

**Comment by platinum4** [comment]
If there is 5% target and 1% increase and decrease then there should be 5 reprices, in 5 hours

**Comment by Quake4** [comment]
No. 5 hours - 4.9% (100 * 0.99 * 0.99 * 0.99 * 0.99 * 0.99)
20% - 23 hour
You set Target 100% - MM update all prices to maximum profit +100% (Cuckaroom + 100% = honeycomb from your screen 17K * 2 = 34K)
Yus set VSD, Grimm manually price above target 100%.

Lower prices to Target 5% from it values by 1% more than 3 days.

**Comment by platinum4** [comment]
I didn't set a target of 100% it was 5% though; I removed the Grimm/Vds rigs

**Comment by Quake4** [comment]
update to latest version and set decrease to 5%, and see that everything works out correctly.
