### ISSUE TITLE
[MRR] Issue adding Cuckaroom rig

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#598]
![image](https://user-images.githubusercontent.com/6779241/72969178-97d01880-3d8a-11ea-8d0e-7813365b2afd.png)

**Comment by Quake4** [comment]
try on latest version

**Comment by platinum4** [comment]
that was on 6.25 already, and I just tried again; same thing

**Comment by platinum4** [comment]
OK I deleted and re-added it went away

**Comment by Quake4** [comment]
what did you delete?

**Comment by Quake4** [comment]
?

**Comment by platinum4** [comment]
I had deleted a Cuckaroom rig and then let it re-add; the Cuckaroom rig was the one with the password 'x'

**Comment by Quake4** [comment]
incomprehensible error, we hope that it will not happen again

**Comment by platinum4** [comment]
yes it was created somehow but then unaccessible due to converting to decimal error
