### ISSUE TITLE
error on 6.26

### ISSUE THREAD

**Issue by smarcello** [Quake4/MindMiner#599]
Get-Speed claymore-eth-150 error: Exception calling "ReadLine" with "0" argument(s): "Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by Quake4** [comment]
did the miner work? or hung? or did it end with an error?

**Comment by smarcello** [comment]
end with an error but after several tries it quit!

**Comment by smarcello** [comment]
got again:
Get-Speed claymore-neoscrypt-12 error: Exception calling "ReadLine" with "0" argument(s): "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host." 
nothing else happened, system continues....

**Comment by smarcello** [comment]
In the miner window I find:
WATCHDOG: GPU 1 hangs in OpenCL call, you need to restart miner :(
but it continues to find shares

**Comment by platinum4** [comment]
claymore-neoscrypt-12 requires basically power limit to be near max for AMD and you probably are not stable on clocks.

**Comment by Quake4** [comment]
Deal with the miners.

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Very strange that I have no earnings from miningpoolhub. With another miner program, I used to have weekly earnings. How can I check that Mindminer actually mines there? Thanks, Marcello                                                                                                                                             Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 26 gennaio 2020 20:56A: MindMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [Quake4/MindMiner] error on 6.26 (#599)  Closed #599.

**Comment by Quake4** [comment]
balance page and pool transactions page
