### ISSUE TITLE
[MRR] gminer-196 not working on Equihash192

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#600]
Hi, please fix this!  lolminer is TERRIBLE

**Comment by platinum4** [comment]
You have some line of code excluding this from pool MRR in the ps1

**Comment by Quake4** [comment]
I don't understand what you want.

**Comment by platinum4** [comment]
You add this:

https://github.com/Quake4/MindMiner/commit/ee823ae8764fd50411d57ba1a9aeddedea35a23f

Now gminer-192 does not mine on MRR when rented, only miniZ/lolminer

**Comment by Quake4** [comment]
erase what i'm added and see what happens

**Comment by platinum4** [comment]
I already tried this it does not work.

Why close an issue you haven't confirmed yet.

**Comment by Quake4** [comment]
Gminer isnt work on mrr on eq192

**Comment by platinum4** [comment]
Why not?  pers=AUTO?

**Comment by Quake4** [comment]
See call string in mm window

**Comment by platinum4** [comment]
idk I can't load it when it is rented because it's disabled

**Comment by platinum4** [comment]
It's OK miniZ is fast enough, lolminer is awful I just disable, only was useful for R9 290X
