### ISSUE TITLE
[MRR] [Add Feature] Split rig types for CPU and GPU, for example, Verushash

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#607]

**Comment by Quake4** [comment]
Its splitet

**Comment by Quake4** [comment]
On one rig

**Comment by platinum4** [comment]
No that all goes on one rig what if my GPU is already rented and I want to rent Verushash on CPU, I can't

**Comment by platinum4** [comment]
Same problem with Yescryptr32, Yescryptr16, and RandomX, RandomSFX

**Comment by Quake4** [comment]
disable verus on gpu

**Comment by Quake4** [comment]
there is no sense, because no one will take the price of the gpu, since the price of the cpu is 3 times lower.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/73423120-3d135f80-433c-11ea-8a34-c06482d3eac3.png)

**Comment by Quake4** [comment]
by default, i disable sfx on gpu it is for this reason

**Comment by Quake4** [comment]
```I want to rent Verushash on CPU```
run two MM, separate for gpu and cpu with different worker names

**Comment by platinum4** [comment]
haha I found something too hard to code finally!  all is good sir ty

**Comment by Quake4** [comment]
This is not hard, I initially started doing this, but changed it to the version that is now.

**Comment by platinum4** [comment]
Yeah it just seems this would be helpful for the YescryptR8/16/32 and Verushash algos since they have their own types of profitability
