### ISSUE TITLE
[MRR] Disable miniZ/BeamV2 by default, not work on MRR

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#610]

**Comment by Quake4** [comment]
No map beamv2 on mrr. Only beam.

**Comment by platinum4** [comment]
Whatever it is miniZ does not work for MRR BEAM rentals, disable and use gminer

**Comment by platinum4** [comment]
I will try add stat for Equihash210 instead of Aion and see if it pulls

**Comment by Quake4** [comment]
Ok
