### ISSUE TITLE
[MRR] Fix map for Aion whatever you did doesn't catch it on MRR API

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#611]

**Comment by Quake4** [comment]
What?
https://www.miningrigrentals.com/api/v2/info/algos

**Comment by platinum4** [comment]
What you are showing me just proves your point, you are mapping it to something that doesn't exist

![image](https://user-images.githubusercontent.com/6779241/73611685-e317d180-45a9-11ea-9b7e-1ef4f208fa42.png)

**Comment by platinum4** [comment]
You need map equihash2109 = aion and then miniZ will work; then you need fix whatever mapping you were trying on lolminer

Or just archive lolminer it sucks.

**Comment by Quake4** [comment]
Remove config in miniz

**Comment by Quake4** [comment]
No aion in miniz

**Comment by platinum4** [comment]
LMFAO why are you not accepting any suggestions dude, I had this working just fine on 6.27 before you tried to map

![image](https://user-images.githubusercontent.com/6779241/73611869-270bd600-45ac-11ea-90aa-ff0e8b98dc71.png)
![image](https://user-images.githubusercontent.com/6779241/73611878-3c810000-45ac-11ea-9fa6-bf3098115172.png)
Aion clearly works on miniZ

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/73611887-57ec0b00-45ac-11ea-9114-1761e9e11ea2.png)

**Comment by platinum4** [comment]
"equihash210" { $alg = "--par=210,9" } in miniz-15t.ps1 needs a better map

**Comment by platinum4** [comment]
OK I got it working, I need change what it's called in miniZ.config.txt since I had build miniz-15t before you ended up updating it

![image](https://user-images.githubusercontent.com/6779241/73611997-730b4a80-45ad-11ea-85a7-14b8f77c2b73.png)

**Comment by Quake4** [comment]
Ok
