### ISSUE TITLE
[Feature Request] MWC Coin

### ISSUE THREAD

**Issue by ToniG123** [Quake4/MindMiner#619]
Seems to be most profitable coin on nVidia at the moment as reported by whattomine.com

info at https://www.mwc.mw/miners

I guess we would need MindMiner to support icemining pool:

https://icemining.ca/

**Comment by platinum4** [comment]
This is being taken care of with Nicehash or MRR on Grind29

**Comment by ToniG123** [comment]
Sure, my rig is mining on nicehash, but MWC seems to have an edge on profitability and mindminer is ignoring it. Heres profitability as reported by whattomine:

![image](https://user-images.githubusercontent.com/3064655/74131504-b6386f80-4be4-11ea-966f-2dd616884520.png)

**Comment by platinum4** [comment]
Understood, icemining is not a profit-switching pool so doesn't report profitability like the other yiimp pools do

**Comment by ToniG123** [comment]
How about FrostyPool?

https://mwc.frostypool.com/

**Comment by platinum4** [comment]
That looks like a nomp-type pool like suprnova it requires a login and does not profit switch

**Comment by ToniG123** [comment]
Too bad. I guess I'd have to manual mine while MWC is most profitable. Thanks for the explanations.

**Comment by platinum4** [comment]
Yes you would have to mine and sell daily to meet that profitability, or choose to hold speculatively.

**Comment by Quake4** [comment]
Yes. The MM is support only autoexchange pools.
