### ISSUE TITLE
 AMD Radeon RX 580 crashed!

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#62]
the AMD Radeon RX 580 graphics card constantly fails on most algorithms!

win 10 ent x64 + last amd drivers
![miner-error1jpg](https://user-images.githubusercontent.com/18327150/40292346-738a9f66-5cd3-11e8-99bd-fd7cf54b9b70.jpg)

**Comment by Quake4** [comment]
Remove overclock and try again.

**Comment by BARUCHER777** [comment]
Overclock not activated!9:32, 21 мая 2018 г., Oleg Samsonov <notifications@github.com>:Remove overclock and try again.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


Best%20regards%2C%20from%20me%21

**Comment by Quake4** [comment]
Go to support clyamore neoscrypt miner thread:
https://bitcointalk.org/index.php?topic=3012600

**Comment by BARUCHER777** [comment]
all other algorithms work normally, the problem is only with the claymore

**Comment by Quake4** [comment]
So ask Claymore. MindMiner only launches the miners.
