### ISSUE TITLE
[MRR] Correct mapping to cryptonightupx = Cnupx

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#624]

**Comment by platinum4** [comment]
"cryptonight_upx" = "Cnupx"
			"cryptonightupx" = "Cnupx"

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/74586668-73451600-4faf-11ea-9057-24c4451cf680.png)

**Comment by platinum4** [comment]
This doesn't work with MRR 
![image](https://user-images.githubusercontent.com/6779241/74591719-e2d2f980-4fdf-11ea-9879-adde779adabf.png)

**Comment by Quake4** [comment]
?

**Comment by platinum4** [comment]
This works I had to redo my statistics file but this works, leave it alone.
