### ISSUE TITLE
[MRR] Map cnzls cnconceal cnfastv2 bl2bsha3

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#626]
"cryptonotev8zls" = "cnZls"
			"cnzls" = "cnZls"
			"cnconceal" = "cnConceal"
			"cryptonotec" = "cnConceal"
			"cryptonotextl" = "cnFastV2"
			"cnfast2" = "cnFastV2"

**Comment by platinum4** [comment]
"cryptonotextl" = "cnFastV2"
			"cnfast2" = "cnFastV2"

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/74599275-d1700880-5044-11ea-9522-40c77e46c633.png)

**Comment by Quake4** [comment]
thanks ;) 
![image](https://user-images.githubusercontent.com/29517243/74605083-8f42d780-50d5-11ea-8473-a82cce77433b.png)

**Comment by platinum4** [comment]
No problem, I was able to catch a Cuckarood29v rental myself as well, I made these other cn rigs when I had a cngpu rental so I figured if there's nothing to shop for then there's no way a person could rent it for me, so I started seeing what other algos I could get to work by adding stats for them and creating manual rigs then adding lowest price and letting MM reprice it

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/74605136-b1fbce80-508a-11ea-920a-19441a76c08c.png)

**Comment by platinum4** [comment]
[cnbatfiles.zip](https://github.com/Quake4/MindMiner/files/4209775/cnbatfiles.zip)
4 bat files for cn algos you can benchmark with (not my mining address, I think they go to a youtuber called Kire)
