### ISSUE TITLE
[question] nvidia-smi issue

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#627]
latest MM , and driver , i noticed that after reboot im getting red warning about nvidia-smi. I run query manually and come up with following

nvidia-smi.exe  --query-gpu=gpu_name,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,clocks.current.graphics,clocks.current.memory,power.default_limit --format=csv,nounits
name, utilization.gpu [%], utilization.memory [%], temperature.gpu, power.draw [W], power.limit [W], fan.speed [%], clocks.current.graphics [MHz], clocks.current.memory [MHz], power.default_limit [W]

GeForce RTX 2080 Ti, 100, 37, 56, 228.82, 210.00, 56, 1560, 6800, [Unknown Error]

for some reason it started to error out on power.default_limit , ideas where to look for fix ?

**Comment by Quake4** [comment]
Is you run smi from bin folder or from `ProgramFiles\NVIDIA Corporation\NVSMI\nvidia-smi.exe`?

**Comment by mo35** [comment]
yes from prog files , driver ver 442.19

**Comment by Quake4** [comment]
set to 100 if it error
