### ISSUE TITLE
[MRR] Map rx/wow cn/double rx/loki cn/rwz sha3

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#628]
!"sha3" = "Keccak"
			!"cryptonotewow" = "RandomWOW"
			!"rx/wow" = "RandomWOW"
			!"randomwow" = "RandomWOW"			
			"cryptonotev8d" = "cnXcash"
			"cn/double" = "cnXcash"			
			!"cryptonightrxl" = "RandomXL"
			!"rx/loki" = "RandomXL"
			!"randomxl" = "RandomXL"
			"cryptonight_rw" = "cnReverseWaltz"
			"cn/rwz" = "cnReverseWaltz"

**Comment by platinum4** [comment]
"cryptonotev8d" = "cnXcash"
			"cn/double" = "cnXcash"

**Comment by platinum4** [comment]
"cryptonightrxl" = "RandomXL"
			"rx/loki" = "RandomXL"
			"randomxl" = "RandomXL"

**Comment by platinum4** [comment]
"cuckoocycle32" = "Grin32"

**Comment by platinum4** [comment]
"cryptonight_xeq" = "CryptonightGPU"

**Comment by platinum4** [comment]
"nscryptv" = "Verium"
			"scryptn2" = "Verium"

I cannot get MRR or Zergpool to see this however, please fix

**Comment by Quake4** [comment]
added
