### ISSUE TITLE
Get-PoolInfo

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#639]
![image](https://user-images.githubusercontent.com/6779241/75141263-361b0b00-56b6-11ea-9f8d-3d00262cca22.png)

**Comment by Quake4** [comment]
You write mapping of two algo from one pool to one algo at one pool.

**Comment by platinum4** [comment]
I think I fixed by Disable Blake2b on MRR config

**Comment by Quake4** [comment]
it mapping:
"cryptonight_xeq" = "CryptonightGPU"

**Comment by Quake4** [comment]
"cryptonight_xeq", "cryptonight_gpu" to "CryptonightGPU"
