### ISSUE TITLE
DelosMiner 1.1.2

### ISSUE THREAD

**Issue by centreece** [Quake4/MindMiner#66]
> optimized for BitCore, HMQ1725, HSR, Phi, Skunk, x16r, x16s, x17

[Source](https://bitcointalk.org/index.php?topic=4344544.0)

**Comment by BARUCHER777** [comment]
please add this miner!)

**Comment by Quake4** [comment]
Ок.

**Comment by Quake4** [comment]
Which driver for cuda 9.2 do you recommend?

**Comment by centreece** [comment]
Frankly, I have no idea. I'm not the dev, just found the miner on BitCoinTalk.
I'm always using the latest nVidia driver for anything. I didn't even consider that other drivers might work better! :D

**Comment by slovke** [comment]
For cuda 9.2 you need also hardware 9.2 gpu so i think Tesla Volta generation is cuda 9.x only

**Comment by centreece** [comment]
It works well with my good old 1070 GPU

**Comment by slovke** [comment]
ofcurse it will work with older cuda devices you will need 9.x hardware to use 9.2 optimizations it have for them

**Comment by centreece** [comment]
Now I got it! Thanks for the clarification!!

**Comment by aloth** [comment]
Could you also add the latest pre-release (1.2.0)?

**Comment by Quake4** [comment]
Can try?

[ccminer-delos-112.zip](https://github.com/Quake4/MindMiner/files/2056861/ccminer-delos-112.zip)

**Comment by Quake4** [comment]
only phi and skunk faster then other miners

**Comment by All-in-Miner** [comment]
@centreece check All-in-Miner, which aims to include all available miners, and also added support for Delos: https://github.com/All-in-Miner/All-in-Miner/releases

**Comment by Quake4** [comment]
added
