### ISSUE TITLE
Disable auto disable asic algos

### ISSUE THREAD

**Issue by naminator666** [Quake4/MindMiner#661]
There are some algos in the mindminer.ps that are automatically disabled, could we rather choose from a list of what algos we want disabled rather than the program auto disabling algos?

**Comment by Quake4** [comment]
what algorithm would you like to allow?

**Comment by naminator666** [comment]
Hi, mostly Tribus, C11, Skein and Skunk. If it's a wanted feature by other users, then you can allow those algos, otherwise I have no problem allowing them manually

**Comment by Quake4** [comment]
FPGAs have been sitting on them for a long time. What do you want to catch?

**Comment by Quake4** [comment]
clear the list of disabled algorithms and see the resulting profit. there's nothing interesting there. if ASICs come to the algorithm, then there is nothing for video cards to do there.
