### ISSUE TITLE
Много отклоненных и потерянных шар при майне на найсшех

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#663]
Много отклоненных и потерянных шар при майне на найсшех. доходит до 10-12% в течении 5-ти 6 ти часов.....При майнинге тех же монет на обычных пулах потери и отклонения шар доходят до 1-2% в течении суток!

**Comment by Quake4** [comment]
А скрин?

**Comment by Quake4** [comment]
Высокий пинг, например, из-за сша стратума, а не еур.
