### ISSUE TITLE
Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."

### ISSUE THREAD

**Issue by yellow-dragon** [Quake4/MindMiner#667]
When I edit ZergPool.config:

> "SpecifiedCoins": { "Ethash": [ "ETH", "ETC"]},

I see error when run:

> Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."
> At D:\\MindMiner-6.59\Code\Get-PoolInfo.ps1:71 char:4
> +             $PoolProfitCache.Add($_.PoolKey()+$_.Algorithm, $_.Profit ...
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : ArgumentException
>

**Comment by yellow-dragon** [comment]
`Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."
At D:\\MindMiner-6.59\Code\Get-PoolInfo.ps1:71 char:4
+             $PoolProfitCache.Add($_.PoolKey()+$_.Algorithm, $_.Profit ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException`

**Comment by Quake4** [comment]
thanks, fixed
