### ISSUE TITLE
Майнер WildRig запускается но с ошибками!

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#668]
Майнер WildRig запускается но с ошибками!
Подробности в скрине.
![Error-WldRig](https://user-images.githubusercontent.com/18327150/81489970-a9c7bf80-9284-11ea-872d-d9bbcbd936d3.jpg)

**Comment by Quake4** [comment]
http://virtmachine.ru/kak-udalit-bonjour-polnostyu.html
