### ISSUE TITLE
ZergPool BTC/GH/Day incorrect

### ISSUE THREAD

**Issue by yellow-dragon** [Quake4/MindMiner#669]
I config in ZergPool.config:
"SpecifiedCoins": { "Ethash": [ "ETC", "ETH"] },

I see BTC/GH/Day at window MindMiner is: 0.00106

> "Ethash_ETC":  {
>                        "Value":  0.0000000000010679140066345872,
>                        "Change":  "\/Date(1589109772234)\/",
>                        "Zero":  "\/Date(1589109772234)\/"
>                    },

Though on ZergPool is: 0.00170 => MindMiner incorrect

**Comment by Quake4** [comment]
MM has its own profit calculation that takes into account the current value of profit and 24h actual and other. Looks as proper value.
