### ISSUE TITLE
[Feature Request] Additional parameter - Minimal required miner amount on pool for algo

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#67]
As subject says , would like to request additional configurable parameter. Configurable threshold for required minimal miner amount for algo on allowed pools , to be able to filter out pools/algos with nonexistant miners even for currently most profitable algo , because usually its waste of time and hashrate.

**Comment by Quake4** [comment]
Ok. I will add in algorithms config file.
Is needed value by default?

**Comment by Quake4** [comment]
Maybe look to pool hashrate? Workers can be different: one 1070 or 8x10080Ti.

**Comment by mo35** [comment]
what i had in mind is miner count on algo, that could be retrieved via api ? if that param isnt available , pool hashrate on particular algo could work too , but that would be viable only if we can calculate percentage from algo global hashrate. As for default value i usually avoid mining algos with less than 100 miners , chances to hit block on crowded algo with less miners is nonexistant.

**Comment by Quake4** [comment]
Yes, workers & hashrate on each currency have api. https://www.zpool.ca/api/currencies
Ok. Will add miners minimal count.

**Comment by Quake4** [comment]
use MinimumMiners variable in main config
```json
    "MinimumMiners": 100
```
