### ISSUE TITLE
[Bug] issue with incorrect worker ID

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#670]
Hi, you have a problem with worker ID on MRR for BEAMV2 (also bug on miniz-1.5t3)

It is adding a pointless `._` after the rig ID for MRR and it makes it not submit correctly.

Correct rig ID would be platinumstephen.144471

![image](https://user-images.githubusercontent.com/6779241/82282721-24b26980-995a-11ea-9adf-dd7c6643c520.png)
![image](https://user-images.githubusercontent.com/6779241/82282775-3e53b100-995a-11ea-8265-89eb497b4afc.png)
![image](https://user-images.githubusercontent.com/6779241/82282826-54fa0800-995a-11ea-9350-31fb3a952925.png)

**Comment by platinum4** [comment]
This commit did not fix it
https://github.com/Quake4/MindMiner/commit/26782ab3d36e70af6f722efe1e97a559428afe1b
![image](https://user-images.githubusercontent.com/6779241/82283079-fbdea400-995a-11ea-99ff-6b0bed75bf9a.png)

**Comment by platinum4** [comment]
Guess this is just a problem with gminer itself, fixing the username didn't help.

**Comment by Quake4** [comment]
I didn't understand anything.

**Comment by Quake4** [comment]
Try the latest version.
