### ISSUE TITLE
[Miner Update] srbm-cpu-44, srbm-amd-44, xmrig-cpu-5112, xmrig-nvidia-5112, xmrig-amd-5112, phoenix-50b

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#673]

**Comment by Quake4** [comment]
https://github.com/Quake4/MindMiner/blob/master/Miners/cpuminer-opt-3141.ps1 ?

**Comment by platinum4** [comment]
OK you already have cpuminer-opt-3141

**Comment by Quake4** [comment]
https://github.com/todxx/teamredminer/
0.7.3
