### ISSUE TITLE
[MRR] Add regions

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#684]
ca-tor01 in Toronto Canada, au-01 in Sidney Australia, us-nw01 in Seattle WA USA, us-south01 in Atlanta GA USA, eu-uk01 in London United Kingdom, jp-01 in Tokyo Japan.

When I set region to us-south in MRR.config.txt it does not change from central

**Comment by Quake4** [comment]
no coded servers. are from api https://www.miningrigrentals.com/api/v2/info/servers
just need wait for update prices (every hour or on signicant change)
