### ISSUE TITLE
НЕ отображается баланс при майнинге через НайсХеш!

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#688]
НЕ отображается баланс при майнинге через НайсХеш! Эта проблема появилась давно начиная примерно с версии 6.19 или 6.20

![mindminer678](https://user-images.githubusercontent.com/18327150/85404598-d8190a00-b567-11ea-9891-ac880e42f15c.jpg)

**Comment by Quake4** [comment]
Есть в конфиге? `"ShowBalance": true,`

**Comment by BARUCHER777** [comment]
Нету увы, вот конфиг:
{
    "Region":  "Europe",
    "Wallet":  {
                   "BTC":  "1G53vRm5rD2ZDorL3bGorW3FpneyG7zKvz"
               },
    "AllowedTypes":  [
                         "nVidia",
                         "AMD",
                         "Intel"
                     ],
    "ApiKey":  "2L4dk8d37Xk7wOEb"
}

**Comment by Quake4** [comment]
Добавьте перед ApiKey

**Comment by BARUCHER777** [comment]
Добавил строчку эту,но не помогло, баланс все равно не отображается

**Comment by Quake4** [comment]
Спасибо. Nice Поменял апи. Исправил.
