### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by danik-guitar** [Quake4/MindMiner#7]
А ты не хочешь оформить свою прогу в виде виндоус окна, наподобии найсхэша.
Там удобно поставил галочку автозагрузка и автозапуск. комп завис перезагрузился и сразу загружается сама и запускается. Да и удобнее менять какие то настройки было бы типо кошелька и интервала и добавить стаститику майнинга с графиком во вкладке. 
Так же включать и выключать пулы с помощью галочки не прерывая майнинг например.
Галочкой включать и выключать нужные алгоритмы и майнеры не прерывая майнинг. ну вот для обычных юзеров удобно и просто было бы)

**Comment by Quake4** [comment]
Нет, Windows GUI не будет.
