### ISSUE TITLE
[Miner Update] lolminer-109, srbm-cpu-53, srbm-amd-53, teamred-713, gminer-226, bminer-1631, ccminer-trex-173, miniz-16w, xmrig-cpu-635, xmrig-nvidia-635, xmrig-amd-635, cpuminer-opt-315

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#707]

**Comment by mo35** [comment]
+miniZ v1.6w , +trex 0.17.2
https://miniz.ch/download/#latest-version
https://github.com/trexminer/T-Rex/releases/tag/0.17.2

**Comment by mo35** [comment]
+gminer 2.23
https://github.com/develsoftware/GMinerRelease/releases/tag/2.23

**Comment by Quake4** [comment]
let's pull requests ;)

**Comment by platinum4** [comment]
you would still need fix srb and trex

**Comment by Quake4** [comment]
what exactly?

**Comment by platinum4** [comment]
t-rex ethash doesn't work on miningpoolhub and i think api on srb was acting weird like not reading hashrates; i had used -52 though

for t-rex and mph i think you need have like a stratum2

**Comment by Quake4** [comment]
look at t-rex file. im add stratum2 for mph
