### ISSUE TITLE
Claymore`s miner`s not worked in my config!

### ISSUE THREAD

**Issue by BARUCHER777** [Quake4/MindMiner#71]
Dear developer, help me to solve the problem, none of the claymore miners will start at all! may need to update something, or register in configuration files, or update the graphics card drivers, to the latest versions !?

**Comment by Quake4** [comment]
Try run miner manually from window's console. See message.

**Comment by BARUCHER777** [comment]
![neoscrypt-err001](https://user-images.githubusercontent.com/18327150/40880545-a850a762-66bb-11e8-96d2-1ee4dbcdf2f1.jpg)

**Comment by BARUCHER777** [comment]
Доброго времени суток, проблема в следующем, дело в том, что у меня две АМД карты первая на ней подключен моник (RADEON R7 240 2 GB) и вторая radeon rx-580 8GB 
Майнер запускается только с параметром "-di 1"  проблема теперь в другом как этот параметр добавить во все майнеры от Клеймора?!?

**Comment by Quake4** [comment]
Поправить 4 кофига, прописать в общий Extraargs нужное значение:
```json
{
    "Algorithms":  [
                       {
                           "ExtraArgs":  null,
                           "BenchmarkSeconds":  0,
                           "Enabled":  true,
                           "Algorithm":  "ethash"
                       }
                   ],
    "ExtraArgs": "-di 1",
    "BenchmarkSeconds":  90,
    "Enabled":  true
}
```

**Comment by BARUCHER777** [comment]
Спасибо! почти все заработало! Но увы при моих настройках для исп пулов почему-то "Claymore's ZCash/BTG AMD GPU Miner v12.6" отказывается запускаться и работать с пулом zpool.ca////

Тпк же прошу вас обратить внимание на майнер: PhoenixMiner 2.9e: fastest Ethereum/Ethash miner with lowest devfee (Windows) у него комисия всего 0.65% и так же в некоторых конфигах он бывает немного быстрее майнера от Клеймора для ETHash

**Comment by Quake4** [comment]
Zpool для equihash днище, но ошибка с claymore zcash исправлена.  Спасибо.
