### ISSUE TITLE
Global GPU selection in config file and maybe miners

### ISSUE THREAD

**Issue by vost56** [Quake4/MindMiner#72]
It will be good to select only GPU-s with -d switch. Example "GPUsToMine": { "AMD": "0,2", "nVidia": "0-3" } to leave some GPU for other purposes like playing games, test mining etc..

**Comment by Quake4** [comment]
No. Statistics are updated during mining. Choosing a gpu will lead to strange results.

**Comment by Quake4** [comment]
You can fast fix mining to one algo during enabledalgorithms variable in algorithms.txt and change same miner.config.txt variable extraargs adding gpus.
