### ISSUE TITLE
Failed to detect NVIDIA platform ID

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#739]
![image](https://user-images.githubusercontent.com/6779241/99894477-a35dcb80-2c49-11eb-8127-ee22e5e8b13b.png)

fresh OS install, NVIDIA 457.30

**Comment by Quake4** [comment]
Install prerequisites

**Comment by platinum4** [comment]
It already said installing 7 prerequisites, which am I missing?

**Comment by platinum4** [comment]
function ParseCudaVersion([Parameter(Mandatory)][string] $verstr) {
	$ver = [version]::new($verstr)
	# https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
	$result = [version]::new()
	if ($ver -ge [version]::new(456, 38)) {
		$result = [version]::new(11, 1);
	}

**Comment by Quake4** [comment]
show running screen of `bin\AMDOpenCLDeviceDetection.exe`

**Comment by platinum4** [comment]
vc++ runtime 12 installed and fixed

**Comment by Quake4** [comment]
2012?

**Comment by platinum4** [comment]
yes was missing msvci120.dll

**Comment by Quake4** [comment]
its Microsoft Visual C++ 2013. have link in prereqs
