### ISSUE TITLE
[Enhancement]: for MRR let us set multipliers on pricing for algos

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#740]
Hi, for common algos like Ethash I might want to offer cheaper prices but for little-used algos like GRIMM or C29V or something else I might want to charge more, can we add a place where we can set algos in a series to certain price multiplier?

Like target profit is 50% but when I want to sell Ethash on MRR I want to sell it at 80% of the 50% target, so I want a list where we can add "AlgoPriceMultipliers": ["Ethash" : 0.8, "Grimm" : 1.15 ] to be multiplied on top of my 50% target.

This would help us profit on the new algos listed when they are hot or from forks.

**Comment by Quake4** [comment]
https://github.com/Quake4/MindMiner/commit/69d39cbe2dc54cfc2a50e2548deb66da8cbbe0a8
can you try it

**Comment by platinum4** [comment]
Yeah sure I will; you spelled target wrong here 
![image](https://user-images.githubusercontent.com/6779241/100742760-ea159900-33a0-11eb-8175-ce2e29b9c0de.png)

**Comment by platinum4** [comment]
I put something like { "Ethash": 200 } and it does not double the rate

**Comment by platinum4** [comment]
Can you make them scalars instead of multipliers so we can set it at 1.25 or 2.0 or 3.33

**Comment by Quake4** [comment]
Show `mrr:` output with speed and prices.
No

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/100851460-dde61600-344a-11eb-95b2-0fe7165ec1c1.png)
I have Octopus set to 200% and you can see its target profit is the exact same

**Comment by platinum4** [comment]
Not sure what you wanted me to do here, I went and downloaded your new MRR.ps1 and it cuts off like half of the code probably due to missing syntax somewhere

**Comment by platinum4** [comment]
The problem is the lines at 380-382 it breaks the rest of the PS1 file

**Comment by platinum4** [comment]
You can see all the broken code in Notepad++

![image](https://user-images.githubusercontent.com/6779241/100854629-e3455f80-344e-11eb-846c-acc4b02fd426.png)

**Comment by platinum4** [comment]
Ah nevermind I think I might have this working now

**Comment by platinum4** [comment]
Yeah hell yeah thanks
![image](https://user-images.githubusercontent.com/6779241/100855075-66ff4c00-344f-11eb-9cee-8b83b065430f.png)

**Comment by platinum4** [comment]
if ($var -lt 5) {
				$Cfg.TargetByAlgorithm."$_" = 50
			}

I can't use any values between 6 and 49 here they all default to 50; what can be done to fix this or set cheaper pricing besides changing my main target?

**Comment by platinum4** [comment]
"TargetByAlgorithm": { "Chukwa2": 200, "Cpupower": 200, "Qureno": 200, "RandomSFX": 200, "RandomWOW": 200, "RandomX": 200, "RandomXL": 200, "ScryptN2": 200, "Yescrypt": 200, "Yespower": 200, "Yespower2b": 200, "Yespowerr16": 200, "Lyra2z330": 10, "Octopus": 10 },
![image](https://user-images.githubusercontent.com/6779241/100857070-d6763b00-3451-11eb-94a2-8cc44d05436f.png)
You can see is defaulting to 50 even though I am not breaking the conditional rule of being less than 5

**Comment by platinum4** [comment]
Oh, I was using 10 so I just thought 50 *.1 is still 5, let me try 11

**Comment by platinum4** [comment]
Still failing over to 50 even when trying 25

**Comment by platinum4** [comment]
I guess I would lower target then increase the percentages, but I want to be able to keep same target and lower prices and raise too

**Comment by platinum4** [comment]
OK I see that this just substitutes the target by algorithm it does not modify it; when I lower my MRR floor to 30% profit you can now see 30s here

![image](https://user-images.githubusercontent.com/6779241/100857993-007c2d00-3453-11eb-9ac5-c08469b65b82.png)

**Comment by platinum4** [comment]
If you can remove that line so I can test then it won't be replaced by updates every time that'd be fine-- I don't want to waste my time calculating targets to match other rigs on market if the next update 6.116 will just erase the code change in MRR.ps1

This is great to increase prices only but there are not a lot of use cases outside of the CPU algorithms where you might want to do that; most other algos on GPUs have competitors but for certain algos I want to go lower if possible but not drop my global target to something really low since then the multiplier on it won't scale the same

**Comment by platinum4** [comment]
Thanks I think I got this working OK by lowering my global target to 5 or 10

**Comment by platinum4** [comment]
Thanks, now I got my CPU making more than a 1070

**Comment by platinum4** [comment]
6.116 overwrote this and now it's gone

**Comment by platinum4** [comment]
I see this in branch for MindMIner-7 and thank you for adding this feature
