### ISSUE TITLE
[Miner Fix] srbm-cpu-56: scryptn2 may fail allocating 768 to HP and then instead run a ton of threads over the capacity of CPU

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#744]
Hi, I had a 4c/8t be assigned 42 threads of scryptn2 when running srbm-cpu-56; I fixed it by setting --cpu-threads to the max threads available when grabbing system info which was 8; maybe you can make a config fix like you did for ccminer verus

**Comment by Quake4** [comment]
what's the point? The speed is lower than 8 threads.
