### ISSUE TITLE
[MRR] Add mappings: cnFast, cnTalleo

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#749]
"cryptonight_masari" = "cnFast"
			"cryptonotefast" = "cnFast"
			"cn/fast" = "cnFast"
			"cnfast" = "cnFast"

https://www.miningrigrentals.com/rigs/cryptonotefast

works in cryptodredge-16a not cryptodredge-251

**Comment by platinum4** [comment]
"cryptonightulv2" = "cnTalleo"
			"cryptonighttlo" = "cnTalleo"
			"cn-pico/tlo" = "cnTalleo"

https://www.miningrigrentals.com/rigs/cryptonightulv2

**Comment by platinum4** [comment]
"cryptonight_v8_reversewaltz" = "cnRWltz"

Add for xmrstak

**Comment by Quake4** [comment]
I certainly understand the topic of perfectionism, but why is this mammoth shit? No one will rent it anyway, and an untrained user will not be able to pass the benchmark.

**Comment by Quake4** [comment]
in new version, im move xmrstak to archive
https://github.com/Quake4/MindMiner/commit/cae6409bf22e998bb45481c062bdb9c950a17fcd

**Comment by platinum4** [comment]
You can just copy and paste so advanced users who want to profit during bull markets can do so.

I've caught rentals of cnheavy, c11, and more, sha3d too, people want obscure algos and I already did all the work for you.

**Comment by platinum4** [comment]
Example of cnFast being rented recently

![image](https://user-images.githubusercontent.com/6779241/100435403-80755200-3063-11eb-8538-398b9fd0b63e.png)

**Comment by Quake4** [comment]
ok, I'll add it

**Comment by platinum4** [comment]
I already got MRR to disable Equihash96,5 YespowerLITB Cryptonote-B2N and Cryptonote-Red so I'm making sure most everything they list can still be mined so there's less bullshit to select from

**Comment by Quake4** [comment]
Is where it algorithms in miners?

**Comment by platinum4** [comment]
Yeah it's "cnfast" in cryptodredge-16a and "cn/fast" in xmrig
For talleo it's "cryptonighttlo" in cryptodredge-251 and "cn-pico/tlo" in xmrig

That is for their config files or in their miner.ps1

**Comment by platinum4** [comment]
This has been added correctly; thank you again.

**Comment by platinum4** [comment]
Thanks, I know you were cussing me out regarding adding these mappings, but this is why

![image](https://user-images.githubusercontent.com/6779241/101170446-154bf280-3604-11eb-9033-de1d74710da1.png)
