### ISSUE TITLE
Придумано хитро

### ISSUE THREAD

**Issue by spider703** [Quake4/MindMiner#76]
систему ты придумал конечно хитрую, особенно с хранением на своем сервере ID который присвоен пользователю, и время когда включить майнинг на разработчика. даже если пользователь грохнет config.txt он его получает онлайн, что не есть хорошо для майнинга, любой кто взломает твой сервер - получает супер профит - можно поставить майнить на взломавшего, переписав пару файлов

**Comment by spider703** [comment]
да нет, перелопатил всю твою программу, нашел лишь два варианта откуда прога может получить адрес разработчика, чтобы на него майнить - сама страница mindminer.online или с мультипулхаба, ну не верю я что программа построена на голом энтузиазме

**Comment by Quake4** [comment]
Я писал ее для себя, потому что, то что написано в MPM и прочем, это ужас.
И прошу за это 1% и все бенчи.
За это предлагаю, стабильность и быстрое обновление.

**Comment by spider703** [comment]
вот с этого и надо было начинать что писал для себя. тогда верю, осталось два вопроса - 1) 1% в час или в сутки? и второй - при закрытии основного окна повершел - окна майнеров не закрылись (работал бенчмарк), и последнее - после ребута пк, если ытарт.бат в автозапуск запихать - так же каждый раз будет спрашивать подтвердить или нет?

**Comment by Quake4** [comment]
А есть разница между 1% в день или час или месяц?
Alt+E или Alt+Q выход из MM.
Не понял о каком подтверждении речь? Если от майнеров, то только раз в основной требует клэймор.

**Comment by Quake4** [comment]
> вот с этого и надо было начинать что писал для себя.

Так и написал:

![image](https://user-images.githubusercontent.com/29517243/41040549-6569fd8a-69a5-11e8-9ba3-c852031a5085.png)
