### ISSUE TITLE
[Bug] lolminer-116a: ETCHASH - Incorrect Speed Read from API

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#760]
Missing MEGAhashes, just reads hashes

![image](https://user-images.githubusercontent.com/6779241/100526379-e231db00-318d-11eb-88d0-e61e3729034c.png)

**Comment by Quake4** [comment]
its api answer bug, send hases instead of megahashes.
`$resjson.Session.Performance_Summary`

**Comment by Lolliedieb** [comment]
This is not a bug of lolMiner. The api clearly states it is outputting mh/s
![no_bug](https://user-images.githubusercontent.com/40234439/101167539-519a4580-363a-11eb-94f8-cd3955d87f5f.png)
