### ISSUE TITLE
How to assign different wallets to some pools?

### ISSUE THREAD

**Issue by ebojali** [Quake4/MindMiner#77]
Config looks like this:
{
    "Region":  "Europe",
    "SSL":  true,
    "Wallet":  {
                   "BTC":  "19CHz......",
               },
    "WorkerName":  "rig1",

I would like:
Blaze,Ahash, NH = BTC wallet
Zerg,Zpool = LTC wallet

Can you please help me with pointing out what to change in the config file and if anything needed to be changed in the pools configurations.

Thanks!

**Comment by Quake4** [comment]
Hello

Why you use LTC on zerg & zpool.

**Comment by ebojali** [comment]
Because I want to be able to specify different wallets for different pools. I can do it on other miner applications.

**Comment by Quake4** [comment]
There isnt such setting now. Use other miner applications.
Now you can use only two wallets LTC & BTC for pools. (if specified "LTC" wallet its use at Zergpool, HashRefinery and BlockMasters).

**Comment by ebojali** [comment]
That is very unfortunate, I hope this will be added in future releases. Keep up the good job!

**Comment by platinum4** [comment]
Hi, is this issue resolved?

**Comment by ebojali** [comment]
Nope nothing yet

**Comment by Quake4** [comment]
thanks for awaitings. 2.94
