### ISSUE TITLE
[Bug] MRR error when us-south01 was down

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#771]
![image](https://user-images.githubusercontent.com/6779241/101230016-a6ed4b80-3668-11eb-9455-a394ac21eaa1.png)
Now I can't mine on MRR anymore what's up?

**Comment by platinum4** [comment]
@Quake4 Help please!!  Happens on brand new download and I tried 7 too!!

**Comment by platinum4** [comment]
Need a fix!!

**Comment by platinum4** [comment]
Resolved by waiting

**Comment by platinum4** [comment]
Hi, maybe you can make some better error message for MRR when it is not reachable

**Comment by platinum4** [comment]
Same shit a second time; can you force MRR Pool check to check failovers regardless of specified region?  Or at least eat the error message correctly so we can failover successfully

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/101233375-318c7580-367e-11eb-9022-a0b89b1212b3.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/101233616-b081ae00-367e-11eb-9665-3b37a02168ee.png)

**Comment by platinum4** [comment]
Can you force MRR Pool check to check failovers regardless of specified region?  Or at least eat the error message correctly so we can failover successfully

![image](https://user-images.githubusercontent.com/6779241/101235070-cdbc7980-368a-11eb-9071-c6f651718921.png)

**Comment by platinum4** [comment]
maybe you can make region an array so we can add 2-3 failovers

**Comment by platinum4** [comment]
Hi and also maybe call for ports less idk, they stay valid 7 days whatever that means

**Comment by platinum4** [comment]
remove /port from 					$redir =  $mrr.Get("/rig/$($_.id)")

**Comment by platinum4** [comment]
Hi, nevermind that totally removes the pool address and port when I do that

**Comment by Quake4** [comment]
just need change region in MRR.config.txt

**Comment by Quake4** [comment]
with /port and without, is 2 different answers

**Comment by Quake4** [comment]
They could have corrected the situation if the response ` "/rig/$($_.id)/port" ' gave a different site than us-central

**Comment by Quake4** [comment]
Which they did, see the answer `https://www.miningrigrentals.com/api/v2/info/servers`
