### ISSUE TITLE
[MindMiner.ps1] Disable ASIC Algo: X17

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#776]
https://lionblockchain.en.alibaba.com/product/62550293162-813912448/Blockchain_Asic_Miner_Ibelink_XM17C_Miner_28g_X13_X17_Algorithm_mining_BCD_Verge_coin.html

**Comment by Quake4** [comment]
more recently, we took rigs on X17 on MRR, until I turn it off
