### ISSUE TITLE
[Miner upgrade] Delos 1.3 is out

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#78]
DelosMiner v1.3.0 is released!

Change log:

    Performance boosts on LYRA2v2, Skein and x16r!
    Additional core speed improvements of up to 2% for most algos.
    Revised dev fee mechanism for a seemless mining experience.

**Comment by Quake4** [comment]
https://bitcointalk.org/index.php?topic=4344544.0

**Comment by Quake4** [comment]
Added in version 2.32
