### ISSUE TITLE
[MindMiner-7] Weird error with if statement

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#782]
![image](https://user-images.githubusercontent.com/6779241/102400341-674b2b80-3fa7-11eb-8262-0d9e6ce6ddc4.png)

**Comment by platinum4** [comment]
This happened when RandomX was enabled and rented on MRR

**Comment by Quake4** [comment]
You, isnt set failover region. Its warning. Error is red.

**Comment by Quake4** [comment]
Try 7.1. must be fixed.

**Comment by platinum4** [comment]
This fixed my MRR RandomX rental, you can close this

**Comment by Quake4** [comment]
Fine. Thank you.
