### ISSUE TITLE
[MRR] FailoverRegion does not set even when set in MRR.config.txt

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#783]

**Comment by Quake4** [comment]
Config plz and screen

**Comment by platinum4** [comment]
I removed the name and targetbyalgorithm for privacy
{
    "MinHours":  3,
    "Enabled":  true,
    "Key":  "<removed for privacy>",
    "Increase":  5,
    "MaxHours":  120,
    "Secret":  "<removed for privacy>",
    "DisabledAlgorithms":  null,
    "Decrease":  5,
    "Wallets":  [
                    "ltc",
                    "bch",
                    "eth",
                    "dash"
                ],
    "FailoverRegion":  "us-central",
    "Region":  "us-south"
}

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/102410207-db8ccb80-3fb5-11eb-9f28-0cfbd917c54a.png)
If I disable RandomX in algos in MRR it works

**Comment by platinum4** [comment]
I currently have a MRR RandomX rental active and cannot continue to mine on that rental contract because of this

**Comment by Quake4** [comment]
If statement is fixed. Restart MM to update it to 7.1.

**Comment by platinum4** [comment]
Hi, this still does not recognize failover; have you added us-south to your regions database so it is recognizable?  It is not in your list anywhere in any config.md but us-south has worked for me for a year.

Also my failover is us-central which is in the list and is still not setting
