### ISSUE TITLE
[Miner Fix] gminer-235: disable ETChash on MPH

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#784]
![image](https://user-images.githubusercontent.com/6779241/102444717-7bb31680-3fef-11eb-88ff-2772e6f0e665.png)

**Comment by Quake4** [comment]
plz, try 7.2. must be fixed `--proto stratum`

**Comment by platinum4** [comment]
Please version bump so it can autodownload to multiple rigs

**Comment by Quake4** [comment]
tested. fixed
