### ISSUE TITLE
Не находит config.txt

### ISSUE THREAD

**Issue by SliderVM** [Quake4/MindMiner#788]
При запуске выдает сообщение
Missing configuration file 'config.txt'. Create. Please, enter wallet address now and change other parameters later.

Если настроить конфиг получаем 
ConvertFrom-Json : [C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Utility\v4.0_3.0.0.0__31bf
3856ad364e35\Microsoft.PowerShell.Commands.Utility.dll] Неправильная сигнатура.
C:\Users\mix\Desktop\MindMiner-6.106 nv\Code\BaseConfig.ps1:34 знак:35
+         $temp = Get-Content -Path $fn | ConvertFrom-Json
+                                         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by Quake4** [comment]
У вас конфиг не соответствуют структуре JSON.
Скорее всего пропустили запятые.

**Comment by SliderVM** [comment]
> У вас конфиг не соответствуют структуре JSON.
> Скорее всего, пропустили запятые или вставили `=` вместо `:`.

Конфиг не трогал, после обновления до 7.1 появилась такая ошибка.
Обновил Microsoft .NET Framework до версии 4.8 ошибка ушла

**Comment by Quake4** [comment]
`NotSpecified: (:) [ConvertFrom-Json], BadImageFormatException`

**Comment by Quake4** [comment]
Явно не хватало `:` где то
