### ISSUE TITLE
[Miner Fix] nb-nvidia-350f: etchash not working on mph

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#789]

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/102480109-e2c4df80-4070-11eb-81c2-ad5ff7bc7b8b.png)
???

**Comment by Quake4** [comment]
does it work?

**Comment by platinum4** [comment]
Tested with nb-nvidia-352 and it works for etchash on mph
