### ISSUE TITLE
[Miner Fix] MRR.ps1 something wrong; MRR keeps switching to failover and back to main server

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#791]
![image](https://user-images.githubusercontent.com/6779241/102531669-4bf42500-4068-11eb-96c2-51fa460413ca.png)
Retried 340 times?

**Comment by platinum4** [comment]
Now it's trying to connect to ap whenever I never ever specified ap 
![image](https://user-images.githubusercontent.com/6779241/102532008-eb191c80-4068-11eb-9adc-54cf1c5a2ca0.png)

**Comment by Quake4** [comment]
`Retried 340 times?`
Run miner 340 times.

**Comment by Quake4** [comment]
try change nb.ps1 and set  `ethproxy+tcp` for MRR

**Comment by platinum4** [comment]
Dude watch your own rentals behavior it just switches to failover ap-01 for no reason.  This is dropping the miner every 60 seconds and switch MRR server it's frustrating as hell.

**Comment by platinum4** [comment]
Nope happens with t-rex and gminer too

**Comment by Quake4** [comment]
reason, your failover is dead

**Comment by platinum4** [comment]
If I set my failover to us-central it just alternates between us-south and us-central every 60 seconds.

**Comment by Quake4** [comment]
randomx mined is normal?

**Comment by platinum4** [comment]
No that has like 300+ retries too but I thought it was because difficulty was too high for worker, let me check

**Comment by platinum4** [comment]
Nope you can see it bouncing servers the whole time here:  
![image](https://user-images.githubusercontent.com/6779241/102533022-76df7880-406a-11eb-93cd-5bb4c6d8a02c.png)

**Comment by Quake4** [comment]
plz, temporary remove failover pool in MRR

**Comment by platinum4** [comment]
When I remove failover, the failover defaults to ap-01

**Comment by Quake4** [comment]
add line to MRR

**Comment by platinum4** [comment]
Not sure what you mean by this

**Comment by Quake4** [comment]
`$redir =  $mrr.Get("/rig/$($_.id)/port")`
`Write-Host "$($redir | ConvertTo-Json)"`

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/102534951-24ec2200-406d-11eb-97fd-31fedec18596.png)

**Comment by Quake4** [comment]
fine, 15 minutes, im is write a fix

**Comment by platinum4** [comment]
Thanks buddy

**Comment by Quake4** [comment]
try change previous line to
`try { $redir.port = [int]$redir.port } catch { }`

**Comment by platinum4** [comment]
This keeps the miner alive longer than 5 minutes yes

**Comment by Quake4** [comment]
strange. powershell work different on different  machines.

**Comment by Quake4** [comment]
again: try change nb.ps1 and set ethproxy+tcp for MRR

**Comment by Quake4** [comment]
does it work?

**Comment by platinum4** [comment]
Yeah, this seems to work at the moment, it keeps both my rentals CPU and GPU on south, earlier it used to put the second rental on the failover every time.
