### ISSUE TITLE
[Feature Request] Drop MRR rental priority if Nicehash or MPH Ethash is more profitable

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#792]
Hi,

This is new times with Bitcoin at all time high, I want option to drop the priority for MRR below the most profitable algo even if it is on NH/MPH; I don't care about not getting 100% rental if it is more profitable to switch for some time, without me having to manually watch this.

**Comment by Quake4** [comment]
I'm not going to do it and I will not explain. I will say that the contract is higher than the immediate profit. I recommend not giving up for more than 48 hours. let me remind you, the default value of target is 50% and maxhours is 24 hours and it is not taken from a simple, but that would not miss the growth of profitability

**Comment by platinum4** [comment]
@Quake4 I am forfeiting profit
![image](https://user-images.githubusercontent.com/6779241/102550150-f0836080-4082-11eb-928a-517aba487ca2.png)

**Comment by Quake4** [comment]
I say, do not give up for target profit 5%.
25-30% its minimum
