### ISSUE TITLE
[Miner Fix] gminer-235: grin29 fee is 3%

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#794]

**Comment by Quake4** [comment]
[AlgoInfoEx]@{ Enabled = $true; Algorithm = "cuckaroo29" }
		[AlgoInfoEx]@{ Enabled = $true; Algorithm = "cuckaroo29b" }
		[AlgoInfoEx]@{ Enabled = $true; Algorithm = "cuckarood29" }
		[AlgoInfoEx]@{ Enabled = $true; Algorithm = "cuckarood29v" }
		[AlgoInfoEx]@{ Enabled = $true; Algorithm = "cuckaroom29" }
		[AlgoInfoEx]@{ Enabled = $true; Algorithm = "cuckarooz29" }
which one?
elseif ($_.Algorithm -match "cuckarooz29") { 3 }

**Comment by platinum4** [comment]
The command I ran was --grin29 and gminer dev said it was cuckarooz, can you try?

**Comment by Quake4** [comment]
Im check it.
