### ISSUE TITLE
[Miner Fix] gminer-237: Remove algos: removed algorithms: Eaglesong, Handshake, Kadena, BeamHashI, BeamHashII, Grimm, Cuckaroo29, Cuckaroom29, Equihash 96,5, Cuckoo24

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#797]

**Comment by Quake4** [comment]
No, I write all supported algorithms in the miner config. that would not be lost

**Comment by platinum4** [comment]
@Quake4 I can tell you did not read the release notes from gminer-235 where that list of algos is REMOVED from the miner so you cannot even run them.
