### ISSUE TITLE
not showing pool profit calculations for fiat

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#80]
After latest updates my test rig stopped showing USD/day EUR/day for zergpool , so does in balance summary only btc is shown. I downloaded 2.32 , made clean unpack , copied miner statistics and config
over. I removed zergpool statistic file. 
Config file isnt changed between updates. and it does include -
"ShowBalance": true, and "Currencies": { "BTC": 8, "EUR": 2 },

basically i cant get my head around issue , whats wrong... suggestions?
![capture](https://user-images.githubusercontent.com/16078512/41096326-f32fc7aa-6a5c-11e8-89c4-c8b74e709163.PNG)

**Comment by Quake4** [comment]
Main config must contain wallet LTC and MM mine in LTC on zerg, then showing.

**Comment by Quake4** [comment]
please, show config.txt without wallets, replece its to spaces

**Comment by mo35** [comment]
my config , err i dont want LTC payouts , coinbase api calls are correct

{
    	"Region": "Europe",
    	"SSL": true,
    	"Wallet": { "BTC":  "xxx" },
    	"WorkerName": "Ti",
    	"Login": "xxx",
    	"Password": "x",
    	"CheckTimeout": 5,
    	"LoopTimeout": 60,
    	"NoHashTimeout": 10,
    	"AverageCurrentHashSpeed": 180,
    	"AverageHashSpeed": "1 day",
    	"Verbose": "Normal",
    	"AllowedTypes": [ "nVidia" ],
    	"CoolDown": 2,
		"ApiServer": false,
		"SwitchingResistance": { "Enabled": true, "Percent": 4, "Timeout": 15 },
		"BenchmarkSeconds": { "nVidia": 240 },
    	"MinimumMiners": 50
}

**Comment by mo35** [comment]
meh uploaded changed config (edited), was messing around , actual one have showbalance and currencies parameters

**Comment by Quake4** [comment]
coinbase responding?

**Comment by mo35** [comment]
yep , told so
 {"data":{"currency":"BTC","rates":{"AED":"28245.09","AFN":"550268.05","ALL":"818598.37", blah blah blah

**Comment by Quake4** [comment]
look to window, now normal showed?

**Comment by Quake4** [comment]
I'm write more failover code, if coinbase not respond. I hope it will be less repeated.

**Comment by Quake4** [comment]
please, wait next version 2.24

**Comment by mo35** [comment]
Actually i figured whats wrong , something changed regarding your miner , symantec endpoint started to block something. If im disabling av/fw then im getting fiat calculations. Disabling AV/FW is not an option.

**Comment by Quake4** [comment]
add to trusted app in semantic, or add to disabled folders to check.

**Comment by mo35** [comment]
what else exactly to add , bat file was already added , and folder excluded from all scans.
turned notifications on and now im getting spammed with each MM refresh with following.

[SID30805] System Infected: Coinminer activity 5 detected and [SID30601] Coinminerdownload detected.

have no idea what else to exclude to allow api requests , MM itself works , so does miners , but seems 
 like api requests causes grief for some reason

i see some red flashing on MM updates , is there way to turn on debuging , loging on so i can see thos ?

**Comment by mo35** [comment]
i did that already long time ago (as always with all the mining crap) , as i said problem is not with MM or even miners themselves , problem is with api request not going trough for unknown reason. 

I dont have problem with Symantec spamming abut coinminer , i can just suspend thos notifications , but api updates is must have , that why im asking about debug mode or loging.

**Comment by Quake4** [comment]
I dont know the semantic programm. Possible, you can create white list:
github.com
all used pools

**Comment by mo35** [comment]
did that , nothing helped , i even tried to di trough signatures .... tens of thousands of them ... eventualy i had to get rid of Symantec intrusion prevention module , replaced with my Malware bytes , so unfortunately no strightforward solution , but workaround solution

**Comment by Quake4** [comment]
You won semantic?

**Comment by mo35** [comment]
nope , unfortunately i couldnt find way in Symantec Endpoint to put MM completely on ignore , and weirdest part was , i had all urls , all bins in excluded and had no problems with them , but it was some kind of false positive about JSCoinminer/JSCoindownloader (thos websites with xmr mining integrated) , and it was getting triggered when MM requested data from pool api , doesnt make any sense at all. So i replaced Symantec AV/web protection part with Malwarebytes , and just left Symantec firewall.
