### ISSUE TITLE
Solo mining pool setup

### ISSUE THREAD

**Issue by RL-R** [Quake4/MindMiner#806]
How do i setup so i pool from my bitcoin-qt or litecoin-qt running on localhost?
i assume this isnt supported because you wont get your 1%? or will you? im fine with 6.435BTC/LTC 💯 @Quake4 

or perhaps a more important question, how can i setup my own custom pool file in the pools folder?

or is that even allowed?

**Comment by Quake4** [comment]
Why do you need MM? Just run the miner on your local wallet.

**Comment by RL-R** [comment]
Im having trouble with setting up litecoin mining on bfgminer (a stratum
error i believe)  and i cant get bfgminer to detect my gpus on bitcoin...
so currently i can only mine bitcoin with cpu getting about 16Mh/s total
... going mad here! Thanks for your reply sorry to trouble you with
newbie questions haha
