### ISSUE TITLE
Can't run nvidia-smi.exe: Unknown value:  [N/A]

### ISSUE THREAD

**Issue by mwodzynski** [Quake4/MindMiner#807]
I am getting the following error message when tying to run MM for the first time. 

**Can't run nvidia-smi.exe: Unknown value:  [N/A]**

Any advise? 

TIA

**Comment by Quake4** [comment]
pls run smi and post result
`programfiles\NVIDIA Corporation\NVSMI\nvidia-smi.exe --query-gpu=gpu_name,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,clocks.current.graphics,clocks.current.memory,power.default_limit --format=csv,nounits`

**Comment by Quake4** [comment]
and check 7.13 version. I tried to fix the problem.

**Comment by Quake4** [comment]
?

**Comment by mwodzynski** [comment]
Sorry I couldn't get to this yet. I will look into this, this evening and will post update.

**Comment by mwodzynski** [comment]
I was able to do a fresh "install" without any problems. GREAT THANKS
Do you still need smi results?

**Comment by Quake4** [comment]
Yes. Pls post smi results

**Comment by mwodzynski** [comment]
`"c:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=gpu_name,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,clocks.current.graphics,clocks.current.memory,power.default_limit --format=csv,nounits`

Result: 

name, utilization.gpu [%], utilization.memory [%], temperature.gpu, power.draw [W], power.limit [W], fan.speed [%], clocks.current.graphics [MHz], clocks.current.memory [MHz], power.default_limit [W]
GeForce RTX 2060 SUPER, [N/A], [N/A], 65, [N/A], [N/A], 79, [N/A], [N/A], [N/A]

`"c:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=driver_version --format=csv,nounits,noheader`

Result:

457.51

I had to back roll the driver, because I had some problems after downloading the newest one.
