### ISSUE TITLE
[miner] CryptoDredge 0.3.0 ccminer fork

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#81]
claims to be fastest on Neoscrypt , Lyra2REv2 and Allium (at least on 1080Ti)

https://bitcointalk.org/index.php?topic=4129696.0

**Comment by mo35** [comment]
0.4.0 version with Phi2 support is out

**Comment by Quake4** [comment]
It does not have an api. I cant add.

**Comment by mo35** [comment]
api is missing for now , implementation in progress

**Comment by Quake4** [comment]
ok, just reopen after adding or create new issue.

**Comment by mo35** [comment]
https://github.com/technobyl/CryptoDredge/releases

v0.6.0 with api
