### ISSUE TITLE
[Miner Enhancement] Make minimum price target match LowerFloor if set

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#816]
Hi,

If I set LowerFloor for CPU at 0.00001 BTC I will see me catch rentals that earn 0.00000800 or less and they still mine due to priority is enhanced since a mining contract is in force.

When setting target can you add a condition to check and see if price target as calculated is below LowerFloor, and if so, please replace the intended price target with LowerFloor.  Then, set price to equal LowerFloor since price target fell below LowerFloor.

That way no matter what profitability fluctuates the price will always target LowerFloor instead of go below LowerFloor

**Comment by platinum4** [comment]
As it is LowerFloor is working as intended, it does not mine when contracts are not in force, and thank you for adding this a few years ago.

**Comment by Quake4** [comment]
added, but not the correct implementation.

**Comment by platinum4** [comment]
Not really needed since TargetByAlgorithm overrides this behavior basically.
