### ISSUE TITLE
[extDLL] Temperature incorrect for Zen 3 CPUs

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#817]
https://i.imgur.com/EzwGttZ.png

Using stock cooler, I do not think it is this good though to be 0 C

**Comment by Quake4** [comment]
pls, check
1. latest openhardwaremonitor.dll from MM site
remove bin\openhardwaremonitor.dll
and Ctrl+R in MM
2. latest openhardwaremonitor.dll from developer
replace, openhardwaremonitor.dll from https://openhardwaremonitor.org/files/openhardwaremonitor-v0.9.6.zip

**Comment by platinum4** [comment]
Thanks, I had copied my folder over

**Comment by Quake4** [comment]
dll updated on MM site from 0.9.5 => 0.9.6
