### ISSUE TITLE
no pools! issue

### ISSUE THREAD

**Issue by mo35** [Quake4/MindMiner#82]
Moved some more rigs to your MM , but some are being plagued by No Pools! error randomly , when its starts , then refreshes are going trough fine. For example , i have identical copy of MM from another working rig , Zergpool enabled , Zergpool apis responds , FW off. 
Honestly , some basic debugging option or logging is kinda must , in case of issues.

**Comment by Quake4** [comment]
No pools-occurs when selected pools do not respond to api requests.
Extend 'LoopTimeout', switch off 'ShowBalance' or use api proxy mode.
