### ISSUE TITLE
[Miner Fix] miniz-17x3 | add kawpow and correct fee for kawpow

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#821]
Hi, there is also a miniz-17x4 out too.

To add kawpow to mini-z miner add this:

`[AlgoInfoEx]@{ Enabled = $true; Algorithm = "kawpow" }`

Add this line to switch case for algos/pars

                  `  "kawpow" { $alg = "--par=kawpow" }`

**Comment by platinum4** [comment]
Set fee for kawpow to 1% too please.

**Comment by Quake4** [comment]
no x4
https://miniz.ch/blog/

**Comment by platinum4** [comment]
Set fee for ethash to 0.75% please

**Comment by platinum4** [comment]
> 
> 
> no x4
> https://miniz.ch/blog/

https://miniz.ch/download-beta/

**Comment by Quake4** [comment]
`also block these algos from MRR until new build from miniz is out`
why?
