### ISSUE TITLE
Why do all the miners fail after a rental contract expires?

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#831]
Hi,

Often times after rental is done on MRR, MM will exit the miner for the rental contract then begin to fail all the miners all the way down to the stack of something like 15 or 20 failed.  This skips many profitable algorithms and has it mine garbage for hours as it the profit switching moves up the stack of failed miners as timeouts elapse for their failed periods.

Why?  I've noticed this happens for months, and if you don't watch MM and catch it to restart MM it will lose out on profitability unless you get lucky and get rented again within a couple of hours.

Can you make it not do this?  The miners fail after like 5 seconds

**Comment by Quake4** [comment]
more like a video card dump

**Comment by platinum4** [comment]
https://i.imgur.com/mB4DpH5.png

CPU mining only on this rig, same exact problem; look at the five seconds

**Comment by Quake4** [comment]
so what happens to the miners, they start up and exit?
5 seconds is the standard interval for checking the miner's health.

**Comment by platinum4** [comment]
Yep they open up in command window then close themselves and fail all the way down the stack of profitability until 0.01

**Comment by platinum4** [comment]
Not resolved but not a big issue, just restart MM

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/141108200-be5f9de9-1203-4c93-aec1-60ff6ae28f29.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/141108309-cc230738-6783-4954-b6d2-af7130cdb36a.png)

**Comment by platinum4** [comment]
Rig survived on X25x and started mining
![image](https://user-images.githubusercontent.com/6779241/141108505-58abd741-dda7-412b-b9d1-8ac9654cb732.png)

**Comment by platinum4** [comment]
This is pretty wasteful since it will take about 3-4 hours to get back up the stack, all mining bad algos (not most profitable)

**Comment by platinum4** [comment]
Looks like I solved an X25x block too

**Comment by platinum4** [comment]
You can see X25x algo is spun up and spitting out stats to MM via API like normal
![image](https://user-images.githubusercontent.com/6779241/141108931-b4d6f735-cda1-42ec-b772-6941d93370a2.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/141109021-cce6e9a3-b512-41d4-8033-6b0bdea6d971.png)

**Comment by platinum4** [comment]
Clear failed state and miners mine fine again
![image](https://user-images.githubusercontent.com/6779241/141109196-4028fa0a-965c-4b1b-a458-0204754a5f17.png)
