### ISSUE TITLE
PhoenixMiner wrong hashrate benchmarking

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#84]
It's calculating in khashes, not in mhashes. PhoenixMiner always down in list, but it shouldn't.

**Comment by Quake4** [comment]
Please, try latest version 2.36.

**Comment by jestercore** [comment]
Bug still there. I'm using MPH, Nicehash, and Zpool.

**Comment by Quake4** [comment]
it is possible, NH can change dag on each job change and bench can get wrong results
