### ISSUE TITLE
[API] miniz-18y3

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#848]
![image](https://user-images.githubusercontent.com/6779241/125336203-1b7d1c80-e313-11eb-9f77-c28cbf759efa.png)

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/125336893-f341ed80-e313-11eb-9398-2b399a9dbd31.png)

**Comment by platinum4** [comment]
Hi, need do

**Comment by Quake4** [comment]
fixed
