### ISSUE TITLE
[Miners] Add defaults for Equihash210 in gminer; Swap in lolminer, cnRWltz in xmrig

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#856]

**Comment by Quake4** [comment]
- has [AlgoInfoEx]@{ Enabled = $true; Algorithm = "equihash210_9" }
- No swap in lol.
- cnRWltz - how?

**Comment by platinum4** [comment]
C29S for lolminer
cn/rwz for xmrig / cryptonight_reversewaltz for xmr-stak

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/141352470-e8996ca1-3c5d-429a-87f6-0c89d31491e8.png)

**Comment by platinum4** [comment]
Version 1.06

    Added support for Cuckaroo-29B (Bittube, use --algo CR29-40 to mine it) for 6GByte and higher cards
    Added support for Cuckaroo-29S (Swap, use --algo CR29-32 to mine it) for 6GByte and higher cards

**Comment by Quake4** [comment]
I don't understand, but there is no pool with SWAP

**Comment by platinum4** [comment]
Gets rented on MRR often & gminer-239f1 fails in Windows 11 due to anti-hack mechanism

**Comment by Quake4** [comment]
add `bin` to exclude folder in WinDefender

**Comment by platinum4** [comment]
Already done, only 239f1 has this problem due to being updated for Windows 11 like at -254

**Comment by Quake4** [comment]
add swap to lol
