### ISSUE TITLE
[Add Feature] Ability to Speculative Mine specific algo & pool while still staying alive for MRR & setting prices based on most profitable algo

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#857]
Hi,

I want to spec mine some coins on another pool or even just zergpool, but I want that to be top priority above mining Ethash (most profitable).

Is there a way to add to pools as top priority speculative.txt so I can have it do RunBefore commands and load my speculative mining choice but still watchdog all pools and take rentals from MRR when they come in.

Running an empty MM with high LowerFloor (so it won't mine anything if not rented) is pointless since I have to watch the machine whole time in case MRR rental comes in.

**Comment by platinum4** [comment]
I still would want to set a LowerFloor so when it's exceeded, it kicks out speculative mining and goes back to Ethash.

**Comment by Quake4** [comment]
Enabled?

**Comment by platinum4** [comment]
{
    "Enabled":  true,
    "AverageProfit":  "45 min",
    "Wallet":  "LTC",
    "SpecifiedCoins": { "x16r": [ "RVL", "only"] },
    "EnabledAlgorithms":  "x16r",
    "DisabledAlgorithms":  null
}
 This just disables all algos on Zergpool and still mines Ethash on Nicehash.
I want it to mine x16r with priority OVER Ethash but still want MRR to set prices based on Ethash, so I can't disable it on NH

**Comment by platinum4** [comment]
I wanna make this a carat like when MRR is rented I want to set an algo and pool as #1 priority even if it's not more profitable than #1 profitable algo

Like when people rent at bad price and MM still forces it to mine to MRR

**Comment by platinum4** [comment]
This way I can mine some ergo and flux and stuff and diversify instead of just mine to NH or MPH because Ethash is most profitable always

**Comment by Quake4** [comment]
_I want it to mine x16r with priority OVER Ethash but still want MRR to set prices based on Ethash, so I can't disable it on NH_
Its do it:
"EnabledAlgorithms": [ "X16r" ],

**Comment by platinum4** [comment]
I did this and it removed all other algos from Zergpool except for x16r, then began mining on NICEHASH.  Why.

**Comment by platinum4** [comment]
I think you need to add in Algorithms.txt or in each pools a "PriorityAlgorithm" and for Zerg also PrioritySpecifiedCoin

**Comment by Quake4** [comment]
_I did this and it removed all other algos from Zergpool except for x16r, then began mining on NICEHASH. Why._
Possibly, you `enable` other algos. Check `^` in MM window. Set all algos to default (not enabled).

**Comment by Quake4** [comment]
`EnabledAlgorithms [string array] - set of enabled (prioritized) algorithms. If the value is null or empty, this means that all algorithms are enabled from the all pools otherwise only the specified algorithms are prioritized on all pools.`

**Comment by Quake4** [comment]
`EnablefAlgorithms` is it a `PriorityAlgorithm` (which one you wanted)

**Comment by platinum4** [comment]
I know what the documentation says, please show me a working example where you have Zergpool mining x16r and have Ethash still enabled but not mining.

I do not think it works like you have typed out in the documentation, I think you think it works but have not tried it.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/140991340-0f8d958e-0411-46b8-8cbb-b78d1761d51c.png)
mine cngpu, most profit eq192

**Comment by Quake4** [comment]
zergpool.config.txt
```
{
    "AverageProfit":  "3 hour",
    "SpecifiedCoins":  null,
    "EnabledAlgorithms": [ "CryptonightGPU" ],
    "PartyPassword":  null,
    "DisabledAlgorithms":  null,
    "Enabled":  true
}
```

**Comment by Quake4** [comment]
^ - priority (EnabledAlgo, solo/party)

**Comment by Quake4** [comment]
some time later (4344 changed to 4347)
![image](https://user-images.githubusercontent.com/29517243/140992340-42b297c2-70da-452b-9215-67cab2c91652.png)

**Comment by Quake4** [comment]
if is you use Master/Slave, you must setup on master.

**Comment by platinum4** [comment]
Hi, I am not using master/slave, I will check on this after work; how many rounds does it take to take effect?

**Comment by Quake4** [comment]
one

**Comment by platinum4** [comment]
OK, this seems to work when selecting a different algo, but now I have a deeper question.

If I set Ethash to enabled for MPH it disables Ethash on NH, since NH is more profitable I want to set MRR based on NH profitability but I want to mine ETH at MPH so I can have ETH.

What compare statement do you need to add?

**Comment by Quake4** [comment]
;)
set upper value in "Target" for MRR.

**Comment by platinum4** [comment]
Gotta be an easier / better answer than that yeah?

**Comment by Quake4** [comment]
where is it easier to change one value?
why invent heroic difficulties for yourself, so that they can be heroically solved later?

**Comment by platinum4** [comment]
I guess man, I take pride on setting the right prices though so I fall cheaper than most others, and stay rented near 24/7

Just seemed like something that was possible, I'm OK with how it is now I guess.

**Comment by Quake4** [comment]
change "target" from default 50 to 60.

**Comment by platinum4** [comment]
Won't get rented at 60 @ 0.1545 electricity, too high

**Comment by platinum4** [comment]
That might work for a 1070 or RX 6600 XT not for 30-series though; too profitable already

**Comment by platinum4** [comment]
I'm set at 42.5 which is 40 + 1 for MM + 1 for MM+MRR + 0.5 increase for myself (dev fee from https://github.com/Quake4/MindMiner/issues/780)

**Comment by platinum4** [comment]
Code appears to work as intended

**Comment by Quake4** [comment]
I don't understand your logic.
Suppose:
profit on Nicehash: 5000 sat
profit on MPH: 4600 sat
difference of 8.7%
set Target to 42.5 + 8.7 = 50%
I don't understand that you are stuck with the profit figures on NiceHash.

**Comment by Quake4** [comment]
The main thing is that you earn more on MR than your current profit.

**Comment by Quake4** [comment]
welcome to https://discord.gg/HrKChEQ
