### ISSUE TITLE
[Miner Feature Request] cpuminer-gr-1.2.x do not kill for 222 minutes

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#859]
Hi, --full-tune on this takes 222 minutes or more, but if I set that in miner config it will just NoHash out after 10 minutes.  When rented it's running for hours so I want the tune_config to generate

**Comment by Quake4** [comment]
Yes. there is such a thing.
Option 1: run with your hands
Option 2: run benchmark and close MM
