### ISSUE TITLE
[Miner] set Ghostrider to $threads, set yespower*/cpupower algos to $cores

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#862]
Need to fix some of these flags in srbminer and cpuminer-opt

**Comment by platinum4** [comment]
@Quake4 you needed to set $extraCores for yespower, yespowerr16, cpupower, yespower2b; instead you set $extraThreads

**Comment by Quake4** [comment]
2 core / 4 thread
![image](https://user-images.githubusercontent.com/29517243/142606582-d3965994-55ec-4d35-a67a-e7b22852c9ce.png)
show at you core/thread + default srbm

**Comment by Quake4** [comment]
on 6/12 cpu, at 5/10.
![image](https://user-images.githubusercontent.com/29517243/142624109-1dba4734-5cec-402c-8cd9-5f0b1ea9897a.png)

**Comment by platinum4** [comment]
User needs to set their own config for best hashrate; is different for many different gens of architecture and cache size; etc.
