### ISSUE TITLE
"TargetByAlgorithm" under Profit does not work

### ISSUE THREAD

**Issue by lukeatspace** [Quake4/MindMiner#887]
When you try to set a TargetByAlgorithm it doesn't work when the single Algorithm is under TargetProfit. Is this Correct?

Kind Regards 

Dominik

**Comment by Quake4** [comment]
If Under is lower? Yes, get max value from target profit and target by algo.
`Max($Cfg.Target, $Cfg.TargetByAlgorithm...`

**Comment by Quake4** [comment]
I'm can fix, and get value from targetbyalgo.

**Comment by lukeatspace** [comment]
sorry for my bad English... 

When your Target is 50% and you set TargetByAlgorithm "Ethash" to 30%. He takes the 50% from Target. I hope this example is better for understanding ;) but I think you know what I mean

**Comment by Quake4** [comment]
Ok.

**Comment by lukeatspace** [comment]
Thank you very much for this great work on Mindminer!
