### ISSUE TITLE
MPH: not show balance for other curriencies

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#89]
i've entered API key, but MindMiner don't show anything.

> "ApiKey":  "bd3dac8eb83963b862039d5e07d0f290aaf015be514b10170a5b69f96ad35601",

Right?

I superlike MindMiner, thank you for your job, keep delevoping, please!

**Comment by Quake4** [comment]
MM show only BTC balance.
You use autoconvert balance? What coin?

**Comment by jestercore** [comment]
Autoconverting to DASH. Lower payout fee, and supported by 2 exchanges on MPH.

**Comment by Quake4** [comment]
I write to MPH to extend getbalance answer, to add support other coins.

**Comment by Quake4** [comment]
2.55
