### ISSUE TITLE
[Bug] MindMiner will mine specified coin to specified wallet in config.txt OVER zpool.txt

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#898]
Hi,

I have Zpool.txt set to Wallet = LTC and have a LTC wallet in config.txt as well.

However, I do have a PBTC wallet address in config.txt

Since I have PBTC available, MindMiner will instead mine anything on Zpool as PBTC, no matter what I set for Zpool.txt, like it ignores it.

Why?

**Comment by platinum4** [comment]
Is it this commit that changed it?

https://github.com/Quake4/MindMiner/commit/7dbbbdb134b5aa13cf80809d81e777095cb2ea10

You should still have it honor what is in Zpool.txt or Zergpool.txt

**Comment by platinum4** [comment]
I suppose easy fix is just remove my wallets from config.txt but let me know if there is any other fix

**Comment by Quake4** [comment]
Check zpool.config.txt variable wallet, you must set LTC.
Pbtc must be assigned if mine pbtc

**Comment by platinum4** [comment]
Already done this is why I made the issue post.
