### ISSUE TITLE
No CPU info  (Temperature/Watts) Intel Core i7-12xxx

### ISSUE THREAD

**Issue by g5-freemen** [Quake4/MindMiner#899]
> MindMiner 7.68   https://MindMiner.Online   (C) 2017-2022 by Oleg Samsonov aka Quake4
> 
> Configuration:
>                Worker Name: PC
>                 Wallet BTC: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Timeout Loop/Check/No Hash: 60 sec/5 sec/10 min
> Hash Speed Average/Current: 8 hours/180 sec
>       Switching Resistance: True as 5% or 12 min
>              Active Miners: CPU, nVidia <= Allowed: CPU, nVidia, AMD, Intel
>                 API Server: Disabled
>                     Region: Europe
> 
> CPU x 1: 12th Gen Intel Core i7-12700KF, 3600 Mhz, 12/20 Core/Thread, 99.4 %, 0 C, 0 W, MMX SSE SSE2 SSE42 AES SHA AVX AVX2

**Comment by Quake4** [comment]
Pls, check in new version.
https://github.com/Quake4/MindMiner/releases/tag/v7.70

**Comment by g5-freemen** [comment]
Everything ok. Thanks 19 февр. 2022 г. 16:52 пользователь Oleg Samsonov ***@***.***> написал:
Pls, check in new version.
https://github.com/Quake4/MindMiner/releases/tag/v7.70
