### ISSUE TITLE
Add new Lyra2v2 miner for AMD

### ISSUE THREAD

**Issue by jestercore** [Quake4/MindMiner#90]
> This new miner was released and it's the fastest Lyra2v2 miner I've seen for AMD
> 
> https://github.com/CryptoGraphics/lyclMiner
> 
> Speeds here:
> https://www.reddit.com/r/vertcoin/comments/8svyvr/amd_full_release/

And delete sgminer-nicehash-561, we don't need it anymore!

**Comment by Quake4** [comment]
It has no api.
really 34 Mh on 580/4.

**Comment by Quake4** [comment]
You can sign my essage in his repo. Hot my. 
https://github.com/CryptoGraphics/lyclMiner/issues/2

**Comment by platinum4** [comment]
What about mkxminer? https://bitcointalk.org/index.php?topic=2360168

**Comment by Quake4** [comment]
lycl faster. and dont have api same.

**Comment by Quake4** [comment]
Lyra2v2 go to asic. Isn't actual.
