### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Minhe173** [Quake4/MindMiner#900]
my balance in this miner still unconfirmed for 4 days

**Comment by Minhe173** [comment]
@Quake4

**Comment by Quake4** [comment]
where is screen, pool, other info?

**Comment by Minhe173** [comment]
![image](https://user-images.githubusercontent.com/88653001/156147800-2f0d2e72-2717-4450-9915-8b7cf1a93814.png)

**Comment by Minhe173** [comment]
1 week pending...

**Comment by Quake4** [comment]
https://www.nicehash.com/support/mining-help/earnings-and-payments/when-and-how-do-you-get-paid
the minimum is 1000 satoshi. yours unpaid is only 23 satoshi.

**Comment by Minhe173** [comment]
ok thx
