### ISSUE TITLE
Argon2d16000 broken on MRR after bad mapping, rigs do not show up

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#904]
Hi,

No idea why this got mapped to Argon2d16K it shows up no more on MRR due to this choice please fix ASAP.

**Comment by platinum4** [comment]
Add only one line to mapping, exact as below:

"argon2d_16000" = "Argon2d16000"

No more.  Please.

**Comment by Quake4** [comment]
you must wait master update
