### ISSUE TITLE
Profit discrepancy

### ISSUE THREAD

**Issue by undefy** [Quake4/MindMiner#905]
Dear all,
I have 2 x 6 1060 gb gpus using different miner managers (mindminer & rainbowminer) mining same algo but have different returns at almost same speeds... Can some one more knowledge savvy explain please? equihash 144 5 @ 249.45 H/s i get 2.36 USD and @ 222,11 H/s i get 1.67 USD... Is one of them wrong? Images via [link](https://drive.google.com/drive/folders/1xPHQqY6JPN1BG8KqctT0LxHxGIKjstiq?usp=sharing)(view only)

**Comment by Quake4** [comment]
1. In this case, rent, so how much you earn shows MRR.
2. For MRR, the profit is calculated approximately relative to the current speed and the speed declared on the MRR and from the set price..
3. I do not know what rainbowminer is showing there
The screenshot shows `+-40/130%`
1. That you rented out cheap `-40%` of the most profitable mining on the pool.
2. Your stated speed is much less than it really is (the current speed is 130% of the stated one).

**Comment by undefy** [comment]
> 1. In this case, rent, so how much you earn shows MRR.
> 2. For MRR, the profit is calculated approximately relative to the current speed and the speed and price declared on the MRR.
> 3. I do not know what rainbowminer is showing there
> 
> The screenshot shows `+-44/130%`
> 
> 1. That you rented out cheap `-44%` of the most profitable mining on the pool.
> 2. Your stated speed is much less than it really is (the current speed is `130%` of the stated one).

Thank you for the prompt reply and a very good explanation. Is there away to modify how cheap I can rent out?

**Comment by undefy** [comment]
Also, according to [2miners](https://2cryptocalc.com/equihash-144-5-algorithm) - 19500 Sol/s on Equihash 144_5 gives 43.52 USD... this means I should be getting 0.556 USD from 249.16 H/s. I turned off MRR and now  from MPH-EU-BTG | miniz-nv-1.9z2 | EquihashBTG | 215,20 H/s @ 0.00009282 btc/day so that's 1.76 USD/Day. Please correct me if I'm wrong... but

1. mining MPH is more profitable but MRR was mined, but MRR was used anyway. Why is that? Is there a flag somewhere to prioritize MRR? All settings are stock
2. How come there is such a difference between 2miners reward and MPH reward? Earning value is correct?

**Comment by Quake4** [comment]
Such data is returned by the MPH API. If it overestimates, I suggest disabling MPH and not using it anymore. For example, I don't use it.
