### ISSUE TITLE
exit miner

### ISSUE THREAD

**Issue by asinyutincrypto** [Quake4/MindMiner#906]
Hello! Please tell me if it is possible to use stop.bat instead of CTRL + E / ALT + Q and what it should contain, it is required to remotely control the mining process on hosts

**Comment by Quake4** [comment]
Hello, there is no such function provided.

**Comment by asinyutincrypto** [comment]
как тогда отключить автообновление?

**Comment by Quake4** [comment]
нет такой возможности
