### ISSUE TITLE
AMD RX 580 not working drivers

### ISSUE THREAD

**Issue by zeze6** [Quake4/MindMiner#908]
hello
i have AMD RX 580 8gb ram 256bit ..
everytime i format to install drivers i get huge problem..screen turns off and never come back
when i do restart it try to open windows then goes off again
i have to reformat again and again
but i can use the car without drivers
but when i run your awesome software i get errors like opencl.dll file is missing i keep getting this one and
another file missing starts with V don't remember the name..
many people online facing the same issue with this card using windows 10, i just installed windows 11 to try out
help!

**Comment by Quake4** [comment]
a faulty card or monitor dosn't support default resolution and refrash rate

**Comment by zeze6** [comment]
excuse me i somehow figured out how to install drivers in safe mode but no signal in normal mode
when i try to install drivers...
what is the resolution and refrash rate should be? thank you

**Comment by Quake4** [comment]
there is another option, if the monitor is connected with an hdmi or dvi cord, and its default resolution is, for example, 4k and 60Hz, perhaps the cord does not pass the required resolution. it is necessary to set the minimum resolution and refresh rate or replace the cord.

**Comment by zeze6** [comment]
mine set to 800x800 60Hz and can't change it is that not right? do i need to replace the cable?

**Comment by Quake4** [comment]
who cares what the resolution is, the main thing is that mining is going on

**Comment by zeze6** [comment]
that's right :) i will keep trying, thank you
