### ISSUE TITLE
Claymore API not working nvidia/amd

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#99]
tested with ethash miner and claymore amd neo

neo was running for 2hrs, ethash 1hr on other rigs, never saved stats

**Comment by Quake4** [comment]
Perhaps this bug is related to `claymore-cn-40`? It stop MM.
remove `claymore-cn-40`

**Comment by platinum4** [comment]
i already removed it, still happening

https://i.imgur.com/RRgLpB8.png

**Comment by Quake4** [comment]
Please copy data from `Type: nVidia` to `+ Running`

**Comment by platinum4** [comment]
6 hours continuous, never finished any loop

**Comment by platinum4** [comment]
https://i.imgur.com/vMlQWEU.png

**Comment by Quake4** [comment]
Disable "quick edit mode" for console window.

**Comment by Quake4** [comment]
yes, bug confirmed. try find it

**Comment by platinum4** [comment]
Worked fine on 2.49 prior to cn40 removal

**Comment by Quake4** [comment]
after add dredge

**Comment by platinum4** [comment]
I was impressed you got dredge api to pull hashrates, I couldn't, just power draw and compute.  Maybe you made change to API include

**Comment by Quake4** [comment]
Fixed in 2.53. Thanks.

**Comment by Quake4** [comment]
Rerun MM.

**Comment by platinum4** [comment]
OK I'm off in a few hours I will try it when I can monitor them.

**Comment by Quake4** [comment]
thanks
